### PR TITLE
fix: identify and format amount inside notes

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Identify and format amount inside notes

### CODE REVIEW

**Comment by yabirgb** [comment]
Looks good but for the approvals it losses the scientific notation and it is a bit weird here. Do you believe something is possible to fix this? 
image

**Comment by lukicenturi** [comment]
> Looks good but for the approvals it losses the scientific notation and it is a bit weird here. Do you believe something is possible to fix this? image

Im not sure, the amount on some of the approval events is kinda weird (its very long)

**Comment by yabirgb** [comment]
> > Looks good but for the approvals it losses the scientific notation and it is a bit weird here. Do you believe something is possible to fix this? image
> 
> Im not sure, the amount on some of the approval events is kinda weird (it's very long, till the numeric library in frontend can't handle it anymore)

That number is 2**256-1 that is the biggest number you can represent in ethereum (I guess). Doesn't the BigInt library handle this?

**Comment by lukicenturi** [comment]
> > > Looks good but for the approvals it losses the scientific notation and it is a bit weird here. Do you believe something is possible to fix this? image
> > 
> > 
> > Im not sure, the amount on some of the approval events is kinda weird (it's very long, till the numeric library in frontend can't handle it anymore)
> 
> That number is 2**256-1 that is the biggest number you can represent in ethereum (I guess). Doesn't the BigInt library handle this?

Fixed, can you check again? @yabirgb

**Review by kelsos — APPROVED** [review]
lgtm on my side too

**Pull request merged**
