### PR TITLE
Rewrites the electron app in vue.js

### LINKED ISSUE #354: Rewrite electron app in Vue.js
## Abstract

I am opening this issue to keep track of the tasks need to be performed to properly migrate the electron-app to Vue.js.

## Motivation

jQuery is outdated and not fit for modern app development, it makes maintenance and development harder. 

Some of the problems witht he current structure include:
- It doesn't provide hotswapping (webpack) so the app has to be restarted for every single change
- No template support, which makes it harder to debug and modify the ui.
- No [data reactivity](https://vuejs.org/v2/guide/reactivity.html) which means that changes have to be tracked by hand.

## Specification

- [x] Restructure and split the electron app to its own folder. e.g `/app` or `/electron-app`.
- [ ] Rewrite and completely remove jQuery and plugins.
  - [ ] Break functionality to small testable components.
  - [ ] Write unit tests for the new components.
  - [ ] Use vuetify to replace most common components.
  - [ ] Rewrite table functionality with vuetify component and remove DataTables.
  - [ ] Rewrite dialogs and remove jConfirm.
  - [ ] Rewrite first run pulsate with pure CSS.
- [ ] Ensure that the integration tests work.
- [ ] Modify scripts to properly package the electron app.
- [ ] Setup coverage for the electron-app

### PR DESCRIPTION
**Pull request by kelsos**
Opening the PR to keep track of the work done on the vue - rewrite of the app.

Remaining tasks for the PR
- [x] Add first login dialog
- [x] Add Update message
- [x] Add premium dialog
~~- [ ] Fix the e2e tests~~(after merge)
- [ ] Fix packaging
   - [x]  Add packaging targets
   - [x] Upgrade package scripts
   - [ ] Modify CI deployment
- [x] Add context actions to OTC Trades
- [x] Check if OTC is up to date
- [x] Rebase on master
- [x] Rewrite cointracking import functionality
- [x] ETH Account table should be expandable (show the account tokens)
- [x] Messages (Upgrade dialog) should not appear on errors
----
of things needed to finalize this PR:

- [x] Include `package.sh` changes from #552
- [x] Rebase on master. Implement check for analytics
- [x] Evaluate conditional expand on ETH Accounts
- [x] Find a better way to emphasize already setup account.
- [x] Fix currency change after rebase
- [x] Show exchange balances on the dashboard
- [x] Fix OTC edit/delete functionality
- [x] Greyscale Exchange icons
- [x] Fix premium support
- [x] Check and make sure Tax Reporting works properly and shows valid progress

Extra:
- [x] Rewrite Statistics

Closes #354

### CODE REVIEW

**Comment by kelsos** [comment]
So I have an idea why the currency set/NAN happens if you check the header it says `value` when it should say `EUR value` and since I am using the current currency for the calculation thus the NaN.

The most curious thing is why it works locally. I remember seeing a change in the `setCurrency` method when I rebased on top of master yesterday so that should not be a hard fix.

OTC trades I am already aware it broke when I upgraded to the latest Vuetify, I already have it as a todo.

About the grid for the exchange icons should is the problem only with cointracking or is it something different?

On the progress bar, I had similar negative progress issues with the calculations on the retail, I have to re-evaluate.

on 3 the blockchain balances update together right? so the other missing balances are practically the exchange balances that are currently not displayed. 

I will have to set it up and go again through the premium flow.

Statistics won't work at the moment due to the fact that they depend on the implementation details of the live version. I think I mentioned it before. But the last part of the rewrite after everything works is to also update the statistics.

Thanks for the feedback, I will finish the tests and then start fixing the current issues.

**Comment by LefterisJP** [comment]
> About the grid for the exchange icons should is the problem only with cointracking or is it something different?

Cointracking? Cointracking is not an exchange. No this is only that in the previous version it was a grid. So three exchanges first row, three exchanges last row.

> On the progress bar, I had similar negative progress issues with the calculations on the retail, I have to re-evaluate.

There used to be but I fixed it with a PR. So it either still is or somehow with the rewrite it relapsed.

> on 3 the blockchain balances update together right? so the other missing balances are practically the exchange balances that are currently not displayed.

Yes. But they have been queried since for example I can see them if I click on any exchange's icons.

**Comment by kelsos** [comment]
@LefterisJP yes I meant coinbase, my mistake I was merging the coin tracking info import yesterday, thus the mistake

I will check master to be sure. Maybe when I implemented the progress the fix was not merged yet.

Yes, the problem is that I had no clue that exchange data were displayed there, so 3-4 is the same issue I just don't show them at all. It should be easy to modify the getter to include them

**Comment by LefterisJP** [comment]
So I had another look as requested and will write out what I found.

## Need to do pip install -e.

For some reason the electron app does not discover the python process without `pip install -e .`. I do not think this was the case before but I would have to check.

## Multiple balances of same asset in "All balances"

For some reason in the "all balances" table in the dashboard there are multiple entries for different assets. Perhaps since it does not sum up the locations (e.g. exchanges, blockchain, banks)?

2019-11-09-114829_966x229_scrot
2019-11-09-114944_793x177_scrot

## Missing Grey out/Green out of exchange premium key if it's already registered.

In the current version if an exchange is already registered (also if premium is working) the respective api key/secret fields are green/greyed out so that the user knows he can't input a new key unless he presses the remove button.

2019-11-09-115041_956x476_scrot

## Missing a way to provide tokens location per ETH account

2019-11-09-115755_897x187_scrot

In the original UI you could see how many/which tokens each account holds. It is indeed subtoptimal since for each token there was a new column in that table and as such became too big and needed scrolling. Perhaps as you suggested in our chat add it as hidden info per account that can be shown? You could have another column `Number of tokens owned by account` or something like that. The name needs to be shorter I guess. And there show a number of how many tokens the account owns. So if the account has `GNO`, `RDN` and `OMG` the number will be 3. And then when you press that number show you details about these tokens and expand the entry.

## Did not pick up the main currency from settings

The main currency of the account should have been `EUR` when starting but the UI showed `USD` when it started. So for some reason it did not pick up the user's saved currency from the settings.

## UI element has no padding

This is rather minor but the UI element of the start date does not seem to have enough distance from the "Main currency selection"

2019-11-09-120918_931x155_scrot

## Editing a date should start from date that is being edited

I am trying to edit a date for a trade and wanted to make it 1 day later. But when clicking the UI element it starts from the current date. It should start from the date that is being edited.

2019-11-09-121124_620x463_scrot

## Editing/deleting external trades does not work

2019-11-09-121326_482x183_scrot
2019-11-09-121354_471x181_scrot

Perhaps something wrong with a rebase? There were some changes there.

## Data import margin/padding

Super minor ... but it looks ugly at the moment. There is no padding/margin to separate from the left and top menus.

2019-11-09-121542_1177x524_scrot

## Tax report warning

The new progress bar looks much better. I think it would be nice to have a message there too warning the user that this will probably take a lot of time if he has done many trades and/or if the period is long. One thing to keep in mind here is that the report will go through all trades/actions no matter when the user set the start period since it needs to know about all actions that happened.

2019-11-09-121750_1094x497_scrot

## Missing is_virtual marker from trades report

At some point there is some trades of selling BCH for BTC. That creates also a virtual trade of buying the equivalent BTC amount with EUR but there is nothing in the virtual column.

2019-11-09-123030_1134x256_scrot

**Comment by LefterisJP** [comment]
Looking at the new stuff I guess:

The ui of the api keys still does not really show that it's not inputtable. I indeed can't click on an exchange that is already registered but it's not really visible that it's greyed out. Something a bit more obvious would be nice. Does not need to be as much highlighted as it is in the current version.

2019-11-12-235751_894x215_scrot


I like the way the tokens show for the accounts now, but perhaps it should be a bit more obvious that they can be expanded. Not sure how. We should think on it.

One note though. The accounts that have no tokens should not be expandable. The arrow should be missing for them.


I also saw this warning in the dev tools:

```

vue.runtime.esm.js:619 [Vue warn]: Property or method "floatingPrecision" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <AccountAssetBalances> at src/components/settings/AccountAssetBalances.vue
       <VSimpleTable>
         <VData>
           <VDataTable>
             <AccountBalances> at src/components/settings/AccountBalances.vue
               <VCard>
                 <BlockchainBalances> at src/components/settings/BlockchainBalances.vue
                   <User> at src/views/settings/User.vue
                     <VContent>
                       <VApp>
                         <App> at src/App.vue
                           <Root>
```


The rest of the concerns of the last comment seem to be addressed.

**Comment by kelsos** [comment]
@LefterisJP Could you have a look at the packaging and how it works for you? 
Build on macOS, Windows and Linux and see how the builds work.

To be safe rename/delete the `node_modules` folder to make sure that the `zeromq` module is not picked from the absolute path.

The build targets are dmg for macOS, a portable executable for Windows and a tar/AppImage for linux.

**Comment by kelsos** [comment]
@LefterisJP everything should be ready for testing and reviewing. 
The only thing left to be done is to modify the deployment to use the new files. 

How do you want to proceed from here?

**Comment by LefterisJP** [comment]
So testing along with the premium stuff like statistics is ready? If so I need to rebuild the ranch and test it.

**Comment by LefterisJP** [comment]
So from the premium statistics the only thing that I see is the order is wrong.

It should be:
1. Total netvalue
2. Netvalue by asset
3. Distribution by asset
4. Distribution by location.

Also the start date dropdown is kind of annoying as it insists to be provided time. If I start typing I want the calendar view to not hide the typing. And If I type "01/01/2016" and press Enter it should work and not tell me I have to enter the hour too.

**Comment by kelsos** [comment]
@LefterisJP Can you open that as an issue to the repo of the statistics? I will try to fix them tonight.

**Comment by LefterisJP** [comment]
After merging the latest premium components and continuing testing I noticed this warning in the console. It is emitted directly at the start of the app:
```
(node:22992) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Also still as before letting the app query all blockchain balances seems to over-write the balances of an asset found in the exchanges. For example the test user had `X` BTC in all exchanges and `Y` in the bitcoin blockchain. When the app firs quries exchanges the BTC balance shows as `X` and then later once the blockchain balance query came in he had `Y` instead of `X+Y`

Same for other assets, for example kraken EUR balances being overwritten by banks EUR balances, instead of getting added.

Finally for the premium statistics I would like some default values for the charts as they were before.

1. The netvalue graph should have the entire range of data as its default value.
2. The Asset amount and value over time graph does not need a default value but can be as (1) for the first asset on the list.

**Comment by LefterisJP** [comment]
Hey @kelsos as discussed the default branch for development of big features has been changed to develop. I updated the PR to reflect this. Make sure you are aware of this when you do anything with it.

**Comment by LefterisJP** [comment]
Hey @kelsos so I think that it's mostly working and we will need to iron out any other bugs we find. But at this point this should be merged to develop so that the other big change can also be rebased on top of it. Do you agree?

Can you add a changelog entry also? Since you are the author of the change choose the words, but try to focus on modern/sleek UI which is also easily customizable.

**Comment by kelsos** [comment]
@LefterisJP sure I will add it and we can merge on develop then

**Pull request merged**
