### PR TITLE
Adds defi icons to the app and ignores the icon returned from zerion

### LINKED ISSUE #1689: Replace defi protocol icons fetched from Zerion SDK
## Problem Definition

We need to remove the reliance on Zerion SDK's metadata for icons since it is deprecated and it will be removed.

> As for icons -- metadata for protocols has been deprecated and will be removed in the next release, so you should not rely on it (yes, we stopped downloading icons for the latest protocols)

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1689

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
The icons seem to work fine. Do you want to merge and I do the removal on the backend? Or can you also handle it? It should be simple

**Comment by kelsos** [comment]
> The icons seem to work fine. Do you want to merge and I do the removal on the backend? Or can you also handle it? It should be simple

let me take care of the backend part too no worries

**Comment by kelsos** [comment]
@LefterisJP it seems that all the protocol data is in the balance response so there is no extra call. For this reason I only removed the `icon` property.

**Review by LefterisJP — APPROVED** [review]
LGTM

**Comment by LefterisJP** [comment]
Something is super strage. The backend in the github actions failed on a non-existing test. The test exists only on develop and this needs rebasing on it.

I will rebase and run locally.

**Comment by LefterisJP** [comment]
Ok rebased on develop and pushed a commit to fix that exact test which was only on develop. Was instantiating a `DefiProtocol(...)` and as such was failing since you changed the signature to remove the icon link.

So that's interesting. Actions ran the tests as if they are merged on develop. Not sure if travis did the same.

**Comment by kelsos** [comment]
> So that's interesting. Actions ran the tests as if they are merged on develop. Not sure if travis did the same.

Interesting indeed. do you need me to do something here in order to merge this

**Comment by LefterisJP** [comment]
I need the tests to pass. I rebased on develop and fixed one test last night. I still see red. Would need to investigate.

**Comment by LefterisJP** [comment]
Seems like it was a cryptocompare hiccup

**Comment by LefterisJP** [comment]
Merging since I think it was just a temp hiccup. Test does pass locally.

**Pull request merged**
