### PR TITLE
Adds frontend support for sushiswap

### LINKED ISSUE #2426: Add Sushiswap support
## Abstract

It seems that Sushiswap transactions are not currently picked up as trades in the profit/loss section of the application

## Motivation

Sushiswap is one of the primary decentralised exchanges and I would imagine that since it is a Uniswap fork, it should take less code to implement this feature than to implement tracking for an entirely different decentralised exchange

## Specification

N/A

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2426 

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

- I will add the update of the docs after the review/fixes
- need to test the backwards support

### CODE REVIEW

**Review by LefterisJP — APPROVED** [review]
So from a quick look it looks fine.

Probably at testing time would find more problems but the little bit I tested looks okay. The thing I need to fix in the backend is the export of the event type for sushiswap. Oh and also to add a changelog entry.

I will do them myself and push here.

Afterwards can you check the components backwards compatibility and edit the docs?

**Review by LefterisJP — CHANGES_REQUESTED** [review]
Actually there seems to be a problem at sushiswap burn. There is no amount or token shown.

**Comment by kelsos** [comment]
> Actually there seems to be a problem at sushiswap burn. There is no amount or token shown.
> 
> 

This was pushed on the components repo yesterday

**Review by LefterisJP — APPROVED** [review]
LGTM!

**Pull request merged**
