### PR TITLE
Add support for renBCH & renZEC tokens

### PR DESCRIPTION
**Pull request by bakkdoor**

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Hey @bakkdoor thanks for the PR.

As per the failing test when adding new assets you also need to edit the assets test and adjust the md5:

rotkehlchen/tests/unit/test_assets.py::test_assets_json_meta

```

2020-11-26T05:50:34.4056914Z =================================== FAILURES ===================================
2020-11-26T05:50:34.4060415Z ____________________________ test_assets_json_meta _____________________________
2020-11-26T05:50:34.4061289Z 
2020-11-26T05:50:34.4062194Z     def test_assets_json_meta():
2020-11-26T05:50:34.4063488Z         """Test that all_assets.json md5 matches and that if md5 changes since last
2020-11-26T05:50:34.4064805Z         time then version is also bumped"""
2020-11-26T05:50:34.4067165Z         last_meta = {'md5': '21b8c3a8fe0cd22029aeb550ba1aad24', 'version': 24}
2020-11-26T05:50:34.4069569Z         data_dir = Path(__file__).resolve().parent.parent.parent / 'data'
2020-11-26T05:50:34.4071313Z         data_md5 = file_md5(data_dir / 'all_assets.json')
2020-11-26T05:50:34.4072342Z     
2020-11-26T05:50:34.4073628Z         with open(data_dir / 'all_assets.meta', 'r') as f:
2020-11-26T05:50:34.4074814Z             saved_meta = json.loads(f.read())
2020-11-26T05:50:34.4076105Z     
2020-11-26T05:50:34.4077336Z         assert data_md5 == saved_meta['md5']
2020-11-26T05:50:34.4078267Z     
2020-11-26T05:50:34.4079402Z         if data_md5 != last_meta['md5']:
2020-11-26T05:50:34.4080343Z             msg = (
2020-11-26T05:50:34.4081804Z                 'The md5 has changed since the last time assets.json was edited '
2020-11-26T05:50:34.4083427Z                 'and the version has not been bumped',
2020-11-26T05:50:34.4087631Z             )
2020-11-26T05:50:34.4089232Z >           assert saved_meta['version'] == last_meta['version'] + 1, msg
2020-11-26T05:50:34.4091260Z E           AssertionError: ('The md5 has changed since the last time assets.json was edited and the version has not been bumped',)
2020-11-26T05:50:34.4092484Z E           assert 26 == (24 + 1)
2020-11-26T05:50:34.4092902Z 
2020-11-26T05:50:34.4093734Z rotkehlchen/tests/unit/test_assets.py:199: AssertionError
```

**Comment by bakkdoor** [comment]
I knew I had forgotten something 😅

**Comment by LefterisJP** [comment]
Ah no I tried to resolve conflict with the browser but it's ugly. Made a merge commit. Let me rebase manually.

**Comment by LefterisJP** [comment]
So we don't run the CI 100 times, I am just including your commit in the PR I just opened: https://github.com/rotki/rotki/pull/1813. So just closing this.

**Comment by bakkdoor** [comment]
👍

**Pull request closed without merging**
