### PR TITLE
Introduces kraken staking frontend

### LINKED ISSUE #569: Support Kraken's staking feature
## Description

Kraken has [introduced](https://blog.kraken.com/post/3299/staking-xtz-available-on-kraken/) crypto staking from within its interface.

Rotki should also be able to support it provided there is a way to access this data from their [API](https://www.kraken.com/features/api#private-user-data).

Premium only.

Related to: https://github.com/rotki/rotki/issues/473

## Task

Support staking from inside Kraken

### PR DESCRIPTION
**Pull request by kelsos**
Closes #569

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Update the changelog

### CODE REVIEW

**Comment by yabirgb** [comment]
I was specting names to be next to icons on the left
image

Also text is not displayed
image

**Review by LefterisJP — COMMENTED** [review]
We probably need to have a better staking landing page. When I loaded I saw an empty page.
Had to scroll up to see a dropdown.
Wouldn't some kind of big buttons (for the amount of staking we have now) be better? Panel-like buttons? Something like this:



Eventually perhaps if we make all staking events the same type we can even have a common staking page for all, but for now perhaps this approach is good. I think this kind of intro page to staking is better than what I saw in the PR.

**Review by LefterisJP — COMMENTED** [review]
Another thing I would like to see in the frontend @kelsos is a sum of assets gained for the given filter just like in eth staking.

For example:

Without any filter:

all assets and how much was gained for all of them. For example:
20 XTZ (50 EUR with value at the time of events) / 40 EUR with current value
30 DOT (100 EUR with value at the time of events) / 85 EUR with current value 
etc.

If a filter is given, do same thing but only for the given filter.

**Review by LefterisJP — COMMENTED** [review]
Hey @kelsos thanks. There is still some things missing.



1. The two panels on top seem quite mismatched. The left has nothing but the word Total and a value in the user's currency. Say 100 EUR. I would expect the two different total calculations as  discussed in the previous review.
2. The right panel has all the staked assets detected.  But what it's missing is what I already asked in the previous review [here](https://github.com/rotki/rotki/pull/3968#pullrequestreview-862140678). Specifically the ability to: 
    1. see the profit currency (USD/EUR etc.) value per asset and 
    2. the ability to see the value in the historical and he current price just like we do in ETH2.  
    3. Finally here make sure to change the name "Received" to "Earned".
3. The "value" column is still wrong. It needs to have the name of the profit curency (USD/EUR etc.) and be changing when the selected currency changes.


Now ... for the layout on how to achieve the requested changed I am not 100%. But perhaps the left panel won't look so empty after all if you put both the total with current prices and the total with historic prices.

Some more minor problems below:



4. These filter descriptions need to be updated
5. When filtering by asset I would expect the other assets to dissapear from the "Received" panel, but they are still left there.

**Pull request merged**
