### PR TITLE
rotkehlchen/data/all_assets.json: add chai token data

### PR DESCRIPTION
**Pull request by MrChico**
adding chai support as I need it :)
is there anywhere else I need to add it or is this it? (it has a cute logo but not sure where to add it)

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hey @MrChico thank you for your contribution!

Is CHAI trading in any centralized exchange that Rotki supports? I guess not?

To make this work we would need to have CHAI's price queriable. Cryptocompare does not support it, but we can simplify (as probably should be done for cDAI) if we consider it equivalent to DAI.

Add a mapping of `'CHAI'` to `'DAI'` here:
https://github.com/rotki/rotki/blob/7b8074477e19c5569cb7b8469f61ebe1dd7e2b88/rotkehlchen/constants/cryptocompare.py#L1

Also add a changelog entry for the newly supported assets in the changelog for the next release [here](https://github.com/rotki/rotki/blob/7b8074477e19c5569cb7b8469f61ebe1dd7e2b88/docs/changelog.rst) right under VRA.

> it has a cute logo but not sure where to add it

For logos we depend on an external package: https://github.com/atomiclabs/cryptocurrency-icons

You can check if the CHAI logo is there and if not make a PR to add it. But they seem to have slowed down with their releases.

**Comment by MrChico** [comment]
It does not exist on any centralized exchanges yet afaik. Plenty of decentralized ones though. It's dai price will become more skewed over time. Do you support coingecko as a price feed? https://www.coingecko.com/en/coins/chai/ this is what etherscan uses to get the chai price

**Comment by LefterisJP** [comment]
> It's dai price will become more skewed over time. Do you support coingecko as a price feed?

No unfortunately not. Will need to add it as a feed at some point.

**Comment by LefterisJP** [comment]
We do have an issue for adding additional price and historical price feeds. If coingecko has CHAI then I just prioritize as the first additional feed to cryptocompare: https://github.com/rotki/rotki/issues/224

But the above issue would need some work so probably still makes sense to consider CHAI price equal to DAI for now and make an issue to replace the mapping when coingecko support is there.

**Comment by MrChico** [comment]
Makes sense. Current difference between chai and dai is 1%. Feel free to use DAI for CHAI price until coingecko support arrives

**Comment by LefterisJP** [comment]
Thanks @MrChico and congratulations on your first PR in Rotki :smile: 

I will make an issue about changing the price feed of CHAI as soon as coingecko is supported.

**Pull request merged**
