### PR TITLE
Introduces client support for websocket connection

### PR DESCRIPTION
**Pull request by kelsos**

### CODE REVIEW

**Comment by kelsos** [comment]
Like we discussed I checked both in docker and package that it works fine.
I probably need to figure out what happens if the connection is lost due to a network error to handle

**Review by LefterisJP — COMMENTED** [review]
Wow what the heck happened and you have -10k lines?

Seems to work ... but something is wrong with the date of the notifications.



Seems to be this

```typescript
  timeDisplay(date: Date): string {
    return dayjs(date).format('LLL');
  }
```

But you did not add it in this PR so not sure what's wrong exactly.

**Comment by kelsos** [comment]
> Wow what the heck happened and you have -10k lines?
> 
> Seems to work ... but something is wrong with the date of the notifications.
> 
> 
> 
> Seems to be this
> 
> ```ts
>   timeDisplay(date: Date): string {
>     return dayjs(date).format('LLL');
>   }
> ```
> 
> But you did not add it in this PR so not sure what's wrong exactly.

I recreated the package-lock.json and it seems that it removed some stuff
It seems that dayjs doesn't support the LLL format. I will have to check what I can replace it with.

**Comment by yabirgb** [comment]
> I recreated the package-lock.json and it seems that it removed some stuff
> It seems that dayjs doesn't support the LLL format. I will have to check what I can replace it with.

Seems to require a plugin https://day.js.org/docs/en/display/format#localized-formats

**Comment by kelsos** [comment]
I enabled it in #3159

**Comment by LefterisJP** [comment]
Why not same PR? Harder to test now

**Review by LefterisJP — APPROVED** [review]
Works when merging the other PR.

**Comment by kelsos** [comment]
> Why not same PR? Harder to test now

Why would it be harder to test? They are two unrelated issues. The date thing was happening on the develop branch too. We had notifications before introducing the websockets.

**Pull request merged**
