### PR TITLE
Disables asset type selection when editing an asset

### LINKED ISSUE #3479: Cannot change asset type from 'fiat' to 'ethereum token'
## Problem Definition

I accidentally added PUDGY (https://www.coingecko.com/en/coins/pudgy-vault-nftx) as a 'fiat' asset. When I tried to change it to an 'ethereum token' instead, I got the message 'Tried to edit non existing ethereum token with address 0xabea7663c472648d674bd3403d94c858dfeef728'. I ended up deleting the asset and re-adding it, but it seems like it should be possible to edit the asset type. Screenshot is attached.

### System Description

Operating system: macOS 11.4
Rotki version: 1.20.1

Screen Shot 2021-09-18 at 17 02 48

### PR DESCRIPTION
**Pull request by kelsos**
Closes #3479

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by yabirgb — APPROVED** [review]
Thanks sir

**Comment by yabirgb** [comment]
@kelsos seems that it has conflicts in the changelog

**Comment by kelsos** [comment]
Well, that is a constant problem we have isn't it? :D

**Comment by LefterisJP** [comment]
> Well, that is a constant problem we have isn't it? :D

A good trick to avoid these conflicts especially if you got two PRs of your own that may cause it is to add one entry at the bottom and the other PR entry at the top!

**Pull request merged**
