### PR TITLE
Fix ETH2 empty asset distribution

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by kelsos — APPROVED** [review]
code looks good the functionality will be reviewed by @LefterisJP

**Review by LefterisJP — APPROVED** [review]
Looks good @lukicenturi. Can you also add a changelog entry (without an issue since I did not open one)

**Comment by kelsos** [comment]
Hmm the updated cypress and flakiness fixes are on develop, aren't they?

**Comment by lukicenturi** [comment]
> Hmm the updated cypress and flakiness fixes are on develop, aren't they?

AFAIK, it's on both bugfixes and develop

**Pull request merged**
