### PR TITLE
Introduces persistence of graph timeframe

### LINKED ISSUE #1810: User should be able to select default timeframe in dashboard & timeframe should persist during session
## Abstract

A few improvement suggestions for the dashboard chart:
1. The user's choice of selected timeframe should persist throughout the session (e.g. if I set it to "1W" and then browse away and back to Dashboard, it should be on "1W")
2. The user should be able to select their "default" timeframe (i.e. what is shown at startup)
3. The user should be able to enable/disable specific timeframes if they don't want to see buttons for all 6 (and I guess you can add more options such as 6M, 2Y, etc.)

## Specification

Can probably just use the front-end settings that kelsos created for this.

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1810 

- The timeframe set on the settings should be selected when login in.
- Changing the timeframe on the dashboard, navigating away and returning to the dashboard should not reset the selection.

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
I see this is the PR that touches a lot of the settings code.

But I am not sure how it's supposed to work.

1. Why not simply remember the last chosen selection in the dashboard? Why do you need to set this in the settings? It doesn't look like good UX to me. What I would expect is set it in the dashboard and have it remembered whenever I go there again.

2. I tried it and it does not seem to work. What I did:
     a) Went the dashboard and set it to 2W.
     b) Then went to settings and made the default 1W
     c) Went back to the dashboard and it was still at 2W.
     d) Tried setting it from the settings and then restarting the app and it was still at 2W, and the setting in the settings was also 2W.


This was in a non-premium account. Is this perhaps a premium only feature?

**Comment by LefterisJP** [comment]
Also @kelsos since I did not expect to find problems I had rebased on develop and pushed to fix the changelog conflicts. Keep that in mind if you work on it further.

**Comment by LefterisJP** [comment]
> This was in a non-premium account. Is this perhaps a premium only feature?

With a premium account the setting worked, and also the set time range peristed if I navigate away from the dashboard.

**Comment by kelsos** [comment]
Probably missed something for non-premium I will have a look

**Review by LefterisJP — APPROVED** [review]
LGTM with the changes done. Pretty cool.

Also rebased it on develop.

**Pull request merged**
