### PR TITLE
Introduces a tray icon for rotki

### LINKED ISSUE #2064: Possibility of "close to tray"
Hey guys,
i would like to be able to close Rotki into tray and see a changing icon, for example, a green arrow pointing up, a red arrow pointing down would be sufficient for now
thanks in advance

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2064

### CODE REVIEW

**Comment by kelsos** [comment]
After testing on all oses:

- [ ] Change icons to small ones for all OSes (icons appear huge on macos)
- [ ] Fix decimals in delta 
- [ ] Improve the tooltip text a bit

**Comment by LefterisJP** [comment]
Hey @kelsos ready to review? And this would be to just take the binary and see it works?

**Review by LefterisJP — COMMENTED** [review]
Hey @kelsos so this seems to work in i3. But there is some questions.

## What does this do?

2021-06-16-113336_190x200_scrot

What does the rotki part of the tray menu do? I clicked it but nothing happens.

## Amount change not visible in i3

In i3 hovering over the icon shows nothing. This is probably a limitation of the i3 tray menu. But exactly due to that would it be possible to add the amount also in the tray menu? As an informative non-menu entry?

## Minimize to tray from inside the app




Is it possible to add the minimize to tray also in the app itself? The only way me to minimize to tray is from the tray icon menu.

**Review by LefterisJP — COMMENTED** [review]
So this seems to work now as disussed.

But when I tried to close the generated binary in Linux I got a javascript exception in the console

```
2021-06-16T21:39:22.810Z: (info): Checking for update
2021-06-16T21:39:22.917Z: Restarting the backend
2021-06-16T21:39:22.923Z: Determining if we are packaged by seeing if /tmp/lefteris/.mount_rotki-XhMprY/resources/rotkehlchen_py_dist exists
2021-06-16T21:39:22.924Z: Starting packaged python subprocess: /tmp/lefteris/.mount_rotki-XhMprY/resources/rotkehlchen_py_dist/rotkehlchen-1.17.3.dev116+g9c8d80df-linux --api-port 4242 --loglevel debug --api-cors app://* --logfile /home/lefteris/.config/rotki/logs/rotkehlchen.log
2021-06-16T21:39:22.931Z: The Python sub-process started on port: 4242 (PID: 30025)
2021-06-16T21:39:23.694Z: (info): Update for version 1.17.2 is not available (latest version: 1.17.2, downgrade is disallowed).
(node:29933) UnhandledPromiseRejectionWarning: Error: AssertionError
    at S (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:433964)
    at Y.e [as getWindow] (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:447452)
    at Y.destroy (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:440219)
    at ae (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:451634)
    at App.<anonymous> (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:450446)
    at App.emit (events.js:315:20)
    at App.<anonymous> (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:447332)
    at App.emit (events.js:327:22)
(Use `rotki --trace-warnings ...` to show where the warning was created)
(node:29933) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29933) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C(node:29933) UnhandledPromiseRejectionWarning: Error: AssertionError
    at S (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:433964)
    at Y.e [as getWindow] (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:447452)
    at Y.destroy (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:440219)
    at ae (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:451634)
    at App.<anonymous> (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:450446)
    at App.emit (events.js:315:20)
(node:29933) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
2021-06-16T21:40:33.233Z: rotki API server is running at: 127.0.0.1:4242

2021-06-16T21:40:33.234Z: The Python sub-process exited with signal: null (Code: 0)
```

**Comment by kelsos** [comment]
> So this seems to work now as disussed.
> 
> But when I tried to close the generated binary in Linux I got a javascript exception in the console
> 
> ```
> 2021-06-16T21:39:22.810Z: (info): Checking for update
> 2021-06-16T21:39:22.917Z: Restarting the backend
> 2021-06-16T21:39:22.923Z: Determining if we are packaged by seeing if /tmp/lefteris/.mount_rotki-XhMprY/resources/rotkehlchen_py_dist exists
> 2021-06-16T21:39:22.924Z: Starting packaged python subprocess: /tmp/lefteris/.mount_rotki-XhMprY/resources/rotkehlchen_py_dist/rotkehlchen-1.17.3.dev116+g9c8d80df-linux --api-port 4242 --loglevel debug --api-cors app://* --logfile /home/lefteris/.config/rotki/logs/rotkehlchen.log
> 2021-06-16T21:39:22.931Z: The Python sub-process started on port: 4242 (PID: 30025)
> 2021-06-16T21:39:23.694Z: (info): Update for version 1.17.2 is not available (latest version: 1.17.2, downgrade is disallowed).
> (node:29933) UnhandledPromiseRejectionWarning: Error: AssertionError
>     at S (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:433964)
>     at Y.e [as getWindow] (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:447452)
>     at Y.destroy (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:440219)
>     at ae (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:451634)
>     at App.<anonymous> (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:450446)
>     at App.emit (events.js:315:20)
>     at App.<anonymous> (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:447332)
>     at App.emit (events.js:327:22)
> (Use `rotki --trace-warnings ...` to show where the warning was created)
> (node:29933) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:29933) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ^C(node:29933) UnhandledPromiseRejectionWarning: Error: AssertionError
>     at S (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:433964)
>     at Y.e [as getWindow] (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:447452)
>     at Y.destroy (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:440219)
>     at ae (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:451634)
>     at App.<anonymous> (/tmp/lefteris/.mount_rotki-XhMprY/resources/app.asar/background.js:2:450446)
>     at App.emit (events.js:315:20)
> (node:29933) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> 2021-06-16T21:40:33.233Z: rotki API server is running at: 127.0.0.1:4242
> 
> 2021-06-16T21:40:33.234Z: The Python sub-process exited with signal: null (Code: 0)
> ```

Ok let me have a look

**Review by LefterisJP — APPROVED** [review]
LGTM.

As discussed we need to test again once binaries are generated but the functionality is there.

**Pull request merged**
