### PR TITLE
feat: scroll table to top when changing page

### LINKED ISSUE #2848: Add scroll to the top button in Deposits & Withdrawals / trades etc.
When click on next page `>` (/history/deposits-withdrawals), expected page to be scrolled to the top, instead it scrolled to the bottom. After i scrolled to the bottom and seen latest dep/with transfers expecting next page take me to the top so i can scroll down and see transaction in their chronological order.

Screen Shot 2021-05-05 at 6 58 15 PM

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #2848 

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Scroll table to top when changing page

### CODE REVIEW

**Comment by lukicenturi** [comment]
There are still some bug, let me finish them

**Comment by kelsos** [comment]
> There are still some bug, let me finish them

Sure let me know when I can have a look

**Comment by lukicenturi** [comment]
> > There are still some bug, let me finish them
> 
> Sure let me know when I can have a look

Updated, the e2e also should not broken again.

**Comment by kelsos** [comment]
I only have a couple of minor comments.

First, do you think it would look better if there is a divider between the top paginator and the header?

Second, do we really need the bottom pagination at all? is there a way to remove it?

**Comment by lukicenturi** [comment]
> I only have a couple of minor comments.
> 
> First, do you think it would look better if there is a divider between the top paginator and the header?
> 
> Second, do we really need the bottom pagination at all? is there a way to remove it?

I think for the divider under the top paginator will be good.

For bottom pagination, I think it still needed, imagine if user choose to show 100 row, and scroll to the bottom of the table, we can't tell them to scroll manually to top.

**Comment by lukicenturi** [comment]
Divider added between top pagination and header

**Review by kelsos — APPROVED** [review]
lgtm

**Pull request merged**
