### PR TITLE
Small correction in usage_guide

### PR DESCRIPTION
**Pull request by defi-caratacus**
Some small corrections of things I noticed when going through the usage guide

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Hey @defi-caratacus thank you for your contribution! Can you please sign the CLA so we can accept your PR?

**Comment by defi-caratacus** [comment]
> Hey @defi-caratacus thank you for your contribution! Can you please sign the CLA so we can accept your PR?

What exactly is the CLA for? I thought this is an opensource project.

**Comment by LefterisJP** [comment]
> > Hey @defi-caratacus thank you for your contribution! Can you please sign the CLA so we can accept your PR?
> 
> What exactly is the CLA for? I thought this is an opensource project.

The CLA allows us to have full control of the license of the project. As we are a for-profit company that has salaries to pay we need to make sure we are not left at some point without the ability to change the license if we so need and lose our ability to survive as a business.

Without a CLA we would need to get a signed approval from every contributor ever. And even a single contributor could block any such attempt. Which is a risk we can not afford to have.

**Comment by defi-caratacus** [comment]
> > > Hey @defi-caratacus thank you for your contribution! Can you please sign the CLA so we can accept your PR?
> > 
> > 
> > What exactly is the CLA for? I thought this is an opensource project.
> 
> The CLA allows us to have full control of the license of the project. As we are a for-profit company that has salaries to pay we need to make sure we are not left at some point without the ability to change the license if we so need and lose our ability to survive as a business.
> 
> Without a CLA we would need to get a signed approval from every contributor ever. And even a single contributor could block any such attempt. Which is a risk we can not afford to have.

All right. That makes sense. You guys have to do all you can to make the project sustainable.

**Review by LefterisJP — APPROVED** [review]
Thanks @defi-caratacus! LGTM!

**Pull request merged**
