### PR TITLE
feat: some improvements on account balances

### PR DESCRIPTION
**Pull request by lukicenturi**
- [x] Evmlike to EVM
- [x] Clicking the chain icon will do the filter
- [x] Filter by chains now show correct usdValue on the group row
- [x] Show top assets instead of amount
- [x] Options to show aggregated assets under chains group, instead of address per chain info

For these two I guess I can do it in different PR
- [ ] Mass delete account
- [ ] Mass edit account

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Hey @lukicenturi looks really cool.

Some more things.

1. Clicking the chain icon will do the filtering. Here what I imagined was the opposite. Clicking the chain icon should basically gray out that chain, still keep it there and keep the rest only. This is so you can filter for multiple chains. Because with the current approach you can only filter one by one.

**Review by kelsos — APPROVED** [review]
I am gonna merge and we can take care of whatever need fixing/remaining on develop

**Comment by kelsos** [comment]
For the filter on a specific address we need to think a bit

**Comment by kelsos** [comment]
related to #8040

**Pull request merged**
