### PR TITLE
Isolates electron specific code and updates dependencies

### PR DESCRIPTION
**Pull request by kelsos**
- Updates vue cli from 3.x to 4.x
- Updates electron from 6.x to 8.x

### Isolates node from vue app
- https://www.electronjs.org/docs/api/sandbox-option
- https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content
- https://www.electronjs.org/docs/tutorial/security#3-enable-context-isolation-for-remote-content
- https://www.electronjs.org/docs/tutorial/security#15-disable-the-remote-module

### CODE REVIEW

**Comment by LefterisJP** [comment]
@kelsos You requested a review but this is still a draft and node.js linting fails

**Comment by kelsos** [comment]
@LefterisJP Ok I am gonna fix that but can you do a check to see if the packaged version works on windows/OSX?

**Comment by LefterisJP** [comment]
oh that's gonna take some time. But yes will do.

**Comment by LefterisJP** [comment]
So should I try it now? @kelsos

**Comment by kelsos** [comment]
No not yet I am still trying to figure how to properly package preload. At the. Moment the packaged version doesn't work.

**Comment by LefterisJP** [comment]
Let me know when and I will test in OSX and Windows packaged version @kelsos

**Comment by LefterisJP** [comment]
Tried to package in OSX High Sierra and got the following. Looks really bad ... `SIGILL` ... lol?
Will see if it repeats.

```
  • electron-builder  version=22.4.1 os=17.7.0
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.1.1 appOutDir=dist/mac
SIGILL: illegal instruction
PC=0x1065880 m=0 sigcode=1

goroutine 22 [running]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00019b580 sp=0xc00019b578 pc=0x1065880
net.IP.Equal(0xc000121370, 0x10, 0x10, 0x1fd5690, 0x10, 0x10, 0xa)
	/usr/local/Cellar/go/1.14/libexec/src/net/ip.go:410 fp=0xc00019b588 sp=0xc00019b580 pc=0x1154ca0
net.(*Resolver).internetAddrList(0x1fa9de0, 0x1a93520, 0xc000120008, 0x1877e3f, 0x3, 0xc000121310, 0xe, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.14/libexec/src/net/ipsock.go:288 +0x795 fp=0xc00019b6c0 sp=0xc00019b588 pc=0x115a795
net.(*Resolver).resolveAddrList(0x1fa9de0, 0x1a93520, 0xc000120008, 0x1878254, 0x4, 0x1877e3f, 0x3, 0xc000121310, 0xe, 0x0, ...)
	/usr/local/Cellar/go/1.14/libexec/src/net/dial.go:222 +0x49e fp=0xc00019b800 sp=0xc00019b6c0 pc=0x1142eee
net.(*Dialer).DialContext(0x1faa800, 0x1a93520, 0xc000120008, 0x1877e3f, 0x3, 0xc000121310, 0xe, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.14/libexec/src/net/dial.go:404 +0x22a fp=0xc00019b940 sp=0xc00019b800 pc=0x114404a
net/http.(*Transport).dial(0xc0002a6280, 0x1a93520, 0xc000120008, 0x1877e3f, 0x3, 0xc000121310, 0xe, 0x0, 0x15, 0x1fd6460, ...)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:1094 +0x165 fp=0xc00019b9b8 sp=0xc00019b940 pc=0x1398ce5
net/http.(*Transport).dialConn(0xc0002a6280, 0x1a93520, 0xc000120008, 0x0, 0xc000102360, 0x5, 0xc000121310, 0xe, 0x0, 0xc0001539e0, ...)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:1519 +0x19ee fp=0xc00019bed8 sp=0xc00019b9b8 pc=0x139cc3e
net/http.(*Transport).dialConnFor(0xc0002a6280, 0xc000271970)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:1365 +0xc6 fp=0xc00019bfd0 sp=0xc00019bed8 pc=0x139a606
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00019bfd8 sp=0xc00019bfd0 pc=0x1064011
created by net/http.(*Transport).queueForDial
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:1334 +0x3fe

goroutine 1 [select]:
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency(0x2, 0x3, 0xc00031f870, 0x8, 0x170a3af)
	/Volumes/data/Documents/app-builder/pkg/util/async.go:79 +0x4da
github.com/develar/app-builder/pkg/util.MapAsync(...)
	/Volumes/data/Documents/app-builder/pkg/util/async.go:12
github.com/develar/app-builder/pkg/electron.UnpackElectron(0xc000286b60, 0x1, 0x1, 0x7ffeefbfd92f, 0x32, 0x7ffeefbfd975, 0xc, 0x100ab01, 0xc000020000, 0x17b1ac0)
	/Volumes/data/Documents/app-builder/pkg/electron/electronUnpack.go:35 +0x10f
github.com/develar/app-builder/pkg/electron.ConfigureUnpackCommand.func1(0xc000280240, 0x100bf13, 0x17b1ac0)
	/Volumes/data/Documents/app-builder/pkg/electron/electronUnpack.go:29 +0xfe
github.com/alecthomas/kingpin.(*actionMixin).applyActions(0xc00019c6d8, 0xc000280240, 0x0, 0x0)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28 +0x6d
github.com/alecthomas/kingpin.(*Application).applyActions(0xc00016a690, 0xc000280240, 0x0, 0x0)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557 +0xdc
github.com/alecthomas/kingpin.(*Application).execute(0xc00016a690, 0xc000280240, 0xc000253150, 0x1, 0x1, 0x0, 0x0, 0x0, 0x14e3ace)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390 +0x8f
github.com/alecthomas/kingpin.(*Application).Parse(0xc00016a690, 0xc00013e010, 0x7, 0x7, 0xc00016a690, 0xc000102058, 0x0, 0x0)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222 +0x1fe
main.main()
	/Volumes/data/Documents/app-builder/main.go:90 +0x292

goroutine 20 [select]:
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency(0x1, 0x3, 0xc000066ed8, 0xc0002534c0, 0x0)
	/Volumes/data/Documents/app-builder/pkg/util/async.go:79 +0x4da
github.com/develar/app-builder/pkg/util.MapAsync(...)
	/Volumes/data/Documents/app-builder/pkg/util/async.go:12
github.com/develar/app-builder/pkg/electron.downloadElectron(0xc000286b60, 0x1, 0x1, 0xc000054f68, 0x100800a, 0xc0001022a0, 0x0, 0x0)
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:56 +0xc9
github.com/develar/app-builder/pkg/electron.UnpackElectron.func1.2(0x0, 0xc0001022a0)
	/Volumes/data/Documents/app-builder/pkg/electron/electronUnpack.go:42 +0x49
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2(0xc00029ebc0, 0xc0001022a0, 0xc00011ee40, 0xc0002a2a50)
	/Volumes/data/Documents/app-builder/pkg/util/async.go:68 +0x69
created by github.com/develar/app-builder/pkg/util.MapAsyncConcurrency
	/Volumes/data/Documents/app-builder/pkg/util/async.go:58 +0x3a3

goroutine 21 [select]:
net/http.(*Transport).getConn(0xc0002a6280, 0xc0002a2cc0, 0x0, 0xc000102360, 0x5, 0xc000121310, 0xe, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:1291 +0x57b
net/http.(*Transport).roundTrip(0xc0002a6280, 0xc000162300, 0xfc99c42, 0xa, 0x663e2ddb6915a291)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:552 +0x726
net/http.(*Transport).RoundTrip(0xc0002a6280, 0xc000162300, 0xc0002a6280, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000162300, 0x1a82820, 0xc0002a6280, 0x0, 0x0, 0x0, 0xc00011c858, 0x2, 0x1, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/client.go:252 +0x43e
net/http.(*Client).send(0xc0002a2b40, 0xc000162300, 0x0, 0x0, 0x0, 0xc00011c858, 0x0, 0x1, 0x2aaaaaaaa)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/client.go:176 +0xfa
net/http.(*Client).do(0xc0002a2b40, 0xc000162300, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/client.go:699 +0x44a
net/http.(*Client).Do(...)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/client.go:567
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1(0xc0002534d0, 0xc000162300, 0xc000199840, 0xc000102360, 0x5c, 0xc00011a680, 0x34, 0x0, 0xc000162300, 0x0)
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:152 +0x53
github.com/develar/app-builder/pkg/download.(*Downloader).follow(0xc0002534d0, 0xc000102360, 0x5c, 0x189c05c, 0x79, 0xc00011a680, 0x34, 0x103d85c, 0xc000106c00, 0xc000067b58)
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:186 +0x56e
github.com/develar/app-builder/pkg/download.(*Downloader).Download(0xc0002534d0, 0xc000102360, 0x5c, 0xc00011a680, 0x34, 0x0, 0x0, 0x0, 0xc000102360)
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:80 +0xdb
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload(0xc000054f50, 0xc000102360, 0x5c, 0xc000276140, 0x45, 0x18777d6, 0x1)
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192 +0x121
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download(0xc000054f50, 0x8, 0x187cdc3, 0xe, 0xc000054f00)
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177 +0x372
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1(0x0, 0xc000102300)
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73 +0x72
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2(0xc00029ec00, 0xc000102300, 0xc00011ef00, 0xc0002a2ab0)
	/Volumes/data/Documents/app-builder/pkg/util/async.go:68 +0x69
created by github.com/develar/app-builder/pkg/util.MapAsyncConcurrency
	/Volumes/data/Documents/app-builder/pkg/util/async.go:58 +0x3a3

rax    0x10
rbx    0xc0002a2e70
rcx    0x1fd5690
rdx    0x10
rdi    0xc00019b370
rsi    0x1
rbp    0xc00019b6b0
rsp    0xc00019b578
r8     0xc0001024e0
r9     0x0
r10    0x1
r11    0x28
r12    0xc00019b550
r13    0x5
r14    0x0
r15    0x0
rip    0x1065880
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
 ERROR  Error: /Users/johndoe/w/rotkehlchen/electron-app/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Error: /Users/johndoe/w/rotkehlchen/electron-app/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.childProcess.once.code (/Users/johndoe/w/rotkehlchen/electron-app/node_modules/builder-util/src/util.ts:239:14)
    at Object.onceWrapper (events.js:272:13)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rotki@1.2.1 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rotki@1.2.1 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johndoe/.npm/_logs/2020-03-18T16_14_12_377Z-debug.log
package.sh - ERROR: electron builder step failed
```

**Comment by LefterisJP** [comment]
Second time also failed with similar but a bit different trace:

```
> ejs@2.7.4 postinstall /Users/johndoe/w/rotkehlchen/electron-app/node_modules/webpack-bundle-analyzer/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> yorkie@2.0.0 install /Users/johndoe/w/rotkehlchen/electron-app/node_modules/yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> core-js@3.6.4 postinstall /Users/johndoe/w/rotkehlchen/electron-app/node_modules/@vue/babel-preset-app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> rotki@1.2.1 postinstall /Users/johndoe/w/rotkehlchen/electron-app
> electron-builder install-app-deps

  • electron-builder  version=22.4.1
SIGILL: illegal instruction
PC=0x1065880 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc000064e80 sp=0xc000064e78 pc=0x1065880
text/template.createValueFuncs(0xc0000966c0, 0xc0000966c0)
	/usr/local/Cellar/go/1.14/libexec/src/text/template/funcs.go:59 fp=0xc000064e88 sp=0xc000064e80 pc=0x11a10a0
text/template.init()
	/usr/local/Cellar/go/1.14/libexec/src/text/template/funcs.go:56 +0x8aa fp=0xc000064ec8 sp=0xc000064e88 pc=0x11aa67a
runtime.doInit(0x1f64620)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc000064ef8 sp=0xc000064ec8 pc=0x104330a
runtime.doInit(0x1f63980)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000064f28 sp=0xc000064ef8 pc=0x10432d7
runtime.doInit(0x1f65520)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000064f58 sp=0xc000064f28 pc=0x10432d7
runtime.doInit(0x1f66f80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000064f88 sp=0xc000064f58 pc=0x10432d7
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc000064fe0 sp=0xc000064f88 pc=0x103686e
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x1064011

rax    0xc0000966c0
rbx    0x50
rcx    0x18a5828
rdx    0x17aeae0
rdi    0xc0000d6058
rsi    0xc0000966c0
rbp    0xc000064eb8
rsp    0xc000064e78
r8     0xc0000d6000
r9     0x43
r10    0x0
r11    0x4
r12    0x1a
r13    0x6
r14    0x10
r15    0x1878ff7
rip    0x1065880
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rotki@1.2.1 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rotki@1.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johndoe/.npm/_logs/2020-03-18T16_46_19_992Z-debug.log
package.sh - ERROR: npm ci step failed
```

**Comment by LefterisJP** [comment]
As discussed it seems to be a problem with Golang in one of the electron-builder dependencies and probably only on my old CPU.  It worked for OSX when pinning electron-builder to 22.2.0.

**Comment by kelsos** [comment]
Just to document the issue you are facing seems to be this go lang regression on older CPUs without AVX instructions on OSX https://github.com/golang/go/issues/37459

It seems that the issue was introduced in this version of app-builder -> https://github.com/develar/app-builder/commit/ac3aa40ea04f05ebef39002888991405b003cae4, which was pulled in this commit of the electron-builder https://github.com/electron-userland/electron-builder/commit/f0cb15d2723ee0da263cf2d1a71fcba777133f3f

[electron-builder@v22.3.2](https://github.com/electron-userland/electron-builder/releases/tag/v22.3.2) should be safe. 

It should not be an issue either on CI or newer machines.

**Comment by LefterisJP** [comment]
Also works on Windows 7. Packaged the branch and ran the packaged binary without any issues.

**Comment by kelsos** [comment]
@LefterisJP that is awesome :) I will rebase and we can merge after the next release then as we discussed.

**Pull request merged**
