### PR TITLE
Group events on pnl report

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

image

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Hey rotki, in your screenshot it looks nice, but the continuity breaks completely when there is a cost basis involved.

Take a look here:



And since the cost basis is a huge line separator that can be dragged down and opened, it appears as a separator between the events too.

How do you think we can improve this?

**Comment by lukicenturi** [comment]
> Hey Luki in your screenshot it looks nice, but the continuity breaks completely when there is a cost basis involved.
> 
> Take a look here:
> 
> 
> 
> And since the cost basis is a huge line separator that can be dragged down and opened, it appears as a separator between the events too.
> 
> How do you think we can improve this?

Is it better? 
image

**Review by LefterisJP — COMMENTED** [review]
> Is it better?

Hey @lukicenturi visually yes! Thank you!

But I am getting the following in the console:

```
vue.runtime.esm.js:619 [Vue warn]: Invalid prop: type check failed for prop "offset". Expected Number with value 1, got String with value "1".

found in

---> <TableExpandContainer> at src/components/helper/table/TableExpandContainer.vue
       <CostBasicTable> at src/components/profitloss/CostBasisTable.vue
         <VSimpleTable>
           <VData>
             <VDataTable>
               <DataTable> at src/components/helper/DataTable.vue
                 <VSheet>
                   <VCard>
                     <Card> at src/components/helper/Card.vue
                       <ProfitLossEvents> at src/components/profitloss/ProfitLossEvents.vue
                         <ProfitLossReport> at src/views/reports/ProfitLossReport.vue
                           <VMain>
                             <VApp>
                               <App> at src/App.vue
                                 <Root>
```

**Comment by lukicenturi** [comment]
> > Is it better?
> 
> Hey @lukicenturi visually yes! Thank you!
> 
> But I am getting the following in the console:
> 
> ```
> vue.runtime.esm.js:619 [Vue warn]: Invalid prop: type check failed for prop "offset". Expected Number with value 1, got String with value "1".
> 
> found in
> 
> ---> <TableExpandContainer> at src/components/helper/table/TableExpandContainer.vue
>        <CostBasicTable> at src/components/profitloss/CostBasisTable.vue
>          <VSimpleTable>
>            <VData>
>              <VDataTable>
>                <DataTable> at src/components/helper/DataTable.vue
>                  <VSheet>
>                    <VCard>
>                      <Card> at src/components/helper/Card.vue
>                        <ProfitLossEvents> at src/components/profitloss/ProfitLossEvents.vue
>                          <ProfitLossReport> at src/views/reports/ProfitLossReport.vue
>                            <VMain>
>                              <VApp>
>                                <App> at src/App.vue
>                                  <Root>
> ```

updated

**Review by kelsos — APPROVED** [review]
@lukicenturi lgtm thank you :)

**Pull request merged**
