### PR TITLE
Update exchanges icon

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Update exchanges icon to newest version (based on their current website logo). Also add white wrapper to them when viewed in dark mode.
image
- [ ] Compress the image size.
- [ ] Add white placeholder to asset image and defi icons, if opened in dark mode (for better visibility)
image
image
- [ ] Fix several error from PR https://github.com/rotki/rotki/pull/4001

### CODE REVIEW

**Comment by yabirgb** [comment]
Dammmm so coool!

**Review by LefterisJP — COMMENTED** [review]
cool to see the attention to detail for stuff like that. Thank you Luki!

**Comment by kelsos** [comment]
@lukicenturi I see that some of the SVG icons have been replaced with pngs was there a problem with the SVGs?

**Review by kelsos — APPROVED** [review]
Looks really good thank you. 

Btw when looking for icons please prefer SVGs to any raster type (png, jpg) unless no svg cannot be found at all.

If there is an SVG that contains more information like text, we can extract the actual logo using Inkscape, so let me know. It is trivial to do it, I have done it many times, I can also make a small guide for you if needed.

Lastly, I found a minor annoyance. The wrapper seems to scale weirdly for me on the blockchain balances in summary, so we may have to force the height on the wrapper.

image

**Comment by kelsos** [comment]
Also, another minor comment, do you think we could round the corners a bit for the white wrapper on a dark background?

**Comment by lukicenturi** [comment]
> Looks really good thank you.
> 
> Btw when looking for icons please prefer SVGs to any raster type (png, jpg) unless no svg cannot be found at all.
> 
> If there is an SVG that contains more information like text, we can extract the actual logo using Inkscape, so let me know. It is trivial to do it, I have done it many times, I can also make a small guide for you if needed.
> 
> Lastly, I found a minor annoyance. The wrapper seems to scale weirdly for me on the blockchain balances in summary, so we may have to force the height on the wrapper.
> 
> image

Alright I will see if there is any way the SVG can be used, since I found the problem when I tried to invert it in dark mode.

**Comment by lukicenturi** [comment]
> Also, another minor comment, do you think we could round the corners a bit for the white wrapper on a dark background?

Yeah it will be nice, I will add it

**Comment by lukicenturi** [comment]
@kelsos All logos changed in this PR are SVG now.

**Pull request merged**
