### PR TITLE
Makes more locations with an asset icon navigate to the asset page

### LINKED ISSUE #3304: Clicking on assets (base/quote) in a trade should take you to the asset page
## Abstract

In deposits & withdrawals clicking an associated token under `Asset` will take you to that tokens page (I think this is a nice featured & desired). When clicking the tokens in Trades, for example, (either `Base` or `Quote`) nothing happens. We should make this behavior consistent across the app. Similarly, in "trades" perhaps we should be able to click the "Location" and be taken to the relevant section of the app (if there is one), e.g. clicking "Coinbase" in trades would take us to the Coinbase exchange page (usually accessed via the Dashboard).

### PR DESCRIPTION
**Pull request by kelsos**
Closes #3304 

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### Notes
- Requires also changes in the components
- Airdrops is more complicated than expected (skipping for now)

### Places to check
- History -> Trades
- DeFi -> Dex Trades
- History -> Deposits -> Protocols Events

Let me know if I missed something

### CODE REVIEW

**Comment by yabirgb** [comment]
For me defi -> dex trades is the only place that doesn't work properly. I click on the icons but it doesn't redirect me to the asset place.

Also would be cool to have an icon here to edit the asset. Don't know if its possible
image

**Comment by kelsos** [comment]
> For me defi -> dex trades is the only place that doesn't work properly. I click on the icons but it doesn't redirect me to the asset place.
> 
> Also would be cool to have an icon here to edit the asset. Don't know if its possible
> image

If the navigation to the asset page works then there is no need to add edit buttons everywhere right? 
Can you pinpoint the exact place in the Dex Trades where it doesn't work? 

If you go in with the vue dev tools you should also find the component.

**Comment by kelsos** [comment]
At least from checking a couple of them, I don't see any issue, they navigate properly so more information would be needed.

**Comment by yabirgb** [comment]
> At least from checking a couple of them, I don't see any issue, they navigate properly so more information would be needed.

Indeed. If rechecked and I didn't have the proper premium components

**Review by yabirgb — APPROVED** [review]
The rest of the locations seem to work and my request was not in the scope of the issue and might need a new issue. I see the PR okey to merge :)

**Pull request merged**
