### PR TITLE
Fixes symbol in compound loans

### PR DESCRIPTION
**Pull request by kelsos**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
The other issue is on the components unfortunately 😢 @yabirgb

**Review by yabirgb — APPROVED** [review]
It works fine. Thanks sir

**Comment by yabirgb** [comment]
@kelsos Yes I could imagine. We could leave it as it is not something major and we will probably modify all this sections

**Comment by kelsos** [comment]
> @kelsos Yes I could imagine. We could leave it as it is not something major and we will probably modify all this sections

I am creating a PR with the fix in components and we can see about deployment

**Pull request merged**
