### PR TITLE
Introduces support for aave borrowing

### LINKED ISSUE #1629: Don't start with side menu-minimized
## Problem Definition

Don't start with side-menu minimized in most screen sizes. As long as the screen size can afford it start with the menu shown.

## Task

Just do it

### PR DESCRIPTION
**Pull request by kelsos**
Is there an issue for that @LefterisJP 
This also needs the components PR and dev proxy.

Closes #1629

### CODE REVIEW

**Comment by LefterisJP** [comment]
> Is there an issue for that

@kelsos no actually there is not. IT was bundled up with the subgraph integration work

**Review by LefterisJP — COMMENTED** [review]
### Deposits total earned per asset

I don't see the total earned per asset in the deposits section anywhere



### From/to assets for events

In Compound we get all the required data from the subgraph about which asset we move from/to in each event and we show it.



Here you are not yet doing it for Aave


But we don't need any extra data to do it from the subgraph.

In a deposit you go from asset to aAsset. So for example `DAI` -> to `aDAI`.
In a withdrawal it's the opposite. You withdraw `DAI`, so you go from `aDAI` to `DAI`.

The amount/values are always 1 to 1.

### Borrow events format

The borrow events don't look good.



The rate of a borrow looks forced in there. I think these should be two different fields. So APR and rate type in %.




### Liquidation is missing something



So what happens here is the guy is losing his 0.42 WBTC collateral. Bye bye! But has a part of his ETH debt (almost half repaid). So what he loses is the difference between the WBTC value and the ETH value. So what is missing here is the ETH value as earned.

Do you think I should be adding this in the backend too? I think I should now that I think about it

### Going to liabilies first

As discussed in discord going to liabilities is missing a query to AAve history it seems

**Comment by kelsos** [comment]
> 
> 
> The rate of a borrow looks forced in there. I think these should be two different fields. So APR and rate type in %.

> 

Is the problem that the fee and rate are shown in the same column? or something else.

**Comment by LefterisJP** [comment]
> Is the problem that the fee and rate are shown in the same column? or something else.

That is one problem yes. The other is the screenshot where the `%` goes to the next line. I think those problems are related.

**Review by LefterisJP — COMMENTED** [review]
### Total liquidation earned




Some changes here. Can you only make the tab appear if it's required? This will only have data for loans that got liquidated. This is a minority of the loans. So I would only show it if there is something to show

And can you rename the title in the frontend? "Total earned by debt repayment from liquidation"

And the other one -> "Total lost by debt interest and liquidation"
## Borrowing events

They look better now. Still I think we need a UX/UI guy to go through everything and make it pretty.

Thing looking a bit off but is mostly nitpicky is distance between amount and % as seen below



### Repay events

It seems that depending on the logo of the token "Fee" appears in different positions







It would be nice if this was made consistent.

### Total earned

This appears when filtering aave now, so great. Only thing is we should change the title:

"Aave: Total earned from deposit interest"

**Comment by kelsos** [comment]
Interesting. I just realized that the space between the currency and symbol was accidentally broken. Just fixed that so both the currency and percentage have some space in between as they were supposed to.

**Review by LefterisJP — APPROVED** [review]
LGTM. Thanks a lot! (Please also merge the premium components PR if it's all good there too).

The test failure seems to bit a 5XX bittrex error. Can ignore.

**Pull request merged**
