### PR TITLE
Introduces frontend support for new status endpoint

### PR DESCRIPTION
**Pull request by kelsos**
Frontend part of #2141

### CODE REVIEW

**Comment by LefterisJP** [comment]
When testing this I saw this:

```
processing_state: "Processing all retrieved historical events"
total_progress: "-136.1043507269561426156328462"
```

followed by 

```
processing_state: "Processing all retrieved historical events"
total_progress: "73.95509172072068600482123502"
```

followed by

```
processing_state: "Processing all retrieved historical events"
total_progress: "93.00386942919726271877358527"
```

So something must be wrong in the backend's new logic there. Let me look.

**Review by LefterisJP — APPROVED** [review]
Test it and it works and LGTM.

Added a few more commits for some backend fixes and changelog

**Comment by kelsos** [comment]
```
rotkehlchen/tests/api/test_bitcoin.py:317: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rotkehlchen/tests/utils/api.py:78: in assert_proper_response_with_result
    assert_proper_response(response, status_code)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

response = <Response [502]>, status_code = <HTTPStatus.OK: 200>

    def assert_proper_response(
            response: Optional[requests.Response],
            status_code=HTTPStatus.OK,
    ) -> None:
        assert (
            response is not None and
>           response.status_code == status_code and
            response.headers["Content-Type"] == "application/json"
        )
E       AssertionError
```
Seems like a gateway error for the single failure of the backend tests so I am assuming we can merge it right?

**Comment by LefterisJP** [comment]
yeah blockstream api's had timed out

```
2021-01-22T00:51:46.0551235Z [22/01/2021 00:28:37 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qap7594pcdfsz5a7zcuj4qk5utejz3cktr497e2. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 3 tries left
2021-01-22T00:51:46.0552428Z [22/01/2021 00:28:37 UTC] DEBUG rotkehlchen.utils.misc: Querying https://blockstream.info/api/address/bc1qwqfcawzzdnvdkstyamus6j5n0z00z7uknn9pl4
2021-01-22T00:51:46.0553316Z [22/01/2021 00:28:37 UTC] DEBUG rotkehlchen.utils.misc: Querying https://blockstream.info/api/address/bc1qty6q6ehcjym4t4hw6w8rtkxap5q0luvl7hm7dn
2021-01-22T00:51:46.0554180Z [22/01/2021 00:28:38 UTC] DEBUG rotkehlchen.utils.misc: Querying https://blockstream.info/api/address/bc1q4uhedt5spvt0g7rmudkw0xlya4hyfrkkthvglx
2021-01-22T00:51:46.0555694Z [22/01/2021 00:28:43 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1q4uhedt5spvt0g7rmudkw0xlya4hyfrkkthvglx. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 4 tries left
2021-01-22T00:51:46.0556989Z [22/01/2021 00:28:46 UTC] DEBUG rotkehlchen.tasks.manager: At task scheduling. Current greenlets: 0 Max greenlets: -1. Will not schedule.
2021-01-22T00:51:46.0558423Z [22/01/2021 00:28:48 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1q4uhedt5spvt0g7rmudkw0xlya4hyfrkkthvglx. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 3 tries left
2021-01-22T00:51:46.0560166Z [22/01/2021 00:28:53 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1q4uhedt5spvt0g7rmudkw0xlya4hyfrkkthvglx. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 2 tries left
2021-01-22T00:51:46.0561265Z [22/01/2021 00:28:53 UTC] DEBUG rotkehlchen.utils.misc: Querying https://blockstream.info/api/address/bc1qrsuzyk45dn3k3q4jpkxary6nkc2x58xcem8rdz
2021-01-22T00:51:46.0562307Z [22/01/2021 00:28:56 UTC] DEBUG rotkehlchen.tasks.manager: At task scheduling. Current greenlets: 0 Max greenlets: -1. Will not schedule.
2021-01-22T00:51:46.0563819Z [22/01/2021 00:28:58 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qrsuzyk45dn3k3q4jpkxary6nkc2x58xcem8rdz. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 4 tries left
2021-01-22T00:51:46.0565556Z [22/01/2021 00:29:03 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qrsuzyk45dn3k3q4jpkxary6nkc2x58xcem8rdz. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 3 tries left
2021-01-22T00:51:46.0566822Z [22/01/2021 00:29:06 UTC] DEBUG rotkehlchen.tasks.manager: At task scheduling. Current greenlets: 0 Max greenlets: -1. Will not schedule.
2021-01-22T00:51:46.0568241Z [22/01/2021 00:29:08 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qrsuzyk45dn3k3q4jpkxary6nkc2x58xcem8rdz. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 2 tries left
2021-01-22T00:51:46.0569358Z [22/01/2021 00:29:08 UTC] DEBUG rotkehlchen.utils.misc: Querying https://blockstream.info/api/address/bc1qws4m6rj9hn9cf7knchdcuqfms6qq39r6432h3p
2021-01-22T00:51:46.0570841Z [22/01/2021 00:29:13 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qws4m6rj9hn9cf7knchdcuqfms6qq39r6432h3p. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 4 tries left
2021-01-22T00:51:46.0572087Z [22/01/2021 00:29:16 UTC] DEBUG rotkehlchen.tasks.manager: At task scheduling. Current greenlets: 0 Max greenlets: -1. Will not schedule.
2021-01-22T00:51:46.0573499Z [22/01/2021 00:29:18 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qws4m6rj9hn9cf7knchdcuqfms6qq39r6432h3p. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 3 tries left
2021-01-22T00:51:46.0575278Z [22/01/2021 00:29:23 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qws4m6rj9hn9cf7knchdcuqfms6qq39r6432h3p. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 2 tries left
2021-01-22T00:51:46.0582327Z [22/01/2021 00:29:26 UTC] DEBUG rotkehlchen.tasks.manager: At task scheduling. Current greenlets: 0 Max greenlets: -1. Will not schedule.
2021-01-22T00:51:46.0583764Z [22/01/2021 00:29:28 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qws4m6rj9hn9cf7knchdcuqfms6qq39r6432h3p. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 1 tries left
2021-01-22T00:51:46.0585483Z [22/01/2021 00:29:33 UTC] DEBUG rotkehlchen.utils.misc: In retry_call for -https://blockstream.info/api/address/bc1qws4m6rj9hn9cf7knchdcuqfms6qq39r6432h3p. Got error HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5) Trying again ... with 0 tries left
2021-01-22T00:51:46.0587366Z [22/01/2021 00:29:33 UTC] DEBUG rotkehlchen.api.rest: Request successful response={"result": null, "message": " query for https://blockstream.info/api/address/bc1qws4m6rj9hn9cf7knchdcuqfms6qq39r6432h3p failed after 5 tries. Reason: HTTPSConnectionPool(host='blockstream.info', port=443): Read timed out. (read timeout=5)"}, status_code=502
2021-01-22T00:51:46.0588715Z [22/01/2021 00:29:33 UTC] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "PUT /api/1/blockchains/BTC/xpub HTTP/1.1" 502 386 96.277215
```

**Pull request merged**
