### PR TITLE
Fix : fix eth transactions that deploy a contract break transaction view

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Fix eth transactions that deploy a contract break transaction view

### CODE REVIEW

**Comment by lukicenturi** [comment]
From issue #3916. The logging part will be done separately, need to discuss with @kelsos the best way to handle it.

**Review by LefterisJP — COMMENTED** [review]
Hey @lukicenturi this seems to work. But you need to point it to fix the issue and to also add a changelog entry. Something like:

"Users with ethereum transactions that deploy contracts will now be able to load the transactions view properly"

Another question. We don't touch the to_address in the search filters, right?

**Comment by lukicenturi** [comment]
> Hey @lukicenturi this seems to work. But you need to point it to fix the issue and to also add a changelog entry. Something like:
> 
> "Users with ethereum transactions that deploy contracts will now be able to load the transactions view properly"
> 
> Another question. We don't touch the to_address in the search filters, right?

Changelog added. For the filter, yes, we don't touch the to_address.

**Comment by LefterisJP** [comment]
> > Hey @lukicenturi this seems to work. But you need to point it to fix the issue and to also add a changelog entry. Something like:
> > "Users with ethereum transactions that deploy contracts will now be able to load the transactions view properly"
> > Another question. We don't touch the to_address in the search filters, right?
> 
> Changelog added. For the filter, yes, we don't touch the to_address.

I don't see the changelog entry.

**Comment by lukicenturi** [comment]
> > > Hey @lukicenturi this seems to work. But you need to point it to fix the issue and to also add a changelog entry. Something like:
> > > "Users with ethereum transactions that deploy contracts will now be able to load the transactions view properly"
> > > Another question. We don't touch the to_address in the search filters, right?
> > 
> > 
> > Changelog added. For the filter, yes, we don't touch the to_address.
> 
> I don't see the changelog entry.

my bad, not pushed

**Review by LefterisJP — APPROVED** [review]
lgtm

**Pull request merged**
