### PR TITLE
Use correct date format while importing information from nexo

### LINKED ISSUE #3057: Some NEXO entries in CSV have different datetime format
## Problem Definition

A user provided a screenshot

image

where the date seems to include also seconds in the format. This is something different from what we had so I suspect that depending on region or something the format might be different

Operating system: 
Rotki version: 1.17.2

### PR DESCRIPTION
**Pull request by yabirgb**
Closes #3057

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Hey @yabirgb please do this as a bugfixes PR

**Comment by yabirgb** [comment]
@LefterisJP Sorry. I used the bugfixes branch but when creating the PR it choosed develop and didn't notice. Should be correct now

**Comment by yabirgb** [comment]
Failing test seems to be something that changed in cryptocompare API, a pair that doesn't have information. Need to investigate why and fix it or change but in a different PR

**Review by LefterisJP — APPROVED** [review]
Thanks @yabirgb! Looks good to me.

**Pull request merged**
