### PR TITLE
Fixes some bugged AmountDisplay values

### PR DESCRIPTION
**Pull request by isidorosp**
* Fixes 2 instances of amounts presented via AmountDisplay that were not being converted to main currency

[ui tests]

### CODE REVIEW

**Comment by LefterisJP** [comment]
Thank you @isidorosp !

Is this all the amounts that are in the wrong format?

If yes can you please specify the locations also in the changelog?
If not, can you check and fix the other locations too?

**Comment by isidorosp** [comment]
> Thank you @isidorosp !
> 
> Is this all the amounts that are in the wrong format?
> 
> If yes can you please specify the locations also in the changelog?
> If not, can you check and fix the other locations too?

It's all the ones I could find, yes. Sure, I will specify.

**Comment by LefterisJP** [comment]
@isidorosp this needs a rebase. Also is it okay for merging? It's still a draft.

**Comment by isidorosp** [comment]
@LefterisJP I rebased this this morning but it looks like it needs yet another one as you merged something in the meantime. Feel free to just resolve conflicts & merge via the github GUI whenever you want to slot this in.

**Pull request merged**
