### PR TITLE
Fixes notification popup close being off-screen

### LINKED ISSUE #2117: Can not dismiss error notification
## Problem Definition

This is a minor frontend issue seen in v1.12.1. At some point when user gets an error there is a top notification which does not go away for quite some time and there is no "X" to click to dimiss it. So the only thing to do is wait.

I am not sure if the problem here is that the "X" is there but not visible, or that there is no "X" at all to be found.

Looks like this:

## Task

Figure out why it happens and make the notification dismissale.

### PR DESCRIPTION
**Pull request by kelsos**
Also introduces a dismiss all action that dismisses all of the pending notifications
Closes #2117

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
The individual notification removal does not seem to work for me.


https://user-images.githubusercontent.com/1658405/105335200-0d5a0900-5bd8-11eb-9278-370b8c21471c.mp4

Should I do npm ci? I don't see any new packages.

**Comment by kelsos** [comment]
damn wrong rebase...

**Comment by kelsos** [comment]
@LefterisJP the issue should now be fixed and everything should be ready

**Comment by LefterisJP** [comment]
There is a funny status stuck on yellow

**Review by LefterisJP — APPROVED** [review]
tested again and it works. Thanks.

**Comment by kelsos** [comment]
> There is a funny status stuck on yellow (I force merged) @kelsos
> 
> 

Yes, this funny status will be stuck on yellow on the bugfixes branch until we have a new release and sync bugfixes. The CI configuration that contains that is only in develop.

**Comment by LefterisJP** [comment]
> > There is a funny status stuck on yellow (I force merged) @kelsos
> > 
> 
> Yes, this funny status will be stuck on yellow on the bugfixes branch until we have a new release and sync bugfixes. The CI configuration that contains that is only in develop.

no need to wait. Can't you cherry pick the CI config into bugfixes too? This is what we did in the past in such situations.

**Pull request merged**
