### PR TITLE
Add grouping of multichain frontend

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
How does asset breakdown work with the grouped assets? 
I clicked added a DAI on optimism as a manual balance, then clicked on the asset to go to the asset details page and I can not see the manual balance, only the on-chain values

**Comment by lukicenturi** [comment]
> How does asset breakdown work with the grouped assets? 
> 
> I clicked added a DAI on optimism as a manual balance, then clicked on the asset to go to the asset details page and I can not see the manual balance, only the on-chain values

Hmm yeah I need to update this asset details page too. If you click that parent icon, it will show the asset detail of that asset on first chain in the array.

**Comment by kelsos** [comment]
I dropped the commit from the backend and rebased on top of develop.
Assuming that the tests pass, we can do the remaining work to a new issue.

**Review by kelsos — APPROVED** [review]
merging so that the e2e tests work

**Pull request merged**
