### PR TITLE
Setting for cost basis method on frontend

### LINKED ISSUE #44: Add accounting option for calculating profits in LIFO order
At the moment the profit calculation is made in a hard-coded FIFO order as that's how it's required by German taxes. Make this customizable and add an accounting option to switch between different modes.

- [ ] In `accounting.py` add an option for LIFO profit calculation
- [ ] Make `accounting.py` able to switch between those options
- [ ] In the frontend, in the accounting settings page offer a dropdown menu to customize this choice.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #44
image

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by kelsos — APPROVED** [review]
lgtm @lukicenturi thanks

**Review by LefterisJP — APPROVED** [review]
LGTM!

**Comment by msagansk** [comment]
With this structure in place, is it possible to get ACB method in as well from [#4024](https://github.com/rotki/rotki/issues/4024)?

**Comment by LefterisJP** [comment]
> With this structure in place, is it possible to get ACB method in as well from [#4024](https://github.com/rotki/rotki/issues/4024)?

This is a different issue. Eventually yes, that's the plan! But not yet.

**Pull request merged**
