### PR TITLE
Update electron builder

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.\

image

### CODE REVIEW

**Comment by lukicenturi** [comment]
@kelsos I had to delete the package-lock.json and do `npm install`, because the overrides command won't work unless the package-lock.json is deleted.

**Comment by kelsos** [comment]
> @kelsos I had to delete the package-lock.json and do `npm install`, because the `overrides` command won't work unless the package-lock.json is deleted.

Yes, I was aware already that this was the only way to fix it. This is what I also tried yesterday, but without the overrides, that is why it did not work

**Comment by kelsos** [comment]
is the check failure due to downgrading vue-cli-eslint?

**Review by kelsos — APPROVED** [review]
@lukicenturi thank you lgtm :)

**Pull request merged**
