### PR TITLE
refactor: move tag management to it's own page

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by kelsos — COMMENTED** [review]
so let's move the icon to the library and then merged this, looks good :)

**Review by kelsos — APPROVED** [review]
lgtm

**Comment by aspiers** [comment]
@kelsos Is this related to https://github.com/rotki/rotki/discussions/8934 ?

**Comment by kelsos** [comment]
> @lukicenturi @kelsos Is this related to #8934 ?

Yes, exactly we did some changes and moved the tag table to the left-side navigation menu

**Comment by aspiers** [comment]
Awesome!

**Pull request merged**
