### PR TITLE
Fixes a few bugs that would prevent a user to connect to the dockerized backend from the app

### LINKED ISSUE #3118: Allow access the Rotki Docker Backend with Rotki Windows Client
## Abstract

Allow access from the Rotki Windows Client through the docker backend

## Motivation

It would be a great feature to use the windows client instead of the web browser.
Maybe the performance would also be better instead of the web.

### PR DESCRIPTION
**Pull request by kelsos**
Closes #3118 

To build the docker image for testing

```
docker buildx build --tag rotki:test .         
docker run -d --name rotki-test \ 
    -p 8084:80 \
    -v $HOME/.rotki/data:/data \
    -v $HOME/.rotki/logs:/logs \
    rotki:test
```

A build of the app from this branch is also needed, OS doesn't matter.

Verify that the frontend is accessible through `http://localhost:8084` and then start the app go to the backend settings and set the endpoint to `http://localhost:8084`

### CODE REVIEW

**Comment by kelsos** [comment]
There is also an issue with the rest of the custom backend I am looking into

**Comment by yabirgb** [comment]
I got this error when trying a `npm run electron:serve` in this branch

```
ERROR: Running in development mode and not inside a python virtual environment
2021-06-24T17:36:34.353Z: Terminating the backend
(node:42280) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at createWindow (webpack:///./src/background.ts?:117:17)
    at async App.onReady (webpack:///./src/background.ts?:55:5)
(node:42280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:42280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LefterisJP** [comment]
Tell me when this is ready for review. But to be honest I won't be able to test it.

**Comment by kelsos** [comment]
@LefterisJP it is ready for review

**Review by LefterisJP — APPROVED** [review]
I trust you in this.

**Pull request merged**
