### PR TITLE
feat: add nft price functionality in price menu

### LINKED ISSUE #5283: Migrate NFT prices to the price manager
## Abstract

Managing NFT prices is now done via the Accounts -> NFT balances, which can be confusing for users.

## Motivation

Move the NFT price management under the price manager.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #5283

Need backend work `also return NFT custom prices on endpoint /assets/prices/latest/all`

### CODE REVIEW

**Comment by kelsos** [comment]
@lukicenturi is this ready for review?

**Comment by lukicenturi** [comment]
> @lukicenturi is this ready for review?

Yeah it is, just ignore the e2e, it's gonna be resolved in other PR

**Review by kelsos — APPROVED** [review]
lgtm

**Comment by kelsos** [comment]
CI failure is known flakiness

**Pull request merged**
