### PR TITLE
Upgrade to python 3.10

### PR DESCRIPTION
**Pull request by LefterisJP**
135937807-fd3e0fd2-a31a-47a4-90c6-b0bb1d0704d4

### CODE REVIEW

**Comment by kelsos** [comment]
https://github.com/rotki/rotki/blob/9c573d957753cf2bc118cfd7dc16e35a240ce960/.github/.env.ci#L1

3.10.11 here

**Comment by LefterisJP** [comment]
> https://github.com/rotki/rotki/blob/9c573d957753cf2bc118cfd7dc16e35a240ce960/.github/.env.ci#L1
> 
> 3.10.11 here (you need to be explicit otherwise the download from python.org for macOS wont' work for building)

Thanks will do. Is there anything more for building? 

Also lots of more stuff seem to need my caressing touch :smile:

**Comment by LefterisJP** [comment]
API tests seem to be timing out

**Comment by LefterisJP** [comment]
As discussed python 3.10 should go in. So since all is green I am merging.

**Pull request merged**
