### PR TITLE
fix: add date and time to eth2 deposit table

### LINKED ISSUE #3884: Add date and time to eth2 deposits table
## Abstract

At the moment in the eth2 staking details page there is no date column for the deposits.

Would be cool to have it and also be able to sort by date.

## Task

Do it

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #3884

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Add date and time to eth2 deposit table

### CODE REVIEW

**Comment by yabirgb** [comment]
The timestamp should be appearing in the events table at the eth2 staking section?

**Comment by kelsos** [comment]
@yabirgb will the timestamp be added as part of the 1.24? meaning that is it not in 1.23? or is something that the backend returned but we missed?

**Comment by yabirgb** [comment]
> @yabirgb will the timestamp be added as part of the 1.24? meaning that is it not in 1.23? or is something that the backend returned but we missed?
Is something that we already returned, so seems that the frontend was missing it
https://github.com/rotki/rotki/blob/9536f89554f83e4209510f3a80077d62d3dff0c5/rotkehlchen/chain/ethereum/typing.py#L295

but I don't know where it gets rendered if it is ever rendered

**Review by kelsos — APPROVED** [review]
lgtm

**Comment by kelsos** [comment]
> > @yabirgb will the timestamp be added as part of the 1.24? meaning that is it not in 1.23? or is something that the backend returned but we missed?
> > Is something that we already returned, so seems that the frontend was missing it
> > https://github.com/rotki/rotki/blob/9536f89554f83e4209510f3a80077d62d3dff0c5/rotkehlchen/chain/ethereum/typing.py#L295
> 
> but I don't know where it gets rendered if it is ever rendered

11 months should be safe for backward compatibility

**Pull request merged**
