### PR TITLE
fix typo in data import components

### LINKED ISSUE #4710: Uphold File Import Not possible
## Problem Definition

Importing Uphold Trade History returns: 
{"source": ["Failed to deserialize DataImportSource value uphold"]}

Either using standard date formats or custom: %a %b %d %Y %H:%M:%S %z

## Logs

[18/08/2022 19:07:05 Mitteleuropäische Sommerzeit] DEBUG rotkehlchen.api.server Greenlet-14: start rotki api PUT /api/1/import view_args={}, query_string=b''
[18/08/2022 19:07:05 Mitteleuropäische Sommerzeit] DEBUG rotkehlchen.api.server Greenlet-14: end rotki api PUT /api/1/import view_args={}, query_string=b'', status_code=400, result={'message': '{"source": ["Failed to deserialize DataImportSource value uphold"]}', 'result': None}

### System Description

Operating system: win10
Rotki version: 1.25.2

### PR DESCRIPTION
**Pull request by prettyirrelevant**
Closes #4710 

This fixes similar typo across other importers.

### CODE REVIEW

**Review by lukicenturi — APPROVED** [review]
Good from the code side

**Comment by LefterisJP** [comment]
@prettyirrelevant this should be against bugfixes. It's a bug

**Review by LefterisJP — CHANGES_REQUESTED** [review]
1. This should be against bugfixes
2. This should have a changelog entry explaining what was fixed

**Review by yabirgb — COMMENTED** [review]
In this branch I get 

```
Invalid prop: custom validator check failed for prop "source".
```

Is there something else that needs to be updated @lukicenturi ?

**Review by yabirgb — APPROVED** [review]
I've tested this and luki has looked at the code. Branch is correct and has changelog entry. LGTM

**Review by LefterisJP — APPROVED** [review]

**Comment by LefterisJP** [comment]
Flaky e2e test known to be flaky in bugfixes.

> if yes this test has been failing on bugfixes because of the addition being too slow

**Pull request merged**
