### PR TITLE
Re-introduces e2e testing for general settings to the frontend

### PR DESCRIPTION
**Pull request by kelsos**
I am not sure if we have an issue for that but this is to track the work done on re-introducing the e2e tests for the vue rewrite.

This PR is part of #638

### CODE REVIEW

**Comment by LefterisJP** [comment]
@kelsos I don't think we have an issue. I suggest you make one.

And then work on it in small incremental PRs :smile:

**Comment by kelsos** [comment]
@LefterisJP sorry that this PR got big but it should have all the infrastructure need to proceed with the rest of them in smaller PRs

At the moment only the `application launch` and `settings general` tests should run successfully.
In order to run only these suites, you can use the following commands in the `electron-app` directory:

```bash
  npm run test:e2e -- -i tests/e2e/specs/create_account.spec.ts 
```

and

```bash
  npm run test:e2e -- -i tests/e2e/specs/settings_general.spec.ts  
```

**Comment by LefterisJP** [comment]
Running `npm run test:e2e -- -i tests/e2e/specs/create_account.spec.ts`

if got stuck at logout

2020-01-18-182621_637x805_scrot


```
> rotki@1.0.7 test:e2e /home/lefteris/w/vue_rotki/electron-app
> jest --config tests/e2e/jest.config.js --runInBand "-i" "tests/e2e/specs/create_account.spec.ts"

  console.log tests/e2e/specs/utils/common.ts:203
    Took screenshot: first usage create account

 FAIL  tests/e2e/specs/create_account.spec.ts (99.631s)
  first usage
    ✕ create account (94696ms)

  ● first usage › create account

    element (".confirm-dialog") still not visible after 40000ms

      at new WaitUntilTimeoutError (../../node_modules/webdriverio/build/lib/utils/ErrorHandler.js:149:12)
      at ../../node_modules/webdriverio/build/lib/commands/waitUntil.js:29:19

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        100.327s
Ran all test suites matching /tests\/e2e\/specs\/create_account.spec.ts/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rotki@1.0.7 test:e2e: `jest --config tests/e2e/jest.config.js --runInBand "-i" "tests/e2e/specs/create_account.spec.ts"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rotki@1.0.7 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lefteris/.npm/_logs/2020-01-18T17_26_34_793Z-debug.log
```

**Comment by kelsos** [comment]
Damn, I run it 10 times before and it worked, as soon as you posted it started failing :/ give me a moment, does the settings test work properly though?

**Comment by LefterisJP** [comment]
After the push the individual commands run and pass. At least the 2 times I tried.

**Pull request merged**
