### PR TITLE
Add Chinese translation to line 125

### PR DESCRIPTION
**Pull request by dongdongzhuzhu**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by yabirgb** [comment]
Hello @dongdongzhuzhu ! We try to keep the git history as clean as possible and we use rebase instead of merge commits. Could you undo that and leave the PR in one commit only?

**Comment by LefterisJP** [comment]
you don't need to close the PR. You can just push into the same branch.

**Review by LefterisJP — COMMENTED** [review]
Read up on git interactive rebase and how to squash commits and force push in a branch.

Alternatively I can also just squash all commits at merge time, but I think it would be beneficial for you to learn how to do it if you don't know how to and you want to get involved with git.

**Comment by dongdongzhuzhu** [comment]
ok is that so?

**Comment by dongdongzhuzhu** [comment]
I haven't modified other files, I don't know why there are so many file changed after using rebase

>

**Pull request closed without merging**
