### PR TITLE
Make asset movement inclusion optional with an accounting option

### LINKED ISSUE #176: Make asset movement inclusion optional with an accounting option
## Problem Definition

History processing and tax report calculation at the moment always takes into account any asset movements from and to exchanges. Exchanges withdrawals always have fees and they are taken by default into account as a loss.

This should be made customizable.

## Tasks
todo

Add a new accounting option named `account_for_asset_movements`. 

- [ ] The location of the setting in the UI should be as shown in the screenshot above.
- [ ] The UI part should be done just like `include_crypto2crypto` is done. Source link [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/ui/accounting_settings.js#L94). Note: There is more places in the front-end code where it should be added.
- [ ] Pass the option to the backend and specifically to the accountant class as seen [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/accounting/accountant.py#L88) and as is also done for `include_crypto2crypto`.
- [ ] Use the option in the `add_asset_movement_to_events` function [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/accounting/accountant.py#L163).

### PR DESCRIPTION
**Pull request by djibix**
Fix #176
Added switch in the accounting settings "Take into account assets movements fees"
Default value: true

Not really sure about the proper use of the new setting in:
rotkehlchen/accounting/accountant.py
line 132

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
From my side it looks okay. A test would have also been nice, but I know this may be a bit more complicated for someone new on the codebase.

@kelsos Is the frontend okay?

**Comment by kelsos** [comment]
> From my side it looks okay. A test would have also been nice, but I know this may be a bit more complicated for someone new on the codebase.
> 
> @kelsos Is the frontend okay?

let me have a look

**Comment by djibix** [comment]
@LefterisJP sorry I didn't mean to request your review again, I just pressed something that looked like a refresh button... Don't take that into account

**Comment by kelsos** [comment]
@djibix when you are ready also ping me for the frontend :)

**Comment by djibix** [comment]
> @djibix are you ready should I take a look at the frontend?

@kelsos sure, how do we proceed?

**Comment by kelsos** [comment]
@LefterisJP looks good on my side, nothing to add 
@djibix thank you :)

**Comment by djibix** [comment]
> @LefterisJP looks good on my side, nothing to add
> @djibix thank you :)

With pleasure! My first successful pull request in an opensource project. Quite proud of it :-)

**Review by LefterisJP — APPROVED** [review]
@djibix looks good to me. Before merging can you add another commit with a changelog entry? It's a feature you are adding. Check how the changelo enties for features are written and write one describing (in the same way the other features are) what changes for the users.

Thank you :bow:

**Comment by djibix** [comment]
> @djibix looks good to me. Before merging can you add another commit with a changelog entry? It's a feature you are adding. Check how the changelo enties for features are written and write one describing (in the same way the other features are) what changes for the users.
> 
> Thank you 🙇

Hi @LefterisJP, I'll try to do that in the coming days. Sorry for delays...

**Comment by LefterisJP** [comment]
@djibix no worries, I did it myself since we wanted the change in! Again thank you so much for your contribution.

**Pull request merged**
