### PR TITLE
fix: transaction page performance

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- Fix transaction page performance by updating the identifier

### CODE REVIEW

**Review by kelsos — APPROVED** [review]
Lgtm thank you

**Review by yabirgb — APPROVED** [review]
Thanks @lukicenturi ! Is much better now :)

**Comment by yabirgb** [comment]
Ah noticed something new. I was in the ethereum transactionms tab and wanted to change to P&L and then that changes freezes again the app

**Comment by kelsos** [comment]
> Ah noticed something new. I was in the ethereum transactionms tab and wanted to change to P&L and then that changes freezes again the app

It could be the same issue but with pnl, we have an open PR for the pnl refactor so maybe it makes sense to take care of it there

**Pull request merged**
