### PR TITLE
Temporary fixes to Win integration test scripts

### LINKED ISSUE #932: Tests Scripts do not run on Windows due to environment variable setting
## Problem Definition

Due to the setting of environment variables, test scripts currently do not execute properly on Windows.

E.g.:
` "test:e2e": "CODE_COVERAGE=true vue-cli-service test:e2e",` in Windows would be:
` "test:e2e": "set CODE_COVERAGE=true && vue-cli-service test:e2e",`

## Solution

We can make separate scripts for Windows, or figure out how to use the .env files we have in the scripts with a cross-platform script command, or use a module like [cross-env](https://www.npmjs.com/package/cross-env) for cross-platform script commands with env variable setting.

### PR DESCRIPTION
**Pull request by isidorosp**
Fix #932

Just opening this PR so anyone who is building on windows can use it for Windows integration test scripts. Let's decide if we just want to have separate scripts or set it up so we have cross-platform scripts.

### CODE REVIEW

**Comment by LefterisJP** [comment]
@kelsos I don't see why we can't have specific OS npm commands for windows. Can you take a look here. And if fine, approve?

**Comment by kelsos** [comment]
I would rather fix it in a non os specific way. Let me gage a look later today to check some things I have in mind.

**Comment by LefterisJP** [comment]
So do we need this PR @isidorosp now that https://github.com/rotki/rotki/pull/960 is merged? I guess not?

**Comment by isidorosp** [comment]
> So do we need this PR @isidorosp now that #960 is merged? I guess not?

No, I will close it!

**Pull request closed without merging**
