### PR TITLE
Removes unneeded wrapping of axios requests

### PR DESCRIPTION
**Pull request by kelsos**
Taking care of some technical debt.

### CODE REVIEW

**Comment by isidorosp** [comment]
When should each of these different session validators be used? It's not immediately clear (e.g. validSessionStatus and validSessionStatus seem identical in signature/content):
```
  validWithSessionAndExternalService,
  validStatus,
  validSessionStatus,
  validWithoutSessionStatus,
  validWithSessionStatus,
  validSessionModifyStatus,
  validTaskStatus
```

**Comment by kelsos** [comment]
Well, this depends entirely on the backend. These patterns are noticed in retrospective. I could try to document them but it will always be empirically based on the status that the backend returns. 

No, they are not identical, you can see that one considers 409 a valid status code and requires a logged user in order to call the endpoint. The other considers 400 since it has some query parameters and (bad request) but works even without a session/user logged in.

**Comment by LefterisJP** [comment]
Ignore the backend tests. They failed due to changes in makerdao stability fees. Should change the tests to not test for those.

**Comment by LefterisJP** [comment]
I am force merging. Will see if I can fix the tests in another PR quickly.

**Pull request merged**
