### PR TITLE
chore(ci): update to `actions/checkout@v4`

### PR DESCRIPTION
**Pull request by TomAFrench**
Fixes CI issue in https://github.com/rotki/rotki/pull/6573

https://github.com/actions/checkout/issues/1448#issuecomment-1705296071

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by TomAFrench** [comment]
Whoops, wrong action.

**Comment by LefterisJP** [comment]
I did a `--rebase-onto` bugfixes since this seems to affect everything

**Comment by LefterisJP** [comment]
Can you maybe point to where they advice changing to v4 @TomAFrench? Their status still seems to point to having problems:  https://www.githubstatus.com/

**Review by LefterisJP — APPROVED** [review]
LGTM but let's see if anyone else has objections

**Pull request merged**
