### PR TITLE
Add new airdrop status: Missed 😭 (squashed)

### PR DESCRIPTION
**Pull request by DaWe35**
This PR is the same as https://github.com/rotki/rotki/pull/8184 but sqashed

### CODE REVIEW

**Comment by LefterisJP** [comment]
> This PR is the same as #8184 but sqashed

hmmm it still has conflicts. You don't need to open another PR to push squashed changes. You can just force push in your PR. Please don't open a new PR to do that as it spams the repo.

Also can you remove the emoticon from the frontend label? It was in the issue but was not meant to be in the frontend itself.

**Comment by DaWe35** [comment]
@LefterisJP Sure, I removed the emoji. I usually avoid using force push, can't you just Squash merge instead?
image

**Review by LefterisJP — COMMENTED** [review]
I can squash and merge and could do the same in the previous PR ;)

Please don't be afraid of force pushing.

You need to fix linting though as backend lint failed.

**Comment by LefterisJP** [comment]
I'll take it over

**Review by LefterisJP — APPROVED** [review]
LGTM. Had to make some fixes and adjust tests.

**Comment by LefterisJP** [comment]
Just repushed to adjust double changelog from after rebase. Won't let tests run.

**Comment by DaWe35** [comment]
Thank you @LefterisJP, I had to take some days off. I'm happy to see this merged 🙏🙏

**Pull request merged**
