### PR TITLE
Introduces an table expand container

### LINKED ISSUE #2388: Unify table extended container
## Abstract

Create a component that unifies the area and css for extend table information

## Motivation

Unified look and feel

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2388

### CODE REVIEW

**Comment by kelsos** [comment]
@LefterisJP this is mostly refactoring and unifying the extended area but can we get it merged at some point?

**Comment by LefterisJP** [comment]
> @LefterisJP this is mostly refactoring and unifying the extended area but can we get it merged at some point?

sure I can do a review. But it needs rebasing. What extended area should I look at?

**Comment by kelsos** [comment]
> > @LefterisJP this is mostly refactoring and unifying the extended area but can we get it merged at some point?
> 
> sure I can do a review. But it needs rebasing. What extended area should I look at?

All of them (there is a premium part) except the dex trades where we have the always visible extend.

**Review by LefterisJP — COMMENTED** [review]
I think this needs rebase. I tried to test it with my account and I think I hit the transactionid problem in deposits/withdrawals

**Comment by kelsos** [comment]
Yes it needs, there are conflicts I will do the rebasing and merging as soon as I can put a pause to what I am working on.

**Pull request merged**
