### PR TITLE
fixes airdrops claimed

### PR DESCRIPTION
**Pull request by dimyG**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
code change makes sense. But perhaps would make sense to be checked by the people who tested with the frontend too

**Comment by yabirgb** [comment]
@LefterisJP I have checked it and works. What is left is the cow airdrop in gnosis that is not shown as claimed because we don't support gnosis yet but is a known limitation

**Comment by LefterisJP** [comment]
> @LefterisJP I have checked it and works. What is left is the cow airdrop in gnosis that is not shown as claimed because we don't support gnosis yet but is a known limitation

That's unrelated to the PR I guess since it's not possible to show as claimed without gnosis support.

**Review by LefterisJP — APPROVED** [review]
LGTM then. LEt's see how tests do

**Pull request merged**
