### PR TITLE
[WIP] Add ICONOMI exchange

### LINKED ISSUE #629: Add ICONOMI platform
## Abstract

Add ICONOMI support for importing trades.

## Motivation

I'd like to see my ICONOMI balances in rotki.

## Specification

ICONOMI has an API at https://www.iconomi.com/api-docs

### PR DESCRIPTION
**Pull request by coinyon**
Like the Bitcoin.de PR, this is in development. I opened this PR to have CI checks run as I work on this.

Currently only works for querying balances. ICONOMI has a "trades" API in their docs, but it is not yet pushed to production.

Closes #629

### CODE REVIEW

**Comment by LefterisJP** [comment]
Nice work @coinyon! We could also make some exceptions for some exchanges if it's really hard to get trades from them and only display balances. But isn't it a bit strange to not be able to query an exchange's trades? What is iconomi exactly?

**Comment by coinyon** [comment]
It is a little strange, I wrote them about that :-)

They are not an exchange, but more like a Coinbase-type way to buy and sell crypto. 

They also offer rebalancing funds they call "strategies". This is another issue I don't know how rotki wants to deal with. It is unfeasable to add each strategy to `all_assets.json`. But nevertheless they are important as individual assets I think. The same issue can rise up when you start implementing the Set protocol on Ethereum. What are your thoughts on that?

For Buchfink I thought about giving the user the possibility to extend the supported assets by adding them to the YAML file, but then the user also has to give price info....

**Comment by LefterisJP** [comment]
Hey @coinyon 

>  But nevertheless they are important as individual assets I think. The same issue can rise up when you start implementing the Set protocol on Ethereum. What are your thoughts on that?

I have not given it that much thought yet as nobody has requested support for them yet, ergo they are way down the backlog of things to do.

> For Buchfink I thought about giving the user the possibility to extend the supported assets by adding them to the YAML file, but then the user also has to give price info....


Hmm I would recommend to keep a consistent strategy and implement it in Rotki too. As they are not an individual asset but a combination of asset they would need special care. Quickly off the top off my head some ideas:

1. Handle each case (sets, iconomi) separately. Somehow query all potential token sets from their API and show them to the user and keep a local cache of them. For historic queries, we can't query their prices in any way unless the token sets themselves offer a way to show historic prices. 

2. We could treat it like a blackbox position. Get the name of the position (token set). Get the enter prices, get the exit prices, do a simple sum to get profit/loss. Show that to the user.

3. Create a generic approach for basket of assets. If we know that this position is 60% ETH, 30% BAT and 10% DAI, and we know the timestamps of each buy/sell event we can calculate the positions value. Also if we know the rebalanced percentages (i.e. if on 01/01/2020 it changes to 90% ETH and 10%BAT) of each rebalancing event then we can still keep calculating the value over time.


I like the idea of (3). Definitely needs more work, but is cleaner and would scale across any similar other service offering basket of known assets.

**Comment by coinyon** [comment]
I think I'm somewhere between 1 and 2. 3 is too much work in my eyes because it requires to know the internals of a ICONOMI strategy or a Token Set. In the future we will see more complicated DeFi-Baskets (with lending and leveraged tokens for example) which makes this a bottomless pit in my eyes. Also taxwise only the blackbox approach is relevant I think.

**Comment by LefterisJP** [comment]
For portfolio tracking (3) is needed though. And if indeed there are more basket of token options in the future the pain of implementing it properly once will pay off in the future.

**Pull request closed without merging**
