### PR TITLE
Show missing acquisitions and price on pnl report

### LINKED ISSUE #4185: Group all acquisition not found and price not found messages for a PnL report
## Abstract

Especially now with v1.24.0 and the accuracy we get to for acquisition and spends there is going to be a lot of [acquisition not found](https://rotki.readthedocs.io/en/latest/usage_guide.html#no-documented-acquisition-found) errors. Also a lot of 

> Skipping event .. during history processing due to inability to find a price

errors.

This becomes really tiring and hard to navigate for a user.

It would be really beneficial if instead of putting them in the messages aggregator we create a special system for them to be shown independently of the messages at the end of the pnl report.

This is kind of related and perhaps part of https://github.com/rotki/rotki/issues/277

## Task

1. Change the code that adds a message to the messages aggregators whenever there is a problem with missing acquisitions https://github.com/rotki/rotki/blob/629a2d49e1c6ea0aa214d1e6195cc9640465549e/rotkehlchen/accounting/cost_basis/base.py#L244

https://github.com/rotki/rotki/blob/629a2d49e1c6ea0aa214d1e6195cc9640465549e/rotkehlchen/accounting/cost_basis/base.py#L306

2. Instead make it keep the information in a different structure which will be queriable by the frontend at the end of the PnL report and will be shown to the user as part of the report and not as 1000s of "error messages".

### Missing Acquisitions

The structure should at least contain the following:

```python
class MissingAcquisition(NamedTuple):
    asset: Asset
    time: Timestamp
    missing_amount: FVal
```

and be kept in a list at the [CostBasisCalculator](https://github.com/rotki/rotki/blob/5543f832cb0d9c4170940bd3e25977274082c9a3/rotkehlchen/accounting/cost_basis/base.py#L221) object which is part of each PnL run.

### Missing Prices

This is a bit trickier. The accountant skipping an event due to a missing price is caught via an exception. And it's here (let's leave the unsupported asset query for later -- though it may need similar handling):

https://github.com/rotki/rotki/blob/5543f832cb0d9c4170940bd3e25977274082c9a3/rotkehlchen/accounting/accountant.py#L170

#### Getting info from the exception

Now the tricky part comes in getting the information. As the only thing that we get at that point is the exception. 

https://github.com/rotki/rotki/blob/5543f832cb0d9c4170940bd3e25977274082c9a3/rotkehlchen/errors.py#L92-L98

The `NoPriceForGivenTimestamp` error already has all information passed to it at construction. It just needs some adjustment in order to keep the information in the exception's state. So it should keep from the `from_asset`, and `to_asset` in the exception.

What's more it should not get a `date` but a timestamp in the constructor. And that timestamp should also be kept in the exception's state. But it should be converted into a date for the error message when passed to the base exception's constructor.

##### Keeping the information

I guess we should have another list of missing_prices for a pnl report that should be initialized at `reset()` and it should just keep a list of a named tuple like this:

```python
class MissingPrice(NamedTuple):
    from_asset: Asset
    to_asset: Asset
    time: Timestamp
```

### Querying from the API

Now that we will have all this data in nice lists of data structures instead of just error messages for the user we can do very cool stuff. We would need a new api endpoint.

I would probably name it 

`'/history/actionable_items', HistoryActionableItemsResource`

And make it return the list of missing acquisitions and list of missing prices.

### Frontend

Then the frontend would need to query that endpoint once a report is done and it would show all actionable items of that last report.

The frontend can do nice magic here:

- For every missing price take them to the manual historical prices addition with from/to asset and timestamp pre-filled and only thing needed being for the user to input the price. SCOOOOOORE :smile: 
- For missing acquisitions ... hmm wish we could do something similar but perhaps we can just group them by asset or something and present them to the user. I am not sure we can pre-fill actions for them.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4185

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by yabirgb** [comment]
@LefterisJP @kelsos For this PR there are tokens that could be missing the price and it is actually difficult to get the price for them (for example curve assets)... what would you say is the best experience here? Letting the user know that if the price is not filled it will default to 0?

**Comment by LefterisJP** [comment]
> @LefterisJP @kelsos For this PR there are tokens that could be missing the price and it is actually difficult to get the price for them (for example curve assets)... what would you say is the best experience here? Letting the user know that if the price is not filled it will default to 0?

As per discord. For whatever token no price can be input by the user it should just stay there as a warning in the PnL report. A price of 0 is an error and is anyway what the PnL report logic does for whatever price is not found.

**Review by kelsos — APPROVED** [review]
code looks good @lukicenturi thank you, @yabirgb @LefterisJP you can check the rest

**Review by LefterisJP — COMMENTED** [review]
Some comments left in the PR


###  Ethereum Assets without name/symbol

Why not show it as ethereum token with the given address? The __ceth__ thing is not supposed to be user facing.




### Frontend exception

When adding a price to one of the fields I see frontend exceptions.

**Comment by lukicenturi** [comment]
> Some comments left in the PR
> 
> ### Ethereum Assets without name/symbol
> Why not show it as ethereum token with the given address? The **ceth** thing is not supposed to be user facing.
> 
> 
> 
> ### Frontend exception
> When adding a price to one of the fields I see frontend exceptions.
> 
> 

Hmm, the missing asset isn't supposed to happen. Is it still happen when restarting the app (npm run dev again)

For the exception, it's from backend that returning 500 error.

Is it possible that we add historical price for asset that are not detected, that causing the exception?

**Comment by LefterisJP** [comment]
> Hmm, the missing asset isn't supposed to happen. Is it still happen when restarting the app (npm run dev again)
>
> For the exception, it's from backend that returning 500 error.
>
> Is it possible that we add historical price for asset that are not detected, that causing the exception?

I would have to look it up when I find time.

The address I tried is: 0x4066643f04859fa538ba8eaa906c197c57e4e3e0

**Review by LefterisJP — APPROVED** [review]
LGTM

**Pull request merged**
