### PR TITLE
Allow users to input a beaconcha.in API key

### LINKED ISSUE #1838: Allow users to add a beaconcha.in api key
## Abstract

We are using the [beaconcha.in API](https://beaconcha.in/api/v1/docs/index.html) for eth2 stuff at the moment. They are a pretty cool opensource beacon chain explorer. By default queries there have a limit of 10 queries per minute. In rotki we try to respect that limit by incrementally backing off if we get a 429 from them.

But a way to get around that limit and also support a cool project would be for a user who needs more queries to purchase an API key and increase the limits: https://beaconcha.in/pricing

## Task

- [ ] Allow addition of a beaconcha.in API key from the frontend
- [ ] Save an optional API key from the user in the beaconcha.in object and use it if it exists, much like we do in ethescan and cryptocompare.

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix #1838 

@kelsos can you add a commit on top of here so that the user can add the key from the frontend?

### CODE REVIEW

**Comment by kelsos** [comment]
@LefterisJP done

**Comment by LefterisJP** [comment]
hmmm why is check-frontend failing @kelsos ?

**Comment by kelsos** [comment]
A piece of setup in the unit test was missing. Now it should be fine.

**Comment by LefterisJP** [comment]
The failed test is fixed in another branch by me. I will merge this one.

**Pull request merged**
