### PR TITLE
Add xtokens available at coingecko

### PR DESCRIPTION
**Pull request by yabirgb**
Add `xtoken`s  (https://xtoken.market/app) that have been tracked by coingecko

### CODE REVIEW

**Comment by yabirgb** [comment]
> Hey @yabirgb can you also add changelog entries and adjust the md5 sum both in the all_assets.meta and the unit tests as per our docs? https://rotki.readthedocs.io/en/latest/contribute.html#adding-new-assets-to-rotki

Fixed. I had an issue in local with an address of the `all_assets.json` being cached and making the tests fails. I don't know why that was happening. Now everything should be fine

**Review by LefterisJP — COMMENTED** [review]
Hey @yabirgb sorry I did not catch it before but can you also remove all "active" keys. They are not needed. If it's active by default it's true. Plus in the new way of representing assets we are going to get rid of the active key.

Also can you add changelog entries for those assets? Make a new one above the release. Since this is probably not going in v1.15.0 but gonna be pulled by it. (I want to actually test this works also).

Don't forget that editing all_assets.json edits the md5 sum again.

**Comment by yabirgb** [comment]
@LefterisJP Everything should be ok now. About the `active` flag I thought it was used to track tokens like for example `ytDAI` (DAI Ironbank https://yearn.rocks/daiironbank) that are no longer being used.

**Comment by LefterisJP** [comment]
> @LefterisJP Everything should be ok now. About the `active` flag I thought it was used to track tokens like for example `ytDAI` (DAI Ironbank https://yearn.rocks/daiironbank) that are no longer being used.

This is what the thinking was for. So that we don't query current price for it if it's considered inactive. But in practise we have not used this field at all yet. So just ignoring it for now.

And not providing it means that it's active by default so in your PR's case it's all fine.

**Pull request merged**
