### PR TITLE
Change encoding in logging file handler

### LINKED ISSUE #5057: Unicode logging entries in Windows
## Problem Definition

While checking the logs of a Windows user I noticed the following repeating multiple times inside rotki-electron.log

```--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1086, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 101: character maps to <undefined>
Call stack:
  File "rotkehlchen\api\rest.py", line 298, in _do_query_async
  File "rotkehlchen\api\rest.py", line 664, in _query_blockchain_balances
  File "rotkehlchen\utils\mixins\lockable.py", line 46, in wrapper
  File "rotkehlchen\utils\mixins\cacheable.py", line 97, in wrapper
  File "rotkehlchen\chain\manager.py", line 616, in query_balances
  File "rotkehlchen\utils\mixins\lockable.py", line 46, in wrapper
  File "rotkehlchen\utils\mixins\cacheable.py", line 97, in wrapper
  File "rotkehlchen\chain\manager.py", line 1150, in query_ethereum_balances
  File "rotkehlchen\chain\manager.py", line 1083, in query_ethereum_tokens
  File "rotkehlchen\chain\evm\tokens.py", line 341, in query_tokens_for_addresses
  File "rotkehlchen\chain\evm\tokens.py", line 181, in _get_multicall_token_balances
  File "logging\__init__.py", line 1800, in debug
  File "logging\__init__.py", line 1844, in log
  File "logging\__init__.py", line 1512, in log
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Greenlet-4: Found \u2728(0x714a91578624d76A209E9aA4aF9a1F55d78f9190) token balance for 0x<redacted> and balance 6.434434324'
Arguments: ()
```

I suspect there may be an issue making unicode log entries to a windows file

## Task

Reproduce and fix

### PR DESCRIPTION
**Pull request by yabirgb**
Closes #5057

### CODE REVIEW

**Comment by yabirgb** [comment]
I've tried to reproduce the error in my windows machine and was not able. Uninstalled all the languages too and left only US english but that didn't do the trick. 

I've checked that the binary generated by this PR works as expected and the logs keep working and showing the information.

About the failing tests is not related to this PR but we need to check it. Looks strange and is the first time I see this one here

**Review by LefterisJP — APPROVED** [review]
LGTM. It's not a bad thing to be specific on encoding. I will merge it though I am not 100% sure this is it if we can't reproduce.

I asked the user in whose logs I saw this to send me their default encoding by typing `[System.Text.Encoding]::Default` in powershell.

Their result was 
```
IsSingleByte      : True
BodyName          : iso-8859-1
EncodingName      : Western European (Windows)
HeaderName        : Windows-1252
WebName           : Windows-1252
WindowsCodePage   : 1252
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1252
```

It seems to be suggested that sometimes in some windows installations default encoding is this `cp1252` which can also be seen in the logs traceback.

So by doing this change and specifying utf-8 it should be enforced.

There is many many such instances of people having problems with unicode and this cp1252 encoding.

**Comment by LefterisJP** [comment]
Ah ffs @yabirgb you had it on develop and changing the target branch pulls other commits. Ffs be careful. I will have to edit this.

**Comment by LefterisJP** [comment]
Did an interactive rebase on bugfixes and purged all other commits and force pushed the branch.

**Pull request merged**
