### PR TITLE
chore: major dependency updates ts5, electron 24

### PR DESCRIPTION
**Pull request by kelsos**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by lukicenturi** [comment]
@kelsos can you run it with node 18?
I got error on the dev-proxy with node 18, I think it's because `http-proxy-middleware` hasn't supported node 18 yet.

Everything is fine with node 16.

**Comment by kelsos** [comment]
> @kelsos can you run it with node 18? I got error on the dev-proxy with node 18, I think it's because `http-proxy-middleware` hasn't supported node 18 yet.
> 
> Everything is fine with node 16.

Let me see I might have had the proxy disabled

**Comment by kelsos** [comment]
> > @kelsos can you run it with node 18? I got error on the dev-proxy with node 18, I think it's because `http-proxy-middleware` hasn't supported node 18 yet.
> > Everything is fine with node 16.
> 
> Let me see I might have had the proxy disabled it might be related to the e2e changes I had to do where I had to specify the listening address as either `127.0.0.1` or `localhost`

So that's it, I am not sure what changed to resolution in newer node, but unless you specify 127.0.0.1 which is the backend's listening IP it won't accept connections.

It could be that the changed something and localhost uses the IPv6 instead. That would explain the problem.

**Review by lukicenturi — APPROVED** [review]
LGTM! works well now, thanks

**Pull request merged**
