### PR TITLE
Fix error location redirection for account chain

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by yabirgb — COMMENTED** [review]
Got this error while checking the PR 

image

**Comment by lukicenturi** [comment]
> Got this error while checking the PR
> 
> image

Fixed, you can try again 💯

**Review by yabirgb — APPROVED** [review]
It is of my honor to say that it works fine now. Thanks

**Review by LefterisJP — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
