### PR TITLE
Pressing the dashboard add manual balance/add blockchain address will open the respective forms

### LINKED ISSUE #1001: Enhance "Add..." button functionality in the dashboard
## Abstract & Motivation

When a user doesn't have any exchange /  blockchain / manual balances, a button appears urging the user to add something. This button currently just takes the user to the relevant page (api keys / accounts & balances). The button should do more. It should:
- take the user to the specific page where the action can be performed, and/or
- present the user with a modal allowing the user to add content without leaving the dashboard

## Specification

In some cases work will be required in the linked pages to allow linking to a specific section (or tab, if a page will be broken up into navigable parts).

TBD

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1001 

This is the minimum effort approach that uses a query parameter to open the modal.

### CODE REVIEW

**Review by LefterisJP — APPROVED** [review]
So looks good to me. Seems to work. One question would be what's the best way to achieve the same effect if there is already a balance? The title does not seem to be clickable.

Also needs rebase on develop for changelog.

**Comment by kelsos** [comment]
I will rebase. I really have no idea what would be the best option to do that.

**Comment by LefterisJP** [comment]
> I will rebase. I really have no idea what would be the best option to do that.

Maybe making the title clickable to go to the appropriate section?

**Comment by kelsos** [comment]
> > I will rebase. I really have no idea what would be the best option to do that.
> 
> Maybe making the title clickable to go to the appropriate section?

We can make that I am not sure if that would be obvious. Maybe we can ask for suggestions in design?

**Pull request merged**
