### PR TITLE
fix: empty tags to null

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Tests are failings still. Is there something off?

**Comment by lukicenturi** [comment]
> Tests are failings still. Is there something off? 

My bad, should be fine now

**Review by LefterisJP — APPROVED** [review]
LGTM since tests pass.

@kelsos I am taking the liberty to approve and merge to unblock our CI green-ness. If you find anything wrong please fix in subsequent PRs.

**Comment by kelsos** [comment]
I was doing a check, it it would make sense for all the payload classes that deal with arrays that are send to the backend to start introducing a `NonEmptyArray<T> | null` maybe as a type.

https://stackoverflow.com/questions/56006111/is-it-possible-to-define-a-non-empty-array-type-in-typescript

**Comment by kelsos** [comment]
@lukicenturi also we have a method to remove nullable fields from the payload in these cases maybe it would make sense to use them.

**Pull request merged**
