### PR TITLE
Only show keychain prompt when needed

### LINKED ISSUE #4378: Rotki probes macOS password for install-helper and "Chromium Safe Storage" in macOS keyring
After I haven't used Rotki for some months it notified me of a update which I downloaded via its internal updater.
Following the download I get macOS popups to enter my macOS login password to install Rotki helper installer and once again to access "Cromium Safe Storage":

Is this behaviour genuine?

Bildschirmfoto 2022-05-27 um 23 37 20

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4378 

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by lukicenturi** [comment]
This will prevent the prompt to appear from the start, but after users click `Remember Me` and hit the `Login` button.

But if the user has already activated the `Remember Me` before, then it still prompts from the beginning of the login screen because it will try to get the saved password from the storage (because this one need permission from the keychain). @kelsos

**Comment by kelsos** [comment]
> This will prevent the prompt to appear from the start, but after users click `Remember Me` and hit the `Login` button.
> 
> But if the user has already activated the `Remember Me` before, then it still prompts from the beginning of the login screen because it will try to get the saved password from the storage (because this one need permission from the keychain). @kelsos

That sounds pretty reasonable to me.

**Comment by lukicenturi** [comment]
image

@kelsos by the way, here is how to remove the permission from the keychain.

Check on both entries inside the rectangle, open the menu `Access Control`, and remove Rotki from there.

**Comment by kelsos** [comment]
@lukicenturi this needs to be rebased on top of bugfixes and then we are good to go :) 

I tested the macOS part. It works as expected thank you.

**Comment by lukicenturi** [comment]
> need to not include develop's commits

develop's commits removed

**Comment by kelsos** [comment]
@LefterisJP you also have to approve since you blocked :smile:

**Review by LefterisJP — APPROVED** [review]
LGTM. Thank you Luki and Kelsos

**Pull request merged**
