### PR TITLE
Improves handling and propagation of sigint on development scripts

### PR DESCRIPTION
**Pull request by kelsos**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

@lukicenturi can you check when you have time. 

It seems to resolve the annoying situation where you get an electron unhandled exception popup when terminating the dev server with ctrl+c

### CODE REVIEW

**Comment by lukicenturi** [comment]
@kelsos is it this, or different popup error? 
this one still appear in this PR
image

**Comment by kelsos** [comment]
It was this, and yesterday I did 10-20 tries in the row and it was gone :/

**Comment by lukicenturi** [comment]
> It was this, and yesterday I did 10-20 tries in the row and it was gone :/

hmm oh yeah, after I clean everything and `pnpm install` again, it removes the popup.
I will merge it

**Review by lukicenturi — APPROVED** [review]
LGTM!

**Pull request merged**
