### PR TITLE
Bump urllib3 and gevent's greenlet

### PR DESCRIPTION
**Pull request by LefterisJP**
This is trying to see if the problem in https://github.com/rotki/rotki/pull/6203 persists here too. As some small tests did not reproduce it.

### CODE REVIEW

**Comment by LefterisJP** [comment]
first run all green.

**Comment by LefterisJP** [comment]
2nd run one failure:

```
FAILED rotkehlchen/tests/unit/decoders/test_liquity.py::test_liquity_pool_deposit[ethereum_accounts0] - sqlite3.OperationalError: interrupted
```
which is a bit weird.

```
rotkehlchen/tests/unit/decoders/test_liquity.py:433: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rotkehlchen/chain/ethereum/decoding/decoder.py:57: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:987: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:167: in __init__
    self.rules += self._recursively_initialize_decoders(self.chain_modules_root)
rotkehlchen/chain/evm/decoding/decoder.py:259: in _recursively_initialize_decoders
    self._add_single_decoder(class_name=class_name, decoder_class=submodule_decoder, rules=rules)  # noqa: E501
rotkehlchen/chain/evm/decoding/decoder.py:192: in _add_single_decoder
    self.decoders[class_name] = decoder_class(
rotkehlchen/chain/ethereum/modules/yearn/decoder.py:60: in __init__
    vaults_v2 = GlobalDBHandler().get_evm_tokens(chain_id=ChainID.ETHEREUM, protocol=YEARN_VAULTS_V2_PROTOCOL)  # noqa: E501
rotkehlchen/globaldb/handler.py:879: in get_evm_tokens
    underlying_tokens = GlobalDBHandler().fetch_underlying_tokens(other_cursor, entry[0])  # noqa: E501
rotkehlchen/globaldb/handler.py:688: in fetch_underlying_tokens
    cursor.execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rotkehlchen.db.drivers.gevent.DBCursor object at 0x7f786cb39bd0>
statement = 'SELECT B.address, B.token_kind, A.weight FROM underlying_tokens_list AS A JOIN evm_tokens as B WHERE A.identifier=B.identifier AND parent_token_entry=?;'
bindings = (('eip155:1/erc20:0xa354F35829Ae975e850e23e9615b11Da1B3dC4DE',),)

    def execute(self, statement: str, *bindings: Sequence) -> 'DBCursor':
        if __debug__:
            logger.trace(f'EXECUTE {statement}')
        try:
>           self._cursor.execute(statement, *bindings)
E           sqlite3.OperationalError: interrupted

rotkehlchen/db/drivers/gevent.py:85: OperationalError
```

**Comment by LefterisJP** [comment]
3rd run no failures

**Comment by LefterisJP** [comment]
4th run

```
rotkehlchen/tests/unit/decoders/test_main.py::test_decoders_initialization - sqlite3.OperationalError: interrupted
```

Which  looks similar to 2nd run failure

```
_______________ ERROR at setup of test_decoders_initialization ________________

database = <rotkehlchen.db.dbhandler.DBHandler object at 0x7f04d54f3070>
ethereum_inquirer = <rotkehlchen.chain.ethereum.node_inquirer.EthereumInquirer object at 0x7f04d5196080>
eth_transactions = <rotkehlchen.chain.ethereum.transactions.EthereumTransactions object at 0x7f04d5197430>

    @pytest.fixture(name='ethereum_transaction_decoder')
    def fixture_ethereum_transaction_decoder(
            database,
            ethereum_inquirer,
            eth_transactions,
    ):
        with patch_decoder_reload_data():
>           yield EthereumTransactionDecoder(
                database=database,
                ethereum_inquirer=ethereum_inquirer,
                transactions=eth_transactions,
            )

rotkehlchen/tests/fixtures/blockchain.py:299: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rotkehlchen/chain/ethereum/decoding/decoder.py:57: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:987: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:167: in __init__
    self.rules += self._recursively_initialize_decoders(self.chain_modules_root)
rotkehlchen/chain/evm/decoding/decoder.py:259: in _recursively_initialize_decoders
    self._add_single_decoder(class_name=class_name, decoder_class=submodule_decoder, rules=rules)  # noqa: E501
rotkehlchen/chain/evm/decoding/decoder.py:192: in _add_single_decoder
    self.decoders[class_name] = decoder_class(
rotkehlchen/chain/ethereum/modules/curve/decoder.py:157: in __init__
    ReloadablePoolsAndGaugesDecoderMixin.__init__(
rotkehlchen/chain/evm/decoding/interfaces.py:217: in __init__
    self.cache_data = self.read_data_from_cache_method()
rotkehlchen/chain/ethereum/modules/curve/curve_cache.py:107: in read_curve_pools_and_gauges
    curve_pools[pool_address] = read_curve_pool_tokens(cursor=cursor, pool_address=pool_address)  # noqa: E501
rotkehlchen/globaldb/cache.py:207: in read_curve_pool_tokens
    tokens_data = globaldb_get_general_cache_keys_and_values_like(
rotkehlchen/globaldb/cache.py:152: in globaldb_get_general_cache_keys_and_values_like
    return cursor.execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rotkehlchen.db.drivers.gevent.DBCursor object at 0x7f04d5197fa0>
statement = 'SELECT key, value FROM general_cache WHERE key LIKE ?'
bindings = (('CURVE_POOL_TOKENS0x3CFAa1596777CAD9f5004F9a0c443d912E262[243](https://github.com/rotki/rotki/actions/runs/7069484517/job/19248548596?pr=7038#step:10:244)%',),)

    def execute(self, statement: str, *bindings: Sequence) -> 'DBCursor':
        if __debug__:
            logger.trace(f'EXECUTE {statement}')
        try:
>           self._cursor.execute(statement, *bindings)
E           sqlite3.OperationalError: interrupted

rotkehlchen/db/drivers/gevent.py:85: OperationalError
=============================== warnings summary ===============================
```

**Comment by LefterisJP** [comment]
6th run fine

**Comment by LefterisJP** [comment]
7th run fine

**Comment by LefterisJP** [comment]
8th run fine

**Comment by LefterisJP** [comment]
Lack of other logs and having no idea why an interrupted sqlite error would be raised makes it very hard to debug. Also can't reproduce locally even with pytest-repeat.

**Comment by LefterisJP** [comment]
10th run fine

**Comment by LefterisJP** [comment]
11th run fine

**Comment by LefterisJP** [comment]
12th run similar error as before

```
rotkehlchen/tests/unit/decoders/test_liquity.py::test_liquity_pool_deposit[ethereum_accounts0] - sqlite3.OperationalError: interrupted
```

Traceback

```
=================================== FAILURES ===================================
________________ test_liquity_pool_deposit[ethereum_accounts0] _________________

database = <rotkehlchen.db.dbhandler.DBHandler object at 0x7f26177019c0>
ethereum_inquirer = <rotkehlchen.chain.ethereum.node_inquirer.EthereumInquirer object at 0x7f261772c550>
eth_transactions = <rotkehlchen.chain.ethereum.transactions.EthereumTransactions object at 0x7f261772d8a0>

    @pytest.mark.parametrize('ethereum_accounts', [['0xF04E6f2D27ED324917AD2098F96f5d4ac52e1684']])
    def test_liquity_pool_deposit(database, ethereum_inquirer, eth_transactions):
        """
        Data for deposit taken from
        https://etherscan.io/tx/0x1277cb6c2c8e151fe90118cdd738e46f894e18de04ab6af33d567e91597f322b
        """
        tx_hex = '0x1277cb6c2c8e151fe90118cdd738e46f894e18de04ab6af33d567e91597f322b'
        user_address = string_to_evm_address('0xF04E6f2D27ED324917AD2098F96f5d4ac52e1684')
        evmhash = deserialize_evm_tx_hash(tx_hex)
        transaction = EvmTransaction(
            tx_hash=evmhash,
            chain_id=ChainID.ETHEREUM,
            timestamp=Timestamp(1646375440),
            block_number=14318825,
            from_address=user_address,
            to_address=string_to_evm_address('0x66017D22b0f8556afDd19FC67041899Eb65a21bb'),
            value=0,
            gas=171[249](https://github.com/rotki/rotki/actions/runs/7069484517/job/19261672636?pr=7038#step:10:250),
            gas_price=22990000000,
            gas_used=171249,
            input_data=hexstring_to_bytes('0x5f788d650000000000000000000000000000000000000000000000068155a43676e0000000000000000000000000000030e5d10dc30a0ce2545a4dbe8de4fcba590062c5'),
            nonce=507,
        )
        receipt = EvmTxReceipt(
            tx_hash=evmhash,
            chain_id=ChainID.ETHEREUM,
            contract_address=None,
            status=True,
            type=0,
            logs=[
                EvmTxReceiptLog(
                    log_index=907,
                    data=hexstring_to_bytes('0x0000000000000000000000000000000000000000000000068155a43676e00000'),
                    address=string_to_evm_address('0x5f98805A4E8be255a32880FDeC7F6728C6568bA0'),
                    removed=False,
                    topics=[
                        hexstring_to_bytes('0xddf[252](https://github.com/rotki/rotki/actions/runs/7069484517/job/19261672636?pr=7038#step:10:253)ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
                        hexstring_to_bytes('0x000000000000000000000000f04e6f2d27ed324917ad2098f96f5d4ac52e1684'),
                        hexstring_to_bytes('0x00000000000000000000000066017d22b0f8556afdd19fc67041899eb65a21bb'),
                    ],
                ), EvmTxReceiptLog(
                    log_index=911,
                    data=hexstring_to_bytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
                    address=string_to_evm_address('0x66017D22b0f8556afDd19FC67041899Eb65a21bb'),
                    removed=False,
                    topics=[
                        hexstring_to_bytes('0x51457222ebca92c335c9c86e2baa1cc0e40ffaa9084a51452980d5ba8dec2f63'),
                        hexstring_to_bytes('0x000000000000000000000000f04e6f2d27ed324917ad2098f96f5d4ac52e1684'),
                    ],
                ),
            ],
        )
        dbevmtx = DBEvmTx(database)
        with database.user_write() as cursor:
            dbevmtx.add_evm_transactions(cursor, [transaction], relevant_address=None)
>       decoder = EthereumTransactionDecoder(
            database=database,
            ethereum_inquirer=ethereum_inquirer,
            transactions=eth_transactions,
        )

rotkehlchen/tests/unit/decoders/test_liquity.py:433: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rotkehlchen/chain/ethereum/decoding/decoder.py:57: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:987: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:167: in __init__
    self.rules += self._recursively_initialize_decoders(self.chain_modules_root)
rotkehlchen/chain/evm/decoding/decoder.py:[259](https://github.com/rotki/rotki/actions/runs/7069484517/job/19261672636?pr=7038#step:10:260): in _recursively_initialize_decoders
    self._add_single_decoder(class_name=class_name, decoder_class=submodule_decoder, rules=rules)  # noqa: E501
rotkehlchen/chain/evm/decoding/decoder.py:192: in _add_single_decoder
    self.decoders[class_name] = decoder_class(
rotkehlchen/chain/ethereum/modules/yearn/decoder.py:60: in __init__
    vaults_v2 = GlobalDBHandler().get_evm_tokens(chain_id=ChainID.ETHEREUM, protocol=YEARN_VAULTS_V2_PROTOCOL)  # noqa: E501
rotkehlchen/globaldb/handler.py:879: in get_evm_tokens
    underlying_tokens = GlobalDBHandler().fetch_underlying_tokens(other_cursor, entry[0])  # noqa: E501
rotkehlchen/globaldb/handler.py:688: in fetch_underlying_tokens
    cursor.execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rotkehlchen.db.drivers.gevent.DBCursor object at 0x7f[261](https://github.com/rotki/rotki/actions/runs/7069484517/job/19261672636?pr=7038#step:10:262)7748e80>
statement = 'SELECT B.address, B.token_kind, A.weight FROM underlying_tokens_list AS A JOIN evm_tokens as B WHERE A.identifier=B.identifier AND parent_token_entry=?;'
bindings = (('eip155:1/erc20:0xa354F35829Ae975e850e23e9615b11Da1B3dC4DE',),)

    def execute(self, statement: str, *bindings: Sequence) -> 'DBCursor':
        if __debug__:
            logger.trace(f'EXECUTE {statement}')
        try:
>           self._cursor.execute(statement, *bindings)
E           sqlite3.OperationalError: interrupted

rotkehlchen/db/drivers/gevent.py:85: OperationalError
```

**Comment by LefterisJP** [comment]
From here and on will try only urllib change and put greenlet back.

**Comment by LefterisJP** [comment]
Second run errored with two errors. One etherscan networking and other same sqlite operation interrupted problem as seen above:

```
________________ test_ethereum_grant_payout[ethereum_accounts0] ________________

database = <rotkehlchen.db.dbhandler.DBHandler object at 0x7fe7cd8db640>
ethereum_inquirer = <rotkehlchen.chain.ethereum.node_inquirer.EthereumInquirer object at 0x7fe7cd2e8f10>
ethereum_accounts = ['0x9531C059098e3d194fF87FebB587aB07B30B1306']

    @pytest.mark.vcr()
    @pytest.mark.parametrize('ethereum_accounts', [['0x9531C059098e3d194fF87FebB587aB07B30B1306']])
    def test_ethereum_grant_payout(database, ethereum_inquirer, ethereum_accounts):
        tx_hex = deserialize_evm_tx_hash('0x66ff5be7841f05cc9cb53fd0307460690f91203c52490f5bbfdeabe8462be50b')  # noqa: E501
        evmhash = deserialize_evm_tx_hash(tx_hex)
>       events, _ = get_decoded_events_of_transaction(
            evm_inquirer=ethereum_inquirer,
            database=database,
            tx_hash=tx_hex,
        )

rotkehlchen/tests/unit/decoders/test_gitcoin_v2.py:364: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rotkehlchen/tests/utils/ethereum.py:356: in get_decoded_events_of_transaction
    decoder = mappings_result[1](database, evm_inquirer, transactions)
rotkehlchen/chain/ethereum/decoding/decoder.py:57: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:987: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:167: in __init__
    self.rules += self._recursively_initialize_decoders(self.chain_modules_root)
rotkehlchen/chain/evm/decoding/decoder.py:259: in _recursively_initialize_decoders
    self._add_single_decoder(class_name=class_name, decoder_class=submodule_decoder, rules=rules)  # noqa: E501
rotkehlchen/chain/evm/decoding/decoder.py:192: in _add_single_decoder
    self.decoders[class_name] = decoder_class(
rotkehlchen/chain/ethereum/modules/curve/decoder.py:157: in __init__
    ReloadablePoolsAndGaugesDecoderMixin.__init__(
rotkehlchen/chain/evm/decoding/interfaces.py:217: in __init__
    self.cache_data = self.read_data_from_cache_method()
rotkehlchen/chain/ethereum/modules/curve/curve_cache.py:107: in read_curve_pools_and_gauges
    curve_pools[pool_address] = read_curve_pool_tokens(cursor=cursor, pool_address=pool_address)  # noqa: E501
rotkehlchen/globaldb/cache.py:207: in read_curve_pool_tokens
    tokens_data = globaldb_get_general_cache_keys_and_values_like(
rotkehlchen/globaldb/cache.py:152: in globaldb_get_general_cache_keys_and_values_like
    return cursor.execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rotkehlchen.db.drivers.gevent.DBCursor object at 0x7fe7cd2eb0a0>
statement = 'SELECT key, value FROM general_cache WHERE key LIKE ?'
bindings = (('CURVE_POOL_TOKENS0x7E050cf658777cc1Da4a4508E79d71859044B60E%',),)

    def execute(self, statement: str, *bindings: Sequence) -> 'DBCursor':
        if __debug__:
            logger.trace(f'EXECUTE {statement}')
        try:
>           self._cursor.execute(statement, *bindings)
E           sqlite3.OperationalError: interrupted

rotkehlchen/db/drivers/gevent.py:85: OperationalError
```

**Comment by LefterisJP** [comment]
3rd run passed

**Comment by LefterisJP** [comment]
After rebase on WAL 1st run is fine

**Comment by LefterisJP** [comment]
2nd run is also fine

**Comment by LefterisJP** [comment]
3rd run is also fine

**Comment by LefterisJP** [comment]
4th run is also fine

**Comment by LefterisJP** [comment]
5th run is also fine

**Comment by LefterisJP** [comment]
6th run we got a failure with sqlite interrupted.

Test: `rotkehlchen/tests/unit/decoders/test_main.py::test_genesis_transaction`

```
rotkehlchen/tests/unit/decoders/test_main.py:780: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rotkehlchen/tests/utils/ethereum.py:366: in get_decoded_events_of_transaction
    decoder = mappings_result[1](database, evm_inquirer, transactions)
rotkehlchen/chain/ethereum/decoding/decoder.py:57: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:999: in __init__
    super().__init__(
rotkehlchen/chain/evm/decoding/decoder.py:173: in __init__
    self.rules += self._recursively_initialize_decoders(self.chain_modules_root)
rotkehlchen/chain/evm/decoding/decoder.py:271: in _recursively_initialize_decoders
    self._add_single_decoder(class_name=class_name, decoder_class=submodule_decoder, rules=rules)  # noqa: E501
rotkehlchen/chain/evm/decoding/decoder.py:198: in _add_single_decoder
    self.decoders[class_name] = decoder_class(
rotkehlchen/chain/ethereum/modules/curve/decoder.py:157: in __init__
    ReloadablePoolsAndGaugesDecoderMixin.__init__(
rotkehlchen/chain/evm/decoding/interfaces.py:217: in __init__
    self.cache_data = self.read_data_from_cache_method()
rotkehlchen/chain/ethereum/modules/curve/curve_cache.py:107: in read_curve_pools_and_gauges
    curve_pools[pool_address] = read_curve_pool_tokens(cursor=cursor, pool_address=pool_address)  # noqa: E501
rotkehlchen/globaldb/cache.py:224: in read_curve_pool_tokens
    tokens_data = globaldb_get_general_cache_keys_and_values_like(
rotkehlchen/globaldb/cache.py:169: in globaldb_get_general_cache_keys_and_values_like
    return cursor.execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rotkehlchen.db.drivers.gevent.DBCursor object at 0x7fc194481750>
statement = 'SELECT key, value FROM general_cache WHERE key LIKE ?'
bindings = (('CURVE_POOL_TOKENS0x6868Eb3fcefe1684486F601d2dC10Bbf0C4EEB8b%',),)

    def execute(self, statement: str, *bindings: Sequence) -> 'DBCursor':
        if __debug__:
            logger.trace(f'EXECUTE {statement}')
        try:
>           self._cursor.execute(statement, *bindings)
E           sqlite3.OperationalError: interrupted

rotkehlchen/db/drivers/gevent.py:85: OperationalError
```

Same as above. Seems like harder to happen but still can happen now.

**Comment by LefterisJP** [comment]
So seems like it always happens for a random global DB read that this sqlite interrupted pops up. And it's quite rare and only has happened for the following tests so far:

```
while true; do python pytestgeventwrapper.py -xs --pdb rotkehlchen/tests/unit/decoders/test_main.py::test_genesis_transaction rotkehlchen/tests/unit/decoders/test_liquity.py::test_liquity_pool_deposit rotkehlchen/tests/unit/decoders/test_gitcoin_v2.py::test_ethereum_grant_payout rotkehlchen/tests/unit/decoders/test_main.py::test_decoders_initialization; done
```

**Comment by LefterisJP** [comment]
After adding trace log, 1st run without the error

**Comment by LefterisJP** [comment]
2nd run without error

**Comment by LefterisJP** [comment]
3rd run without error

**Comment by LefterisJP** [comment]
4th run without error ...

**Comment by LefterisJP** [comment]
5th run without error

**Comment by LefterisJP** [comment]
6th run only some bitcoin tests failed with 502 from blockchain info

**Comment by LefterisJP** [comment]
7th run is fine

**Comment by LefterisJP** [comment]
7th run withou error ...

**Comment by LefterisJP** [comment]
9th run, with only 1 test failing due to etherscan timeout

**Comment by LefterisJP** [comment]
10th run all fine. 

So wtf enabling trace logs makes the problem not happen even after 10 runs?

**Comment by yabirgb** [comment]
Could it be that enabling tracing makes some weird combination on how the greenlets behave due to the io and this gives a different output regarding the issue

**Comment by LefterisJP** [comment]
11th run all fine,

> It could be that enabling tracing makes some weird combination on how the greenlets behave due to the io and this gives a different output regarding the issue

Yes but this makes it impossible to debug.

**Comment by LefterisJP** [comment]
12th run fine

**Comment by LefterisJP** [comment]
13th run also fine ...

**Comment by LefterisJP** [comment]
13th run ... just when I removed the trace logging failed with a completely new error:

```
FAILED rotkehlchen/tests/db/test_async.py::test_callback_segfault_simple[100] - gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x7f973528f510 epoll default pending=0 ref=0 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0x7f9732c71930 pool=<ThreadPool at 0x7f9732cdb8b0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f973528f510 thread_ident=0x7f9736dc5740>>> threadpool=<ThreadPool at 0x7f9732cdb8b0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f973528f510 thread_ident=0x7f9736dc5740>> thread_ident=0x7f9736dc5740>
```

Detailed trace:

```
=================================== FAILURES ===================================
______________________ test_callback_segfault_simple[100] ______________________

database = <rotkehlchen.db.dbhandler.DBHandler object at 0x7f9727b523b0>

    @pytest.mark.parametrize('sql_vm_instructions_cb', [100])
    def test_callback_segfault_simple(database):
        """Test that the async and sqlite progress handler segfault yielding bug does not hit us
        This one is protected against by having the lock inside the callback.
    
        The bug can be summed up as following:
        1. Get in the progress callback
        2. Context switch out of the callback with sleep(0)
        3. Enter critical section, which essentially disables the callback
        4. Write/read more data in the DB
        5. Exit critical section, re-enabling the callback
        6. Context switch back to the progress callback of (1) and exit it.
        7. Segmentation fault.
        """
        # first write some data in the DB to have enough data to read.
        write_events(database, 1000)
    
        # Then start reading from one greenlet and writing from others to create the problem
        a = gevent.spawn(
            read_events,
            database=database,
            limit=100,
        )
        b = gevent.spawn(write_events, database=database, num=200)
        c = gevent.spawn(write_events, database=database, num=200)
>       gevent.joinall([a, b, c])

rotkehlchen/tests/db/test_async.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/gevent/greenlet.py:1065: in gevent._gevent_cgreenlet.joinall
    ???
src/gevent/greenlet.py:1075: in gevent._gevent_cgreenlet.joinall
    ???
src/gevent/_hub_primitives.py:[250](https://github.com/rotki/rotki/actions/runs/7391973994/job/20109783035?pr=7038#step:10:251): in gevent._gevent_c_hub_primitives.wait_on_objects
    ???
src/gevent/_hub_primitives.py:287: in gevent._gevent_c_hub_primitives.wait_on_objects
    ???
src/gevent/_hub_primitives.py:185: in gevent._gevent_c_hub_primitives._WaitIterator.__next__
    ???
src/gevent/_hub_primitives.py:176: in gevent._gevent_c_hub_primitives._WaitIterator.__next__
    ???
src/gevent/_waiter.py:195: in gevent._gevent_c_waiter.MultipleWaiter.get
    ???
src/gevent/_waiter.py:154: in gevent._gevent_c_waiter.Waiter.get
    ???
src/gevent/_greenlet_primitives.py:61: in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:61: in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:65: in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   gevent.exceptions.LoopExit: This operation would block forever
E   	Hub: <Hub '' at 0x7f973528f510 epoll default pending=0 ref=0 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0x7f9732c71930 pool=<ThreadPool at 0x7f9732cdb8b0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f973528f510 thread_ident=0x7f9736dc5740>>> threadpool=<ThreadPool at 0x7f9732cdb8b0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f973528f510 thread_ident=0x7f9736dc5740>> thread_ident=0x7f9736dc5740>
E   	Handles:
E   []

src/gevent/_gevent_c_greenlet_primitives.pxd:35: LoopExit
```

**Comment by LefterisJP** [comment]
We discussed this in the standup and said we should just yolo upgrade since there seems to be no way to debug them via the CI and we do need the new urllib3.

Hope is to debug any problems if/when they happen in develop

**Pull request merged**
