### PR TITLE
Add some more typing for tests

### PR DESCRIPTION
**Pull request by IanMichaelHarper**
I started working on #842 as it was a good first issue, but I after adding typing for a few test files, I quickly realised how tedious of a task it is, and the sheer size of it. I question how valuable it is to spend time working on this, as that time could be better spent working on other issues, which is what I am doing now.

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
> I started working on #842 as it was a good first issue, but I after adding typing for a few test files, I quickly realised how tedious of a task it is, and the sheer size of it. I question how valuable it is to spend time working on this, as that time could be better spent working on other issues, which is what I am doing now.

Hey Ian, yeah it's tedious, which is why this issue has not been picked up by us and done in one go. We typicaly just add more types to tests as we touch them slowly.

Are you in discord? If not please join (https://discord.gg/aGCxHG7). Need DMs open to solve a captcha. We can also chat there for issues to work on if you need any help etc!

**Review by LefterisJP — COMMENTED** [review]
Also @IanMichaelHarper as you can see `make lint` failed. Please check the error here and fix it and force/push to amend the commit: https://github.com/rotki/rotki/actions/runs/4456240359/jobs/7826619707?pr=5784

**Comment by IanMichaelHarper** [comment]
Hey Lefteris, yeah I'm in the discord. I think I did the captcha a while ago. I've been stalking this project for a while but never got around to contributing.

I pushed to fix the isort lint. I thought the PR tests ran automatically. I didn't realise you had to trigger them and I didn't expect you to respond so quick!

**Comment by LefterisJP** [comment]
> Hey Lefteris, yeah I'm in the discord. I think I did the captcha a while ago. I've been stalking this project for a while but never got around to contributing.
> 
> I pushed to fix the isort lint. I thought the PR tests ran automatically. I didn't realise you had to trigger them and I didn't expect you to respond so quick!

Hey @IanMichaelHarper It seems linting is still failing. Can you also squash all commits into one? If not, no problem I can do so before merging.

Run `make lint` locally to make sure all is fine before pushing.

**Comment by IanMichaelHarper** [comment]
> Hey @IanMichaelHarper It seems linting is still failing. Can you also squash all commits into one? If not, no problem I can do so before merging.
> 
> Run `make lint` locally to make sure all is fine before pushing.

Hey Lefteris, sorry about that. I get this weird error for the `ruff` linting even on the develop branch without any of my changes

`ruff rotkehlchen/ package.py tools/
error: TOML parse error at line 126, column 5
    |
126 |     "RSE",
    |     ^^^^^
Unknown rule selector `RSE`

make: *** [Makefile:10: lint] Error 1`

All the other lint commands pass, with a few exceptions where it's still the case on the develop branch. I am working on a windows laptop which I feel may be the reason...

Most of the tests pass but I again get some failures even when I haven't made any changes to what's in `develop`. 

I've linted and tested all my changes to the best of my ability so I think to get a complete lint and test to finish I need it to run via Github Actions.

**Review by LefterisJP — APPROVED** [review]
LGTM. It runs fine on the CI. Something must be off with your dev-machine. I don't know anything about windows, but perhaps hop by our discord's dev-support channel to ask

**Pull request merged**
