### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by kelsos**
Monthly dependency update

### CODE REVIEW

**Comment by LefterisJP** [comment]
@kelsos UI integration tests fail here. Apart from that what else should I check in such a frontend dependency update PR?

**Comment by kelsos** [comment]
I am on it. usually I just do a package and run the packaged app as a smoketest

**Comment by LefterisJP** [comment]
>I am on it. usually I just do a package and run the packaged app as a smoketest

If you already do it then I don't think there is a need to also duplicate effort on my side.

**Review by LefterisJP — APPROVED** [review]
It's all green now so I guess all fine :+1:

**Pull request merged**
