### PR TITLE
Separate options to remember username and password

### LINKED ISSUE #4401: Make it optional to select between the new auto-login remember and the old only username
## Problem Definition

For some users, it is preferable to unlock the account on each usage instead of having an auto-login functionality.

### TODO

- [ ] Allow users to select between the auto-login or only remember username functionality

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4401

image

### CODE REVIEW

**Comment by A2be** [comment]
I was the Discord user who identified #4401.

On the help text in the circled_question_mark adjacent to `Remember Password`:
you should identify that this will leave a method of decrypting the user's encrypted Rotki DB on their local machine, and that it uses open source code from Electron to do it.

In my view, this opens an attack vector for breaking the user's encrypted DB, and they probably ought to have that made clear in the help text.  Just my opinion.  YMMV.

**Comment by LefterisJP** [comment]
> I was the Discord user who identified #4401.
> 
> On the help text in the circled_question_mark adjacent to `Remember Password`: you should identify that this will leave a method of decrypting the user's encrypted Rotki DB on their local machine, and that it uses open source code from Electron to do it.
> 
> In my view, this opens an attack vector for breaking the user's encrypted DB, and they probably ought to have that made clear in the help text. Just my opinion. YMMV.

This is **not an attack vector**. The only way to decrypt this is for your entire OS to be seriously compromised. If that happens then rotki's DB would have been already compromised and you would have had a lot more serious problems than just rotki's data.

**Comment by LefterisJP** [comment]
> > I was the Discord user who identified #4401.
> > On the help text in the circled_question_mark adjacent to `Remember Password`: you should identify that this will leave a method of decrypting the user's encrypted Rotki DB on their local machine, and that it uses open source code from Electron to do it.
> > In my view, this opens an attack vector for breaking the user's encrypted DB, and they probably ought to have that made clear in the help text. Just my opinion. YMMV.
> 
> This is **not an attack vector**. The only way to decrypt this is for your entire OS to be seriously compromised and the keyring of the OS to be exposed. If that happens then rotki's DB would have been already compromised and you would have had a lot more serious problems than just rotki's data.

**Comment by kelsos** [comment]
> > I was the Discord user who identified #4401.
> > On the help text in the circled_question_mark adjacent to `Remember Password`: you should identify that this will leave a method of decrypting the user's encrypted Rotki DB on their local machine, and that it uses open source code from Electron to do it.
> > In my view, this opens an attack vector for breaking the user's encrypted DB, and they probably ought to have that made clear in the help text. Just my opinion. YMMV.
> 
> This is **not an attack vector**. The only way to decrypt this is for your entire OS to be seriously compromised. If that happens then rotki's DB would have been already compromised and you would have had a lot more serious problems than just rotki's data.

It's like @LefterisJP the keychain's purpose on the system is to store encrypted secrets, the whole system's security has to be first compromised and then you already have other problems.

Just to be clear, like I also wrote in discord, if you leave your machine unattended and unlocked then not storing secrets in the keychain won't save you, since anyone with intent and time can compromise the security of your system.

**Review by kelsos — APPROVED** [review]
works great @lukicenturi thank you :smile:

**Pull request merged**
