### PR TITLE
feat(frontend): hide small balances

### LINKED ISSUE #7498: Add functionality/checkbox for "Hide assets <1 USD"
## Abstract

Heavy users normally have a lot of dust tokens in their accounts, from reputable currencies that they don't want to blacklist, such as:
<0.01 BNB
<0.01 WETH
<0.01 stETH
etc.

I'd be nice if there is a checkbox on Rotki, similar to the one found on many exchanges, that says "Hide assets <1 USD", so that one doesn't have 300 tokens under Assets.

## Motivation

Nobody cares at a given point in time that they have 0.01 from a certain asset, so hiding these assets would clean up Rotki interface and make it nicer.

## Nice to have

Ideally make the `hide threshold value` configurable, i.e. some folks might want 1 USD, some might want 10 USD or 100 USD, etc.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #7498

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by kelsos — COMMENTED** [review]
So the setting is unified here, it affects all the balances at once.

When we discussed about it didn't we say something about keeping it separate? @lukicenturi @yabirgb @LefterisJP.

Should there be one setting for all or per category (blockchain/manual/exchange)?

**Comment by yabirgb** [comment]
We mentioned irc that it makes sense to have the same value for all of them and that is a value that affects to the table so it sshould be near it to modify it easily

**Comment by kelsos** [comment]
> We mentioned irc that it makes sense to have the same value for all of them and that is a value that affects to the table so it sshould be near it to modify it easily

OK then I am gonna merged it as it is and we can tweak later

**Review by kelsos — APPROVED** [review]
lgtm @lukicenturi, can you please also add a change log entry before merging?

**Comment by kelsos** [comment]
I am gonna adjust the .ts thing and add the changelog so I can rebase the utils PR on top in case there need to be some adjustments

**Pull request merged**
