### PR TITLE
Introduces address import from MetaMask

### LINKED ISSUE #1122: Use metamask to easily import accounts on rotki
## Abstract

Enable a way to use metamask to import account addresses to rotki

> If your desktop app could briefly host a page and open the user’s browser to it, you could ask the user selects all the accounts they want to share.
Caveat: at the moment they will need to then select each of those accounts, for compat reasons. Adding a “expose all at once” soon.
https://twitter.com/danfinlay/status/1279112773234917376?s=20

## Motivation

It makes it easier for users to import their accounts to rotki

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1122

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Tentative approval. It seems to work. But we need some changes.


## Change location of metamask import button


It makes no sense to have the import button right under the other "+" button. It's confusing and looks bad. I would add it inside the drawer of "add new blockchain accounts. If Ethereum account is selected for addition then show an extra buttton of sorts that will be the metamask logo along with some arrow insinuating importing. Make it fit into the current addition menu but make it big enough to standout as an alternative choice of importing.




 Functionality of the buttons remains the same.

## Adding accounts one by one

I know you are super happy we can add N accounts at once, but it's actually slow. I had 4 metamask accounts and it took some time until something appeared. Instead what I think would be much better from a UX perspective is create 4 (N in the generic case) tasks to add each address individually. When one task completes already some results should appear, right? So that would look much better.

### Consistent terminology

I think I saw various verbs used in the PR for importing. Adding, importing and tracking. Try to be a bit more consistent and use import, not add for metamask since we are importing the addresses from there. And track only where appropriate. For example we are importing addresses in Rotki to track them.

### Make metamask see our logo




I am not sure if this is possible, but metamask shows us as "R" in a circle in the 3 menus I had to click through. Is it possible to show our logo there? If you don't know how we can ask Dan.

**Comment by kelsos** [comment]
> Tentative approval. It seems to work. But we need some changes.
> ## Change location of metamask import button
> 
> 
> 
> It makes no sense to have the import button right under the other "+" button. It's confusing and looks bad. I would add it inside the drawer of "add new blockchain accounts. If Ethereum account is selected for addition then show an extra buttton of sorts that will be the metamask logo along with some arrow insinuating importing. Make it fit into the current addition menu but make it big enough to standout as an alternative choice of importing.
> 
> 
> 
> Functionality of the buttons remains the same.

@LefterisJP 
I was thinking the following approach if we want to integrate it properly to the dialog.

Add a dropdown-select to select mode:
 - Single Address (default)
 - Multiple Addresses (next PR)
 - Metamask Import (current PR)

When in metamask import mode you can't add anything to the address field but you can still specify label/tags (that apply to all the accounts.

Pressing the Add (whatever we call it button) will open the start the metamask flow.

> ## Adding accounts one by one
> 
> I know you are super happy we can add N accounts at once, but it's actually slow. I had 4 metamask accounts and it took some time until something appeared. Instead what I think would be much better from a UX perspective is create 4 (N in the generic case) tasks to add each address individually. When one task completes already some results should appear, right? So that would look much better.

While not impossible it requires changes. The question is what happens to the backend when adding a few accounts in parallel. We currently block the account addition when loading or adding.

> ### Consistent terminology
> I think I saw various verbs used in the PR for importing. Adding, importing and tracking. Try to be a bit more consistent and use import, not add for metamask since we are importing the addresses from there. And track only where appropriate. For example we are importing addresses in Rotki to track them.

Ok that sounds reasonable

> ### Make metamask see our logo
> 
> 
> 
> I am not sure if this is possible, but metamask shows us as "R" in a circle in the 3 menus I had to click through. Is it possible to show our logo there? If you don't know how we can ask Dan.

The icon is pulled from the pages favicon.ico. Up to this point, we didn't have one, I added a favicon in the PR for unidirectional sync let's merge that and see how it goes. If any more changes are required I will do them in a new PR but it didn't make sense to duplicate work across PRs without checking first.

**Comment by kelsos** [comment]
Note about the icon, but we can handle it after merging the db pr that has the favicon changes. https://docs.metamask.io/guide/defining-your-icon.html

**Review by LefterisJP — APPROVED** [review]
LGTM. The failing test in the backend is due to a long running account having moved their LEND (probably to AAVE). Need to modify that test. Will do so in another PR.

**Pull request merged**
