### PR TITLE
Perform npm version sanity check at package.sh

### PR DESCRIPTION
**Pull request by LefterisJP**
[skip ci]

### CODE REVIEW

**Comment by kelsos** [comment]
@LefterisJP I also have to include this change on my PR

**Comment by LefterisJP** [comment]
@kelsos yes I guess. I will need some more changes in packaging since it does not work properly at the moment.

**Comment by kelsos** [comment]
@LefterisJP just ping when just so that I don't miss them, to see if they make sense for me to include them in the new packaging script. Also if you find some time please have a look at the `vue-rewrite` PR packaging. I especially need macOS, but also check how things work for you on windows/linux

**Comment by LefterisJP** [comment]
@kelsos sure will do. The plan at the moment is to make a normal release before vue.js. Once that is done I will test vue in macos.

**Pull request merged**
