### PR TITLE
Introduces liabilities table in the frontend

### PR DESCRIPTION
**Pull request by kelsos**
@LefterisJP this only adds liabilities on the dashboard. We are fine with that initially right?

### CODE REVIEW

**Comment by LefterisJP** [comment]
@kelsos Please also add them in the per account tables in the blockchain & accounts balances. The information is already returned by the API.

**Review by LefterisJP — COMMENTED** [review]
Hey Kelsos, thanks. There is some changes needed. Check the screenshots below for an example of what needs to change:




### Rename first table

balances per asset -> Assets

I think we should be consistent in the naming of the tables in the dashboard. Assets - Liabilities

### Net worth is wrong

The net worth is not calculated correctly. The net worth is Total assets - Total liabilities.

So in the case above we should have 363883.19-18315.29 = 345567.9 EUR of networth

- The correct networth should be shown in the graph / big total numbers
- The percentage of each asset compared to the networth should be in the networth (net worth always means minus liabilities) That means that the percentages may not add up correctly but it's fine.

### The symbol on the dashboard networth graph

That's not related to this PR but I have been saying it for some time now. Please make the EUR sign in the dashboard graph a normal size. It looks bad right now.

----

The liabilities per blockchain account looks fine. Simple for now, but did not see anything wrong. Thanks.

**Comment by kelsos** [comment]
> ### Net worth is wrong
> 
> The net worth is not calculated correctly. The net worth is Total assets - Total liabilities.
> 
> So in the case above we should have 363883.19-18315.29 = 345567.9 EUR of networth
> 
>     * The correct networth should be shown in the graph / big total numbers

Total should be easy. But the graph not really. I am assuming that the liabilities are not calculated for past events so we don't have this information. Removing the liabilities from the latest value would always show a loss in the latest day. Removing it from each value would make the graph completely inaccurate. How would you like to approach this? Maybe it would make sense to start keeping the liabilities snapshots and start showing a second line instead?

>     * The percentage of each asset compared to the networth should be in the networth (net worth always means minus liabilities) That means that the percentages may not add up correctly but it's fine.
> 


> ### The symbol on the dashboard networth graph
> 
> That's not related to this PR but I have been saying it for some time now. Please make the EUR sign in the dashboard graph a normal size. It looks bad right now.

I have 3 todos in the kanban. I will do at least the two of them in a new PR.

**Review by LefterisJP — APPROVED** [review]
Looks good to me now from the test I performed.

**Pull request merged**
