### PR TITLE
Deps update

### PR DESCRIPTION
**Pull request by LefterisJP**

### CODE REVIEW

**Review by PabloCastellano — COMMENTED** [review]
From the [changelog](https://marshmallow.readthedocs.io/en/stable/changelog.html changelog):

```
Bug fixes:

Fix typing in Field._serialize signature (#2046).
```

So it looks like you need to update the _serialize method signatures too. See https://github.com/marshmallow-code/marshmallow/pull/2046.

Question: should you also update tools/data_faker/requirements.txt ?

**Comment by LefterisJP** [comment]
> From the [changelog](https://marshmallow.readthedocs.io/en/stable/changelog.html):
> 
> ```
> Bug fixes:
> 
> Fix typing in Field._serialize signature (#2046).
> ```
> 
> So it looks like you need to update the _serialize method signatures too. See [marshmallow-code/marshmallow#2046](https://github.com/marshmallow-code/marshmallow/pull/2046).
> 
> Question: should you also update tools/data_faker/requirements.txt ?

what's weird it passes locally for some reason.

**Comment by LefterisJP** [comment]
Also @PabloCastellano 

> Question: should you also update tools/data_faker/requirements.txt ?

That is a kind of dead thing. I will just remove it. `data_faker` was an idea to fake data for testing but has just not been used in ages and would probably need heavy rewriting and maintaining

**Review by PabloCastellano — APPROVED** [review]
lgtm

**Pull request merged**
