### PR TITLE
fix: improve report page UX

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
image

Do you think we can make this an icon button and get rid of the text? maybe show it only on a tooltip?

**Comment by kelsos** [comment]
Other than the comment above PR looks great to me.

**Comment by lukicenturi** [comment]
> image
> 
> Do you think we can make this an icon button and get rid of the text? maybe show it only on a tooltip?

**Review by kelsos — APPROVED** [review]
lgtm thanks

**Pull request merged**
