### PR TITLE
Finalizes move to setup script, removes unneeded imports (due to auto-import)

### PR DESCRIPTION
**Pull request by kelsos**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

Depends on #5044

### CODE REVIEW

**Comment by lukicenturi** [comment]
There is some part that we use `get()` inside `template`. Last time I check, it won't work with auto import. Can you confirm it? @kelsos

**Comment by kelsos** [comment]
> There are some part that we use `get()` inside `template`. Last time I check, it won't work with auto import. Can you confirm it? @kelsos

It doesn't seem to work indeed. I think I changed one get but probably in the next PR.
Did you notice one in this PR?

**Comment by lukicenturi** [comment]
> > There are some part that we use `get()` inside `template`. Last time I check, it won't work with auto import. Can you confirm it? @kelsos
> 
> It doesn't seem to work indeed. I think I changed one get but probably in the next PR. Did you notice one in this PR?
> 
> --edit-- Ok this was the next PR 😛

I don't find anything, so we can merge it then  😛

**Review by lukicenturi — APPROVED** [review]

**Comment by kelsos** [comment]
One thing to keep in mind, if we have to use `get` or `.value` in the template, we probably need to rethink the approach to the component. 

for example a get(whatever(item.address)) would probably be better if item.address was the prop of the child component and we did 

```typescript
const { address } = toRefs(props);
const computedProp = whatever(address);
```

and use the computedProp directly in the template so that we benefit from the automatic de-referencing.

**Pull request merged**
