### PR TITLE
Takes new app users to the account creation screen instead of the login

### LINKED ISSUE #3500: Take into account true fee used in kraken trades (such as KFEE or non quote asset)
## Abstract

At the moment is possible to have trade fees paid in KFEE but in the API it appears as paid with the quote asset. 

## Specification

To solve this issue we should compare every trade agains the ledger entries from kraken and check if KFEE was used

### LINKED ISSUE #3840: Take users to account creation when installing the application for the first time
## Problem Definition

A number of users tend to be confused and attempt to log in to the application with the website password. To make it clear that a local account is needed when there is not account the user should be taken directly to the create account page

### PR DESCRIPTION
**Pull request by kelsos**
Closes #3840

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
To test it just move the data dir and start the app: 

`mv ~/.local/share/rotki/data/ ~/.local/share/rotki/data.bak` after testing move `data.bak` back to `data`

**Comment by kelsos** [comment]
it seems that I used the wrong issue as the branch name :disappointed:

**Review by yabirgb — APPROVED** [review]
Looks got to me. LGTM

**Comment by LefterisJP** [comment]
I just merge since you all seem to like and approve it. Will provide feedback if I see something I don't like during release testing.

**Pull request merged**
