### PR TITLE
removed some lines to enable strict typing

### LINKED ISSUE #842: Enable strict typing for all tests
## Problem Definition

For backend tests we have an exception in setup.cfg here:
https://github.com/rotki/rotki/blob/b07063d35164f59b438a7385b3c72955a90e71d9/setup.cfg#L28-L32

We don't have strict typing check for all tests.

## Task

- Remove the lines shown above
- Properly type everything in tests so that linting passes again

### PR DESCRIPTION
**Pull request by yashnirmal**
Closes #842 

## Checklist
The PR modified the setup.cfg file

### CODE REVIEW

**Comment by yabirgb** [comment]
@yashnirmal In addition to remove those lines properly typing all tests is also needed

**Review by LefterisJP — COMMENTED** [review]
As @yabirgb mentioned this is not the solution. One would need to actually type all tests properly to solve the issue

**Comment by LefterisJP** [comment]
I am not sure if you intend to continue work on this PR. If not tell us to close it.

**Comment by yashnirmal** [comment]
> I am not sure if you intend to continue work on this PR. If not tell us to close it.

Not I am not working on it

**Pull request closed without merging**
