### PR TITLE
Adds xpub key type support to account form

### LINKED ISSUE #1558: Cannot delete an XPUB key that has no coins
## Problem Definition

After adding an XPUB key that has balance on its derived address, I can not delete that XPUB from my database anymore. I assume this is because the XPUB address does not show up in the list BTC per account balances since there's no balance. 

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v geth && geth version
command -v parity && parity --version
command -v rotki && rotki version
[ -d .git ] && git rev-parse HEAD
```

Darwin ChocoBookPro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

rotki is version 18.1

### LINKED ISSUE #1562: Properly specify and support the different types of Bitcoin xPubs (add full P2SH-P2WPKH and WPKH support.
## Abstract

With v1.8.1 we added the first bitcoin xPub support in Rotki. A user can provide an xpub starting with the xpub prefix and rotki will assume it's a legacy xpub. `m/44'/0'/x'`  => P2PKH`. If the prefix starts with zpub it will assume it's a native segwit `m/84/0'/x'  => WPKH` type of xpub.

But this is missing some functionality. The `zpub` prefix is electrum specific and not bitcoin standard. The xpub may still start with xpub and still be of WPKH type.

Finally we are missing support for segwit xpubs, `m/49'/0'/x'  => P2SH-P2WPKH`. In electrum they are prefixed with `ypub`.

## Task

At xpub input allow the user to specify the type of xpub.

- `P2PKH` (legacy) with account path `m/44'/0'/x'
- `P2SH-P2WPKH` (segwit) with account path `m/49'/0'/x'`
- `WPKH` (native segwit) with account path `m/84/0'/x`'

Also allow auto completion of the type if the xpub is electrum style. If the user given xpub starts with:

- `xpub` -> `P2PKH`
- `ypub` -> `P2SH-P2WPKH`
- `zpub` -> `WPKH`

In the frontend there will be a choice of xpub type, but in the end what is sent to the backend (so we avoid extra fields) is the xpub with the proper prefix. `xpub`, `ypub`, `zpub`. The backend will read the prefix and treat the xpub accordingly. When returning information on an xpub we coudl add an extra field for the type. We could also just use the xpub prefix for this. @kelsos What do you think? (can also respond in discord)

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1562 
Closes #1558

### CODE REVIEW

**Comment by LefterisJP** [comment]
@kelsos this is a draft. I should not try it yet, right? First should merge https://github.com/rotki/rotki/pull/1623 ?

**Comment by kelsos** [comment]
@LefterisJP this is a draft and requires changes from me to accomodate #1623 yes

**Review by LefterisJP — COMMENTED** [review]
Seems to work, and the type is even autoselected when giving xpub with prefix.

But when adding an xpubs which doesn't derive any accounts they don't seem to appear in the list? Shouldn't they? We had this issue before.

Is that not fixed yet?

**Comment by kelsos** [comment]
> Seems to work, and the type is even autoselected when giving xpub with prefix.
> 
> But when adding an xpubs which doesn't derive any accounts they don't seem to appear in the list? Shouldn't they? We had this issue before.
> 
> Is that not fixed yet?

I just tested that before and it worked, can you send such an xpub? to verify again

**Comment by LefterisJP** [comment]
@kelsos this is why I could not find the xpub: https://github.com/rotki/rotki/issues/1627

**Review by LefterisJP — APPROVED** [review]
Apart from the pagination issue everything else seems to work fine. So approving and merging since we have an issue for that one.

**Pull request merged**
