### PR TITLE
feat: update docker warning docs

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
There is typos in the warning @lukicenturi. Where is this text from? I don't see it in the PR.

**Comment by lukicenturi** [comment]
> There is typos in the warning @lukicenturi. Where is this text from? I don't see it in the PR.

The frontend warning? It is in frontend translation file

**Comment by LefterisJP** [comment]
> > There is typos in the warning @lukicenturi. Where is this text from? I don't see it in the PR.
> 
> The frontend warning? It is in frontend translation file

Okay so then change it:

```diff
-You are running rotki in docker. Make sure you have read our {0} and understand the potential risk that may happens by running rotki this way.
+You are running rotki in docker. Make sure you have read our {0} and understand the potential risk that running rotki in this way entails.
```

and also change the screenshot.

**Review by LefterisJP — APPROVED** [review]
lgtm

**Pull request merged**
