### PR TITLE
fix: adjust the report overview layout

### PR DESCRIPTION
**Pull request by kelsos**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
Screenshot from 2023-11-03 15-48-42

After the changes it will look like this

**Comment by lukicenturi** [comment]
> Screenshot from 2023-11-03 15-48-42
> 
> After the changes it will look like this

image

Did you miss the border, or removed it on purpose? 😛

**Comment by kelsos** [comment]
> > Screenshot from 2023-11-03 15-48-42
> > After the changes it will look like this
> 
> image
> 
> Did you miss the border, or removed it on purpose? 😛

I empty looked just fine :smile: I fixed it and also I am hiding the empty row when there are data.

**Review by lukicenturi — APPROVED** [review]
LGTM!

**Pull request merged**
