### PR TITLE
Updates bug report template with information

### LINKED ISSUE #2231: Explain how to add activate debug logs in the bug template.
Do it

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2231

### CODE REVIEW

**Comment by LefterisJP** [comment]
Ah thanks @kelsos. Would it also not make sense to send a link to the docs where there is also a screenshot of this? https://rotki.readthedocs.io/en/latest/contribute.html#bug-reporting

**Comment by kelsos** [comment]
@LefterisJP done

**Comment by LefterisJP** [comment]
Hah interesting, this is a branch in the upstream. So we show it in our dev notifications.

**Review by LefterisJP — APPROVED** [review]

**Comment by kelsos** [comment]
Yes I did it originally from the github web editor :P

**Pull request merged**
