### PR TITLE
fix: scramble validator index and block number in human readable way

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
@lukicenturi can you add a couple of unit tests for `scramble.ts`?

**Comment by kelsos** [comment]
image
That looks wrong @lukicenturi these are probably really low validator indexes

**Comment by lukicenturi** [comment]
Updated

**Review by kelsos — APPROVED** [review]
lgtm @lukicenturi now it is fine

**Pull request merged**
