### PR TITLE
Fixes FTX exchange forgetting subaccount

### LINKED ISSUE #3998: FTX subaccount forgets subaccount name
## Problem Definition

Once a subaccount is configured going back to editing the subaccount shows the subaccount name as blank. The side effect is that queries to the subaccount endpoint fail.

### System Description

Operating system: Linux, Docker
Rotki version: 1.23.2

### PR DESCRIPTION
**Pull request by yabirgb**
The reason was that the code for the exchange was expecting the key `ftx_subaccount_name`
but the database was returning this value as `ftx_subaccount` making the initialization
for the subaccount field fail.

The solution applied was to use `ftx_subaccount` everywhere to make the name consistent
around the code.

Closes #3998

### CODE REVIEW

**Comment by yabirgb** [comment]
The backend test failed due to a 503 error from etherscan and the e2e got stuck adding an ethereum account that seems to be a problem querying etherscan too.

**Review by LefterisJP — APPROVED** [review]
oh lol. LGTM.

**Review by LefterisJP — COMMENTED** [review]
Hm @yabirgb did you check why the e2e tests failed though?

**Comment by yabirgb** [comment]
> Hm @yabirgb did you check why the e2e tests failed though?

Tried the same again locally and seems to work. Seems like a query stuck due to a slow response

**Comment by LefterisJP** [comment]
> > Hm @yabirgb did you check why the e2e tests failed though?
> 
> Tried the same again locally and seems to work. Seems like a query stuck due to a slow response

okay will believe you :)

**Pull request merged**
