### PR TITLE
Replace zerorpc server with REST API webserver

### LINKED ISSUE #404: Replace zerorpc with normal HTTP Rest API
## Problem Definition

Zerorpc is a pain in the ass the way Rotkehlchen has evolved.

1. We need to have a hack in long running API calls to make sure that gevent does at least 1 context switch every 10 seconds to avoid the dreaded heartbeat error: https://github.com/rotkehlchenio/rotkehlchen/blob/605d56edf46d20d090e4d3dad94becd88c8749a5/rotkehlchen/accounting/accountant.py#L397

2. The module used both in python but more importantly in node for zerorpc is outdated and not maintained. Upgrading to a new electron version becomes harder and harder since the package needs to be forked and maintained by me to do so.

3. Dependency to ZeroMQ and ZeroRPC goes away

4. Some bugs that pop up are suspected to be due to the way zerorpc handles communication between backend and client.

## Task

1. Remove zerorpc server from the backend. Replace with a normal rest HTTP API server.

2. Remove zerorpc client from the frontend side. Replace with simple RPC queries.

### PR DESCRIPTION
**Pull request by LefterisJP**
This PR closes #404 

It also does the following:

- Completely remove ZeroRPC and all its python and npm dependencies
- Consolidates the API by restructuring some calls, and removing others. For example:
    * `set_main_currency` call is removed since the same can be achieved by `set_settings({'main_currency': 'XXX'})`
    * Almost all calls are now wrapped in the `{'result': XXX, 'message': 'may have error message here'}` object for consistency
- Adds a new documentation page for the REST API

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hey @kelsos this is the WIP/Draft PR for replacing zerorpc with a normal webserver.

For the `rotkehlchen_service.ts` how can all the `client.invoke()` calls be changed to be http queries (GET, PUT, DELETE e.t.c.) on endpoints ?https://github.com/rotkehlchenio/rotkehlchen/pull/526/files#diff-5d937a0f461d44838215b9664e4ab53bR34

Also got any other remarks or comments on this ongoing work?

**Comment by kelsos** [comment]
I will check as soon as I am back to Berlin. Is that OK?

**Comment by LefterisJP** [comment]
The default branch for development of big features has been changed to develop. I updated the PR's base branch to reflect this.

**Comment by LefterisJP** [comment]
Just rebased on top of develop and all the vue.js work.

**Comment by LefterisJP** [comment]
Merging this one and will rebase #573 on top of develop.

**Pull request merged**
