### PR TITLE
Adds frontend changes for ftx support

### PR DESCRIPTION
**Pull request by kelsos**
I remember it requiring just a bit more effort.
But checking the kucoin PR without the changes that were one-off, this is what remains.

### CODE REVIEW

**Comment by LefterisJP** [comment]
Now that https://github.com/rotki/rotki/pull/2662 is merged, we need to rebase this one on top of develop and test with the frontend

**Comment by LefterisJP** [comment]
Also this one should add the changelog + close the issue

**Comment by yabirgb** [comment]
I renamed the FTX class in the backend so the frontend can properly query FTX as it does with the other exchanges. Tested that it works but the e2e seems to fail. I'm not familiar with this tests so I don't know exactly what is wrong or if they need to be updated. 

Also included a requested change in the other PR to change one `msg` line. Changelog was updated in the other PR

**Comment by LefterisJP** [comment]
> e2e seems to fail

Did you also rebase on develop?

**Comment by LefterisJP** [comment]
The backend test failure seems to be a gemini sandbox hiccup?

**Comment by yabirgb** [comment]
Yes I rebased on develop. The backend error seems to be something I made since is not happening on develop. I'm trying to figure out what it is

**Comment by LefterisJP** [comment]
> Yes I rebased on develop. The backend error seems to be something I made since is not happening on develop. I'm trying to figure out what it is

I am not sure it is. I have seen it happen in the past. Gemini sandbox can return a stupid error like this.

**Comment by yabirgb** [comment]
@LefterisJP I already found what it was. Before I was not properly adding FTX to the known exchanges and this issue didn't raise since it wasn't tested. I ammed the commit adding the missing entry for FTX in the expected output

**Comment by LefterisJP** [comment]
> @LefterisJP I already found what it was. Before I was not properly adding FTX to the known exchanges and this issue didn't raise since it wasn't tested. I amend the commit adding the missing entry for FTX in the expected output

I see. Nice! That test has pretty confusing error messages now that I look at it.

**Pull request merged**
