### PR TITLE
Introduces a back button when viewing the asset details

### LINKED ISSUE #2515: Back button needed on some screens (asset detail)
## Abstract

There are some screens that can be reached from multiple places e.g. asset detail.

I think it would be useful to include a small back button when in these screens.

## Motivation

Because it feels like it's missing and there's no back button.

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2515

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
check frontend fails here

**Comment by kelsos** [comment]
> check frontend fails here
small typing thing that caused a build error, the functionality is already there

**Review by LefterisJP — APPROVED** [review]
LGTM. So what was the reason this can't go everywhere again?

**Comment by kelsos** [comment]
The only way I could make it work was by disabling the navigation if the history stack was either empty or if the user is not at the dashboard or root. The problem is that it is not possible to know where in the history stack you currently are, so there is a huge chance that you don't see a back button but you can actually go back with e.g. the mouse buttons. 

We can think about enabling it in the future, but it will be slightly inconsistent between the UI button and mouse buttons.

**Pull request merged**
