### PR TITLE
Adds frontend support for non fungible asset balances/price editing

### LINKED ISSUE #1097: Support ethereum NFTs
## Abstract

There is a big market for NFTs in ethereum and an untapped need to track and account for them.

There is crypto collectibles marketplaces like https://opensea.io/

We should be able to account for them

## Task

Figure out a way to autodetect NFTs owned by an ethereum address. A good start would be ERC721 tokens. 

For ERC721 tokens etherscan offers an events endpoint to get a list of ERC721 token transactions per account: https://etherscan.io/apis#accounts

We could use that to see what ERC721 a user has and show their balance after processing them all.

There is also the ERC1155 standard for NFTs

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1097

## Checklist

- [x] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Thanks. So some comments.

### At non fungible balances editing show all NFTs

It seems that NFTs that have no price are not returned there. You need to take all nfts from the nft endpoint call (same one you show in gallery).

This is cause you want to be able to add custom price to things we can't auto-detect the price for yet.

At the 

### Add also given asset price in dashboard



The NFT balances returns also the asset price and the USD price. If there is an asset price, like say denominated in ETH it would be nice to show it.

Same should probably also be shown when there is a custom price at the NFT editing page:



## Edit changelog

I think it would make sense to also edit the changelog here since we are adding much cooler functionailty:

`* :feature:`1097` Users will now be able to view their NFTs.`

Mention we can also now track NFT prices, show it in the dashoard and take it into account in the user's networth.

### Update docs and add screenshots

Once all is done if you can also please update docs and add screenshots.

**Review by LefterisJP — COMMENTED** [review]
So some more things.

### ignore_cache

It still seems as if refreshing the nfts in the gallery and in the nft edit section does not add the ignore cache argument. It would make sense to add it as this would fix many problems

### Use the given price in the gallery

In the gallery the price returned by the nfts endpoint is always used. Could you try to  combine the 2 endpoints info and if there is a manual price given use that instead?

The reason it's not already returned by the nfts endpoint is because that returns the price that opensea detects. Not sure if I should mix the endpoints and add more logic underneath and do it all in the backend instead. What do you think? Open to suggestions here.

### Docs as last thing

screenshots + docs don't forget after we done :smile:

**Comment by kelsos** [comment]
> So some more things.
> 
> ### ignore_cache
> It still seems as if refreshing the nfts in the gallery and in the nft edit section does not add the ignore cache argument. It would make sense to add it as this would fix many problems

Damn a Vuex with proper typescript support would really help. I did some changes and then forgot to modify the caller.

> ### Use the given price in the gallery
> In the gallery the price returned by the nfts endpoint is always used. Could you try to combine the 2 endpoints info and if there is a manual price given use that instead?

Let me see what I can do, it shouldn't be overly complicated.

> The reason it's not already returned by the nfts endpoint is because that returns the price that opensea detects. Not sure if I should mix the endpoints and add more logic underneath and do it all in the backend instead. What do you think? Open to suggestions here.
> 
> ### Docs as last thing
> screenshots + docs don't forget after we done

Yes after we lock on the changes I will do it.

**Review by LefterisJP — APPROVED** [review]
LGTM. Whatever other adjustments we need we can do later.

**Pull request merged**
