### PR TITLE
Ignore asset from overview page

### LINKED ISSUE #4249: Ignore an asset from the asset overview page
## Abstract

It would be nice to be able to ignore an asset immediately from the asset overview page.

If you see an asset that is a spam/fake asset it would be great to be able to remove it from the app with 2 clicks. One in the dashboard asset taking you to the asset overview (implemented), and another on an ignore asset button there.

What's more in an asset's page we should be able to see if it's ignored or not.

## Specification

Implement it in the frontend. It's frontend only.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4249

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by LefterisJP — APPROVED** [review]
Looks fine functionality-wise. Could you also do the thing all frontend needs to be doing? Update user guide and its screenshots to reflect the changes?

**Comment by lukicenturi** [comment]
> Looks fine functionality-wise. Could you also do the thing all frontend needs to be doing? Update user guide and its screenshots to reflect the changes?

Usage guide added

**Review by kelsos — APPROVED** [review]
lgtm

**Review by LefterisJP — APPROVED** [review]
LGTM

**Pull request merged**
