### PR TITLE
Add French translations 🇫🇷

### PR DESCRIPTION
**Pull request by anthony-robin**
This PR enabled french 🇫🇷 translations to rotki.

Content has been translated using ChatGPT to save time. Then, I made a manual quick check to ensure translations keep a correct meaning. Some translations might not be accurate as I don't have specific context so french speaker friends, do not hesitate to suggest me improvments if you detect some weird translations 😄

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hey @anthony-robin! Thanks. If you have any questions about this or need help feel free to chat with us in discord: https://discord.rotki.com/

**Comment by anthony-robin** [comment]
Hi @LefterisJP, 

I just pushed the latest french 🇫🇷 translations to the PR thanks to ChatGPT and Mistral AI (very helpful to translate the huge file) 🎉 
As mentioned, some translations might have incorrect meaning due to a lack of context sometime and my misreading about Defi and some blockchains protocols. Sure it will be enough and still understandable for most of the file !

I also have a question: how do you handle synchronization (add/edit/removal) of i18n keys accross supported languages ? Do you use some external tool such as `crowdin` that friendly display untranslated content from main source file to other languages ?

Let me know if you have any more requests or if you want me to squash commits.
Thank you :)

**Review by LefterisJP — COMMENTED** [review]
Hey @anthony-robin ! Thank you!

> I also have a question: how do you handle synchronization (add/edit/removal) of i18n keys accross supported languages ? Do you use some external tool such as crowdin that friendly display untranslated content from main source file to other languages ?

We have not really put too much thought into internationalization yet. I am not very familiar with such tools but I have heard they exist.

Are they easy to use and interface with the way we do translations? Would we need any changes in the way we do things?

The way the logic works is if a key is missing it always falls back to the default, English.

> Let me know if you have any more requests or if you want me to squash commits.

Hey thanks! Yes it would be nice if you could squash the commits as we want to keep consistent commits for tasks that do 1 thing.

**Comment by LefterisJP** [comment]
I can also squash and merge, so no need to do it yourself.

**Review by LefterisJP — APPROVED** [review]
LGTM

**Comment by anthony-robin** [comment]
I squashed my commits, thank you :)

For crowdin, I used it while contributing to the [Amethyst](https://github.com/vitorpamplona/amethyst) Android app.
Service is linked to the Github repository and changes are pulled from crowdin (or pushed from Github) using the `Crowdin GH Action` to keep synchronized version.

Crowdin interface highlight untranslated keys so it is very easy to find out what has been added to the main locale to be reflected to all other supported language, then contributors only have to translate the content.

I'm not sure if this tool can work for you as you request contributors to sign a licence agrement so this need to be figured out.

**Comment by LefterisJP** [comment]
Hey @anthony-robin it seems there is some lint failures on the file:

```
Error:   1043:7  error  unused 'address_book.address_name_priority_setting.data_name' key  @intlify/vue-i18n/no-unused-keys
Error:   2757:9  error  "whitelist_ title" is not snake_case                               @intlify/vue-i18n/key-format-style
Error:   2757:9  error  unused 'ignore.whitelist.failed["whitelist_ title"]' key           @intlify/vue-i18n/no-unused-keys
```

**Comment by LefterisJP** [comment]
I can probably try to fix them for you if you want @anthony-robin

**Comment by anthony-robin** [comment]
Good catch for failures :)

> I can probably try to fix them for you if you want @anthony-robin

Don't worry, I will fix it in the beginning of afternoon ;)

**Comment by anthony-robin** [comment]
Fixed ! 🎉

**Comment by LefterisJP** [comment]
> Fixed ! 🎉

Perfect. Thanks @anthony-robin. Can you add a changelog entry too? Since this is a user facing change. Essentially at changelog.rst add this at the top:

```
* :feature:`-` rotki is now available in French
```

**Comment by anthony-robin** [comment]
Changelog entry added 👍 

Did you plan to integrate this PR into the next minor or bugfix version ?

**Comment by LefterisJP** [comment]
> Did you plan to integrate this PR into the next minor or bugfix version ?

This will go to next minor version. We only release minor (which for us are our feature releases) or patch versions (our bugfixes releases).

**Review by LefterisJP — APPROVED** [review]
LGTM

**Pull request merged**
