### PR TITLE
Adds frontend support for yearn v2

### LINKED ISSUE #1666: Support yearn finance v2 vaults
## Abstract

Yearn finance current (v1) vaults are fully supported by Rotki. We need to also add support for the upcoming v2 vaults. That is both current balance tracking support and also historical profits and events history for premium users.

Mildly related: https://github.com/rotki/rotki/issues/1655

## Motivation

Yearn is one of the most core protocols in DeFi and their system has to be supported by Rotki. V2 vaults are what everyone will be switching to once they are officially published (~2 weeks from now).

## Specification

Offer the exact same functionality we have for yearn v1 vaults also for v2 vaults.

This is the interface in python from looking at their source: https://github.com/iearn-finance/yearn-exporter/blob/master/yearn/vaults_v2.py#L25-L40

Vaults v2 registry: https://twitter.com/vasa_develop/status/1351154987368390658

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1666

### CODE REVIEW

**Comment by kelsos** [comment]
Todo
- [ ] Adds an entry to the defi overview
- [ ] Fix the dropdown when in deposits

**Comment by yabirgb** [comment]
In the section to delete information from a module the name is not correctly written

**Comment by yabirgb** [comment]
Having only yearn v2 activated show this message in the defi section

image

**Comment by yabirgb** [comment]
Don't know if this is something of this PR but the icons seems to be at different heights 
image

**Comment by kelsos** [comment]
> Don't know if this is something of this PR but the icons seems to be at different heights
> image

I didn't touch the icons in this PR so if there is something wrong there was something wrong before. 
And I am under the impression that this component is part of the premium components

**Comment by LefterisJP** [comment]
> > Don't know if this is something of this PR but the icons seems to be at different heights
> > image
> 
> I didn't touch the icons in this PR so if there is something wrong there was something wrong before.
> And I am under the impression that this component is part of the premium components

But if the icons are not aligned then we need to fix this. If this is indeed the case make another issue as this is probably unrelated to this PR.

**Comment by kelsos** [comment]
> > > Don't know if this is something of this PR but the icons seems to be at different heights
> > > image
> > 
> > 
> > I didn't touch the icons in this PR so if there is something wrong there was something wrong before.
> > And I am under the impression that this component is part of the premium components
> 
> But if the icons are not aligned then we need to fix this. If this is indeed the case make another issue as this is probably unrelated to this PR.

I can also fix that here, but it needs a bit of research since practically only one of them is an actual icon, the other is a rounded CSS border with some text inside, and modifying the height of the existing element breaks the round shape so I probably need top wrap it in another element..

**Comment by kelsos** [comment]
> > > > Don't know if this is something of this PR but the icons seems to be at different heights
> > > > image
> > > 
> > > 
> > > I didn't touch the icons in this PR so if there is something wrong there was something wrong before.
> > > And I am under the impression that this component is part of the premium components
> > 
> > 
> > But if the icons are not aligned then we need to fix this. If this is indeed the case make another issue as this is probably unrelated to this PR.
> 
> I can also fix that here, but it needs a bit of research since practically only one of them is an actual icon, the other is a rounded CSS border with some text inside, and modifying the height of the existing element breaks the round shape so I probably need top wrap it in another element..

It seems that it was way easier than I originally thought, I just had to vertically center in the parent component...

**Comment by yabirgb** [comment]
> It seems that it was way easier than I originally thought, I just had to vertically center in the parent component...

Classical me with css

**Comment by yabirgb** [comment]
In the console I get and in fact now I get duplicate entries. This seems to happen to me with yearn v1 and v2 activated and an account with information only in v2. This happened after the trying the previous status of the PR. If I delete the information and requery again seems that the information is not duplicated.

There is also another issue. If I add an account -> logout -> login again -> go to defi deposits -> yearn history doesn't load anything. If I click on refresh data deleting cache then I get the history entries

```
vue.runtime.esm.js:619 [Vue warn]: Duplicate keys detected: '0xa3003d3808495eac82d142f17f00009940d44cbc6b903363024796b065f30fd6-48'. This may cause an update error.

found in

---> <VDataTable>
       <DataTable> at src/components/helper/DataTable.vue
         <DataTableWrapper>
           <VSheet>
             <VCard>
               <Card>
                 <LendingHistory>
                   <Lending> at src/components/defi/Lending.vue
                     <Protocols> at src/views/defi/deposits/Protocols.vue
                       <VTabItem>
                         <VTabsItems>
                           <VTabs>
                             <TabNavigation> at src/components/helper/TabNavigation.vue
                               <DecentralizedDeposits> at src/views/defi/DecentralizedDeposits.vue
                                 <VTabItem>
                                   <VTabsItems>
                                     <VTabs>
                                       <TabNavigation> at src/components/helper/TabNavigation.vue
                                         <DecentralizedFinance> at src/views/defi/DecentralizedFinance.vue
                                           <VMain>
                                             <VApp>
                                               <App> at src/App.vue
                                                 <Root>
```

**Review by yabirgb — APPROVED** [review]
I don't see any other issue and I've created a PR to solve the backend issue with the history. I believe is safe to merge. Thanks :)

**Comment by kelsos** [comment]
> I don't see any other issue and I've created a PR to solve the backend issue with the history. I believe is safe to merge. Thanks :)

If there is anything else we can fix it as we find it :)

**Pull request merged**
