### PR TITLE
Display failed transactions

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix https://github.com/rotki/rotki/issues/8101

Looks like this

### CODE REVIEW

**Comment by yabirgb** [comment]
Seems that is missing the accounting rule. We need to add it also

**Comment by LefterisJP** [comment]
> Seems that is missing the accounting rule. We need to add it also

do we have tests for these? Something should fail no?

**Comment by LefterisJP** [comment]
answer: no nothing failed about accounting

**Comment by LefterisJP** [comment]
The failed test is already marked as a TODO in the VCR tests `rotkehlchen/tests/unit/test_tokens.py::test_last_queried_ts `

**Pull request merged**
