### PR TITLE
Changes default log level to critical in production

### LINKED ISSUE #1561: Logs are not encrypted and show complete address and balance
## Problem Definition

The logs stored in [Windows] C:\Users\USER\AppData\Roaming\rotki\logs can be accessed by anyone with access to the machine. The logs show a complete address and balance, along with bank balances or other manually inputted balances. 

Is there a way to obfuscate the balances and addresses in the logs? The developers don't always need to know this for debugging, maybe add a high level permission to show these if it is required, but it should not show by default as it defeats the purpose of using Rotki. 

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v geth && geth version
command -v parity && parity --version
command -v rotki && rotki version
[ -d .git ] && git rev-parse HEAD
```

### PR DESCRIPTION
**Pull request by kelsos**
image
image

Closes #1561 

I did a bit of tidying in the account management too

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hey @kelsos here seems that frontend ui tests failed

**Review by LefterisJP — COMMENTED** [review]
Hmm running this branch without doing anything still seems to log debug mode.

I tried to change it to critical only and then got a network error when trying to login. Changed it to error, and then log in worked.

Something is wrong in the logic here.

**Comment by kelsos** [comment]
Can you check the functionality? the test is easy to fix. Just some
renaming

**Comment by kelsos** [comment]
Yes  you are in development mode. I am not changing it to critical there.
It is only set to critical when developing. I will re enable the loading
when you restart. For me it didn't require and wait in between.

**Review by LefterisJP — APPROVED** [review]
LGTM as far as the logging functionality is concerned.

There was an error when logging in `Failed to accounts: TypeError: accounts.map is not a function` but @kelsos said it's a remnant to be fixed in later PR.

**Comment by kelsos** [comment]
> LGTM as far as the logging functionality is concerned.
> 
> There was an error when logging in `Failed to accounts: TypeError: accounts.map is not a function` but @kelsos said it's a remnant to be fixed in later PR.

Yup let's see if this issue remains after #1622 is rebased on this PR. If it is we can fix it there

**Pull request merged**
