### PR TITLE
Switch from isort to isort via ruff

### PR DESCRIPTION
**Pull request by dbast**
This is a split out from https://github.com/rotki/rotki/pull/8473 (isort via ruff is faster)

The added newlines look even more correct compared to before.

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by dbast** [comment]
rebased

**Review by LefterisJP — COMMENTED** [review]
Hey @dbast since I merged the other one, this will now need rebasing again

**Comment by dbast** [comment]
rebased

**Review by LefterisJP — APPROVED** [review]
Hey @dbast we discussed it with the team and this looks good. We will just need to adjust editors to use ruff's isort and not isort itself

**Pull request merged**
