### PR TITLE
feat: redecode missing events for protocol events

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by lukicenturi** [comment]
What missing from this PR is the parameter `addresses` for the API `blockchains/ETH/transactions/decode`.

**Comment by kelsos** [comment]
@lukicenturi @yabirgb do we have any update on what is needed for this PR to close?

**Comment by yabirgb** [comment]
@kelsos Yes, the discussion we had yesterday in the discord channel about how to proceed with the endpoint for decoding. Once that is finished this PR gets unblocked

**Comment by kelsos** [comment]
@yabirgb is this still blocked?

**Pull request closed without merging**
