### PR TITLE
feat: enable running single frontend integration test

### LINKED ISSUE #4183: Enable running a single frontend integration test
## Abstract

At the moment the only way to run the frontend integration tests is by doing:

```
npm run test:integration-ci -w rotki
```

There is no way to just run a single test.

## Specification

Make it possible for a dev to run a single integration test. 

@kelsos mentioned in the discord: 

> we need to change parts of the setup if I recall correctly

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4183

How to run:
`ARGS="-s tests/e2e/specs/account-creation.spec.ts" npm run test:integration-ci`

### CODE REVIEW

**Comment by kelsos** [comment]
hmm the changes in the `package-lock.json` are too many for some reason, after clean modules and `npm ci` running it gives me this which is nowhere near the changes in the PR's package-lock.json 

`❯ npm install -w rotki -D --save-exact cross-env@7.0.3` gives me the following 

```diff
diff --git a/frontend/package-lock.json b/frontend/package-lock.json
--- a/frontend/package-lock.json	(revision 8e84c4d14ad240c0e8877813bd6393276d6fb2d5)
+++ b/frontend/package-lock.json	(date 1650016887323)
@@ -94,6 +94,7 @@
         "babel-eslint": "10.1.0",
         "babel-jest": "27.4.6",
         "babel-plugin-istanbul": "6.1.1",
+        "cross-env": "7.0.3",
         "dotenv": "14.3.0",
         "electron": "18.0.1",
         "electron-builder": "22.14.13",
@@ -13130,6 +13131,24 @@
         "sha.js": "^2.4.8"
       }
     },
+    "node_modules/cross-env": {
+      "version": "7.0.3",
+      "resolved": "https://registry.npmjs.org/cross-env/-/cross-env-7.0.3.tgz",
+      "integrity": "sha512-+/HKd6EgcQCJGh2PSjZuUitQBQynKor4wrFbRg4DtAgS1aWO+gU52xpH7M9ScGgXSYmAVS9bIJ8EzuaGw0oNAw==",
+      "dev": true,
+      "dependencies": {
+        "cross-spawn": "^7.0.1"
+      },
+      "bin": {
+        "cross-env": "src/bin/cross-env.js",
+        "cross-env-shell": "src/bin/cross-env-shell.js"
+      },
+      "engines": {
+        "node": ">=10.14",
+        "npm": ">=6",
+        "yarn": ">=1"
+      }
+    },
     "node_modules/cross-spawn": {
       "version": "7.0.3",
       "resolved": "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz",
@@ -47786,6 +47805,15 @@
         "sha.js": "^2.4.8"
       }
     },
+    "cross-env": {
+      "version": "7.0.3",
+      "resolved": "https://registry.npmjs.org/cross-env/-/cross-env-7.0.3.tgz",
+      "integrity": "sha512-+/HKd6EgcQCJGh2PSjZuUitQBQynKor4wrFbRg4DtAgS1aWO+gU52xpH7M9ScGgXSYmAVS9bIJ8EzuaGw0oNAw==",
+      "dev": true,
+      "requires": {
+        "cross-spawn": "^7.0.1"
+      }
+    },
     "cross-spawn": {
       "version": "7.0.3",
       "resolved": "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz",
@@ -61275,6 +61303,7 @@
         "chart.js": "2.9.4",
         "cleave.js": "1.6.0",
         "core-js": "3.20.3",
+        "cross-env": "7.0.3",
         "cypress": "8.3.1",
         "dayjs": "1.10.7",
         "dmg-license": "1.0.10",
Index: frontend/app/package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/frontend/app/package.json b/frontend/app/package.json
--- a/frontend/app/package.json	(revision 8e84c4d14ad240c0e8877813bd6393276d6fb2d5)
+++ b/frontend/app/package.json	(date 1650016887343)
@@ -29,13 +29,13 @@
     "@vue/composition-api": "1.4.6",
     "@vueuse/core": "7.5.5",
     "axios": "0.25.0",
-    "ethereum-blockies-base64": "1.0.2",
     "chart.js": "2.9.4",
     "cleave.js": "1.6.0",
     "core-js": "3.20.3",
     "dayjs": "1.10.7",
     "electron-updater": "4.6.5",
     "electron-window-state": "5.0.3",
+    "ethereum-blockies-base64": "1.0.2",
     "lodash": "4.17.21",
     "loglevel": "1.8.0",
     "pinia": "2.0.9",
@@ -88,6 +88,7 @@
     "babel-eslint": "10.1.0",
     "babel-jest": "27.4.6",
     "babel-plugin-istanbul": "6.1.1",
+    "cross-env": "7.0.3",
     "dotenv": "14.3.0",
     "electron": "18.0.1",
     "electron-builder": "22.14.13",
```

**Comment by lukicenturi** [comment]
> hmm the changes in the `package-lock.json` are too many for some reason, after clean modules and `npm ci` running it gives me this which is nowhere near the changes in the PR's package-lock.json
> 
> `❯ npm install -w rotki -D --save-exact cross-env@7.0.3` gives me the following
> 
> ```diff
> diff --git a/frontend/package-lock.json b/frontend/package-lock.json
> --- a/frontend/package-lock.json	(revision 8e84c4d14ad240c0e8877813bd6393276d6fb2d5)
> +++ b/frontend/package-lock.json	(date 1650016887323)
> @@ -94,6 +94,7 @@
>          "babel-eslint": "10.1.0",
>          "babel-jest": "27.4.6",
>          "babel-plugin-istanbul": "6.1.1",
> +        "cross-env": "7.0.3",
>          "dotenv": "14.3.0",
>          "electron": "18.0.1",
>          "electron-builder": "22.14.13",
> @@ -13130,6 +13131,24 @@
>          "sha.js": "^2.4.8"
>        }
>      },
> +    "node_modules/cross-env": {
> +      "version": "7.0.3",
> +      "resolved": "https://registry.npmjs.org/cross-env/-/cross-env-7.0.3.tgz",
> +      "integrity": "sha512-+/HKd6EgcQCJGh2PSjZuUitQBQynKor4wrFbRg4DtAgS1aWO+gU52xpH7M9ScGgXSYmAVS9bIJ8EzuaGw0oNAw==",
> +      "dev": true,
> +      "dependencies": {
> +        "cross-spawn": "^7.0.1"
> +      },
> +      "bin": {
> +        "cross-env": "src/bin/cross-env.js",
> +        "cross-env-shell": "src/bin/cross-env-shell.js"
> +      },
> +      "engines": {
> +        "node": ">=10.14",
> +        "npm": ">=6",
> +        "yarn": ">=1"
> +      }
> +    },
>      "node_modules/cross-spawn": {
>        "version": "7.0.3",
>        "resolved": "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz",
> @@ -47786,6 +47805,15 @@
>          "sha.js": "^2.4.8"
>        }
>      },
> +    "cross-env": {
> +      "version": "7.0.3",
> +      "resolved": "https://registry.npmjs.org/cross-env/-/cross-env-7.0.3.tgz",
> +      "integrity": "sha512-+/HKd6EgcQCJGh2PSjZuUitQBQynKor4wrFbRg4DtAgS1aWO+gU52xpH7M9ScGgXSYmAVS9bIJ8EzuaGw0oNAw==",
> +      "dev": true,
> +      "requires": {
> +        "cross-spawn": "^7.0.1"
> +      }
> +    },
>      "cross-spawn": {
>        "version": "7.0.3",
>        "resolved": "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz",
> @@ -61275,6 +61303,7 @@
>          "chart.js": "2.9.4",
>          "cleave.js": "1.6.0",
>          "core-js": "3.20.3",
> +        "cross-env": "7.0.3",
>          "cypress": "8.3.1",
>          "dayjs": "1.10.7",
>          "dmg-license": "1.0.10",
> Index: frontend/app/package.json
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/frontend/app/package.json b/frontend/app/package.json
> --- a/frontend/app/package.json	(revision 8e84c4d14ad240c0e8877813bd6393276d6fb2d5)
> +++ b/frontend/app/package.json	(date 1650016887343)
> @@ -29,13 +29,13 @@
>      "@vue/composition-api": "1.4.6",
>      "@vueuse/core": "7.5.5",
>      "axios": "0.25.0",
> -    "ethereum-blockies-base64": "1.0.2",
>      "chart.js": "2.9.4",
>      "cleave.js": "1.6.0",
>      "core-js": "3.20.3",
>      "dayjs": "1.10.7",
>      "electron-updater": "4.6.5",
>      "electron-window-state": "5.0.3",
> +    "ethereum-blockies-base64": "1.0.2",
>      "lodash": "4.17.21",
>      "loglevel": "1.8.0",
>      "pinia": "2.0.9",
> @@ -88,6 +88,7 @@
>      "babel-eslint": "10.1.0",
>      "babel-jest": "27.4.6",
>      "babel-plugin-istanbul": "6.1.1",
> +    "cross-env": "7.0.3",
>      "dotenv": "14.3.0",
>      "electron": "18.0.1",
>      "electron-builder": "22.14.13",
> ```

My bad, updated. @kelsos

**Review by kelsos — APPROVED** [review]
looks good, do you know if the e2e tests were just flaky? I restarted only the failed tasks let's see how it works

**Comment by lukicenturi** [comment]
> looks good, do you know if the e2e tests were just flaky? I restarted only the failed tasks let's see how it works

Yeah it is, but the second run is usually successful, need to investigate why 😬

**Pull request merged**
