### PR TITLE
fix: ui ux for oracle prices

### LINKED ISSUE #5198: User feedback on oracle customization
## Abstract

@isidorosp Found it consufusing the addition/removal of oracles in the settings. The related discord conversation was 

- https://discord.com/channels/657906918408585217/745172610240872508/1047441686860660756
- https://discord.com/channels/657906918408585217/745172610240872508/1047443099128975421

image

## Specification

We could implement instead of the current system with the trash bin and the searchbox a checkbox list that grays the unselected entries.

If a designed comes we could use some feedback from there

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #5198
image
## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
@lukicenturi the checkbox there doesn't really work as a checkbox, right? it is either ticked or the element is not on the list. Maybe we can find an icon, to replace the trash can that can be associated with the disabling action.

**Comment by lukicenturi** [comment]
> @lukicenturi the checkbox there doesn't really work as a checkbox, right? it is either ticked or the element is not on the list. Maybe we can find an icon, to replace the trash can that can be associated with the disabling action.

Yeah I do it on purpose actually. Another option is to use `mdi-close` (x) icon.

**Comment by kelsos** [comment]
> > @lukicenturi the checkbox there doesn't really work as a checkbox, right? it is either ticked or the element is not on the list. Maybe we can find an icon, to replace the trash can that can be associated with the disabling action.
> 
> Yeah I do it on purpose actually. Another option is to use `mdi-close` (x) icon.

Maybe a close with a tooltip then?

**Comment by lukicenturi** [comment]
> > > @lukicenturi the checkbox there doesn't really work as a checkbox, right? it is either ticked or the element is not on the list. Maybe we can find an icon, to replace the trash can that can be associated with the disabling action.
> > 
> > 
> > Yeah I do it on purpose actually. Another option is to use `mdi-close` (x) icon.
> 
> Maybe a close with a tooltip then?

updated

**Review by kelsos — APPROVED** [review]
lgtm @lukicenturi thank you

**Pull request merged**
