### PR TITLE
feat: improve newly detected tokens

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [x] Add etherscan link to address.
- [x] Add action button for each entries.
- [x] "Remove from list" -> "Accept selected tokens"
- [x] Show tx, which the token detected from

### CODE REVIEW

**Comment by yabirgb** [comment]
Was checking the PR. Does it make sense to have the image generated by the tx hash? i believe we don't do it in other places 
image

**Comment by lukicenturi** [comment]
> Was checking the PR. Does it make sense to have the image generated by the tx hash? i believe we don't do it in other places image

my bad, updated

**Comment by yabirgb** [comment]
Another thing about UX that I noticed is that if you want to click on an accept/ignore and a new token appears the table gets updated and the entry moves. You might end up ignoring the wrong asset. Could we maybe avoid this? Not sure how difficult it is

**Comment by kelsos** [comment]
> > Another thing about UX that I noticed is that if you want to click on an accept/ignore and a new token appears the table gets updated and the entry moves. You might end up ignoring the wrong asset. Could we maybe avoid this? Not sure how difficult it is
> 
> Hmm yeah I see what you mean, let's see what I can do about it

Maybe we can disable sorting completely and keep the default table default array order?

**Comment by lukicenturi** [comment]
> > > Another thing about UX that I noticed is that if you want to click on an accept/ignore and a new token appears the table gets updated and the entry moves. You might end up ignoring the wrong asset. Could we maybe avoid this? Not sure how difficult it is
> > 
> > 
> > Hmm yeah I see what you mean, let's see what I can do about it
> 
> Maybe we can disable sorting completely and keep the default table default array order?

That happens because I push the new data to the head of the array.
We can move it to the end, but then if it pass 500 cache_size, the same thing still happens

**Comment by yabirgb** [comment]
> That happens because I push the new data to the head of the array. We can move it to the end, but then if it pass 500 cache_size, the same thing still happens

if 500 cache size is 500 rows that is enough. How it happened to me is probably an edge case but ~20 new tokens can appear with a background task and that can move enough the table to misclick

**Review by kelsos — APPROVED** [review]
The code looks ok @yabirgb can you check the functionality. If function is ok merge.

**Pull request merged**
