### PR TITLE
Introduces improvements for the auto-updater

### LINKED ISSUE #2424: Improve auto-updater experience
## Abstract

While testing the auto-updater on macos I realized that in some cases it is not overly clear what is happening.
To improve the overall experience the following should be done:

### Tasks 

- [x] Show download progress when the file is downloaded
- [x] Redirect logging of electron-updater to the `rotki-electron.log`
- [x] Properly notify the user when the download fails for any reason (e.g macos read-only dmg)

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2424

### CODE REVIEW

**Comment by kelsos** [comment]
- I also tested on the `macos` read-only dmg to ensure that there is an error message.

**Review by LefterisJP — COMMENTED** [review]
How can I test this myself? If you did it I trust you .. but I guess we would need to anyway test this somehow manually again before v1.16.0

**Comment by kelsos** [comment]
You can go to package.json change the version to something lower like 1.14.1 build and run.

**Comment by kelsos** [comment]
> How can I test this myself? If you did it I trust you .. but I guess we would need to anyway test this somehow manually again before v1.16.0



> How can I test this myself? If you did it I trust you .. but I guess we would need to anyway test this somehow manually again before v1.16.0

This dialog will only be shown to people updating from v1.16.0 to the next version. Manually testing it again won't really make a difference right? if it works now it will work then too.

The people upgrading from v1.15 will not see any progress since v1.15.0 doesn't contain the progress part

**Comment by LefterisJP** [comment]
> Manually testing it again won't really make a difference right? if it works now it will work then too.

Well no. You or I could introduce a change that accidentally breaks it.

**Review by LefterisJP — APPROVED** [review]
Merging this but would need another test before v1.16.0 just to make sure it still works.

**Comment by kelsos** [comment]
> > Manually testing it again won't really make a difference right? if it works now it will work then too.
> 
> Well no. You or I could introduce a change that accidentally breaks it.

We better not :laughing:  it takes some time to test this

**Pull request merged**
