### PR TITLE
chore: upgrade electron version

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
@yabirgb @LefterisJP can someone push this to build? We need to make sure that the major electron builder update does not break anything. Might need to verify binaries too just to be safe

**Comment by LefterisJP** [comment]
> @yabirgb @LefterisJP can someone push this to build? We need to make sure that the major electron builder update does not break anything. Might need to verify binaries too just to be safe

I will do it

**Comment by LefterisJP** [comment]
There were deployment errors @kelsos @lukicenturi

**Review by kelsos — APPROVED** [review]
All builds work fine so we can merge thanks @lukicenturi

**Pull request merged**
