### PR TITLE
yolo test_callback_segfault_simple

### PR DESCRIPTION
**Pull request by LefterisJP**

### CODE REVIEW

**Comment by LefterisJP** [comment]
Test passed on its own

**Comment by LefterisJP** [comment]
This shit won''t fail. Tried `rotkehlchen/tests/test_no_missing_init.py rotkehlchen/tests/test_users.py rotkehlchen/tests/data_migrations/ rotkehlchen/tests/db/` now and passed.

**Comment by LefterisJP** [comment]
Running the entire "others" backend tests makes it fail: `python pytestgeventwrapper.py $PYTEST_ARGS $COVERAGE_ARGS --ignore=rotkehlchen/tests/api rotkehlchen/tests/`

**Comment by LefterisJP** [comment]
Okay made it fail nicely and fast by `python pytestgeventwrapper.py $PYTEST_ARGS $COVERAGE_ARGS -x --ignore=rotkehlchen/tests/api rotkehlchen/tests/`

Unfortunately only on the CI

**Comment by LefterisJP** [comment]
By reverting the urlib3 change test passes ofc, so it's definitely that.

**Comment by LefterisJP** [comment]
Canceled the workflow as it passed the test without failing. So adding TRACE logging makes it not happen. Which ... helps us not.

**Comment by LefterisJP** [comment]
Even increasing the events and decreasing sql_vm_instructions_cb makes this pass. Canceled the workflow again.

**Comment by LefterisJP** [comment]
Okay nice so going back to no trace and no test changes reproduces immediately. At least that's something. Wish I could do this locally.

**Comment by yabirgb** [comment]
We can close this PR right?

**Pull request closed without merging**
