### PR TITLE
Refactor code for multi-evm architecture

### PR DESCRIPTION
**Pull request by LefterisJP**
First commit is a squash of the 2 weeks work seen in https://github.com/rotki/rotki/pull/5180.
Last state of that first commit was to pass linting after merging develop and then squashing the entire branch into 1 commit.

### CODE REVIEW

**Comment by LefterisJP** [comment]
yay. All backend tests green and in sync with develop

giphy (7)

**Comment by kelsos** [comment]
Hmm interesting the e2e tests failed because the assets never loaded in the asset manager.

**Comment by LefterisJP** [comment]
Rebased on top of develop after https://github.com/rotki/rotki/pull/5181/. Took some time ...

 Got green lint and ethereum transaction tests (that were touched by it) passed again.

**Comment by LefterisJP** [comment]
Both failed tests passed locally. I think this `test_convex.py::test_convex_pools ` is our current slowest test and as such caused rate limiting and then stuff failed.

But they pass locally.

That means the base work of the refactor (as far as I can remember) is done. And now I can start work on optimism itself in maybe even smaller PRs.

I will go ahead and merge this. I know it's gonna break everything, especially frontend since it needs to be updated. I am here to help. But can't keep this PR open any more. Each rebase of this is a pain.

**Pull request merged**
