### PR TITLE
Add fees to withdrawals from binance

### LINKED ISSUE #2475: Binance withdrawals don't include fees
For all deposits to Binance the transaction fee is listed as zero. I could correct this by manually adding a ledger action, or adding a blockchain balance. However not all blockchains are supported.

Could Rotki take the txid for the asset and query the fee that was paid to make the deposit?

Should I add blockchain balances for the supported assets BTC, ETH and manually add ledger actions for the others?

### PR DESCRIPTION
**Pull request by yabirgb**
Closes #2475 .One question I have is: in the [documentation](https://binance-docs.github.io/apidocs/spot/en/#withdraw-history-user_data) they have for one of the fields `None` but I believe in the json response should be `null`. I've changed that for the tests but don't know if it is a bad assumption on my side. `None` raises an error in `json.loads`

### CODE REVIEW

**Comment by LefterisJP** [comment]
> One question I have is: in the [documentation](https://binance-docs.github.io/apidocs/spot/en/#withdraw-history-user_data) they have for one of the fields `None` but I believe in the json response should be `null`. I've changed that for the tests but don't know if it is a bad assumption on my side. `None` raises an error in `json.loads`

Of course it should be `null`. `None` is python for `null`. The JSON standard does not know what `None` is. It's a typo of a python programmer :wink:

**Review by LefterisJP — APPROVED** [review]
LGTM. Just needs a rebase.

**Comment by yabirgb** [comment]
All green + rebased. Merging!

**Comment by a7e8** [comment]
Does this support when the fee is in BNB too?

**Pull request merged**
