### PR TITLE
Fix blurry icons on macOS

### PR DESCRIPTION
**Pull request by Pythoniasm**
This PR addresses #502 and replaces the current broken ICNS-File in the electron assets with a newly generated from the proposed image files of #502 issue description.

The ICNS-file is created as follows:

```bash
mkdir rotki.iconset
# Repeating for various resolutions
sips -z 16 16 icon_256x256.png --out rotki.iconset/icon_16x16.png
sips -z 32 32 icon_256x256.png --out rotki.iconset/icon_16x16@2.png
...
iconutil -c icns rotki.iconset/
```

It is important to name the output dir as ``*.iconset`` and the contained files as ``icon_RES.png``. Make sure to also include high-res ``@2`` files for Mac retina displays.

The resulting ``rotki.icns`` can be copied to the asset directory.

For future releases, add even more resolutions - starting from a quadratic 1024 px file. Additionally, there is a bug in the SVG-file of #502, using a non-parsable XML namespace ``:i``. This can be replaced with the W3 XML specification.

### CODE REVIEW

**Comment by Pythoniasm** [comment]
Requesting a CLA signing is rather shady for a decentralized aimed software project.

**Comment by LefterisJP** [comment]
Hey @Pythoniasm thank you so much for taking the time to check this out.

I am sorry you find the CLA signing annoying but from experience it's a good thing to have for opensource software that is also trying to monetize itself and stay flexible. 

For example a lot of people, myself included, spent years working on cpp-ethereum (now called Aleth: https://github.com/ethereum/aleth) and when circumstances required changing the license in order to get more adoption for the client, the refusal of 1 contributor to change the license doomed the project. For more info on this check here: https://www.reddit.com/r/ethereum/comments/70f9mf/why_is_cppethereum_gpl_and_pyethereum_mit/dn2sewf/

**Comment by LefterisJP** [comment]
Hey @Pythoniasm check my [previous comment](https://github.com/rotki/rotki/pull/712#issuecomment-583847850) to understand why a CLA is needed.

If that's still not fine with you and you do not intend to accept the CLA even for such a small contribution then I will close the PR so that someone else can take a swing at it.

**Comment by LefterisJP** [comment]
I take it you

**Comment by Pythoniasm** [comment]
Hey @LefterisJP while I can understand your desire regarding the CLA, I will not sign it. This is based on my personal idealism of WTFPL licenses for open source projects. If you are running a business by offering a service based on the open source code, that's totally fine for me, I still wanted to contribute to your non-premium open source parts.

However, please address this PR by yourself and as an easy fix to the blurry MacOS icons. Like WTFPL states, use any code of this PR 1:1 as it is supposed to contribute as improvement for this project.

**Pull request closed without merging**
