### PR TITLE
Adds changes to allow graphs based on frontend cached balances

### LINKED ISSUE #2849: Value distribution by asset logic
When on `/statistics` page `Value distribution by asset` with default `0` assets to show indicates an erro, when changing to `1` displays `You cannot show more than 0 assets`.
I have `BTC` balance on imported exchanges but asset value is not displayed probably due to short period of time after import(10-30 minutes). But anyway, expected to see some value to the graph. Also `Value distribution by location` is not displayed.
Screen Shot 2021-05-05 at 7 09 52 PM
Screen Shot 2021-05-05 at 7 10 49 PM

Exchange balance:
Screen Shot 2021-05-05 at 7 19 49 PM

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2849

### CODE REVIEW

**Review by LefterisJP — APPROVED** [review]
So as requested I tried this along with the gitlab MR.

Seems to work but wth some kind of delay.

What I did was load a new account. Went to the statistic. HAd nothing as expected.

I then added a manual balance and went to the statistics. It still had nothing.

I went back to the dashbooard again and then again to the statistics and then it finally worked.

**Comment by LefterisJP** [comment]
Rebased this on develop

**Comment by kelsos** [comment]
> So as requested I tried this along with the gitlab MR.
> 
> Seems to work but wth some kind of delay.
> 
> What I did was load a new account. Went to the statistic. HAd nothing as expected.
> 
> I then added a manual balance and went to the statistics. It still had nothing.
> 
> I went back to the dashbooard again and then again to the statistics and then it finally worked.

That is the problem I mentioned

**Comment by LefterisJP** [comment]
> That is the problem I mentioned

Okay then I am changing this to "ready for review" and approving?

**Review by LefterisJP — APPROVED** [review]
LGTM

**Pull request merged**
