### PR TITLE
Show new window for pnl actionable items

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
It creates a new instance of the app. 

You can see that if you try to inspect the pinia store you can see that any changes done to one window are not reflected in the other window. Also if you open the console/network tab you can see that both windows are polling messages and connect to the WebSocket.

**Comment by lukicenturi** [comment]
> It creates a new instance of the app.
> 
> You can see that if you try to inspect the pinia store you can see that any changes done to one window are not reflected in the other window. Also if you open the console/network tab you can see that both windows are polling messages and connect to the WebSocket.

I thought what you mean by a new instance of the app is the electron entry on activity manager.
Yes, the things you said are correct, but I think it is still okay because the second window shouldn't be able to do anything other than see the actionable items (currently it can input prices, but we can hide it in the second window).

But if you think this potentially causes unwanted bugs, we can remove this implementation.

**Comment by kelsos** [comment]
> > It creates a new instance of the app.
> > You can see that if you try to inspect the pinia store you can see that any changes done to one window are not reflected in the other window. Also if you open the console/network tab you can see that both windows are polling messages and connect to the WebSocket.
> 
> I thought what you mean by a new instance of the app is the electron entry on activity manager. Yes, the things you said are correct, but I think it is still okay because the second window shouldn't be able to do anything other than see the actionable items (currently it can input prices, but we can hide it in the second window).
> 
> But if you think this potentially causes unwanted bugs, we can remove this implementation.

I am not opposed to having an independent window but there are things to consider.

Since the new instance of the application (vue) is created, we need to make sure that this window works only with the minimum required state in order to perform its purpose. 
Polling/checking messages etc for example is not required, 

Currently, it will do the same things the main app does, also including fetching balances etc. 

Also, we need an alternative for docker/web since a new tab is not always the best approach.

**Comment by lukicenturi** [comment]
> > > It creates a new instance of the app.
> > > You can see that if you try to inspect the pinia store you can see that any changes done to one window are not reflected in the other window. Also if you open the console/network tab you can see that both windows are polling messages and connect to the WebSocket.
> > 
> > 
> > I thought what you mean by a new instance of the app is the electron entry on activity manager. Yes, the things you said are correct, but I think it is still okay because the second window shouldn't be able to do anything other than see the actionable items (currently it can input prices, but we can hide it in the second window).
> > But if you think this potentially causes unwanted bugs, we can remove this implementation.
> 
> I am not opposed to having an independent window but there are things to consider.
> 
> Since the new instance of the application (vue) is created, we need to make sure that this window works only with the minimum required state in order to perform its purpose. Polling/checking messages etc for example is not required,
> 
> Currently, it will do the same things the main app does, also including fetching balances etc.
> 
> Also, we need an alternative for docker/web since a new tab is not always the best approach.
> 
> Well, it might cause bugs, since the interaction between backend and frontend was not designed with multi-instance support in mind.

Alright then, I guess I'll just do simple pinning feature inside the app.

**Comment by lukicenturi** [comment]
https://github.com/rotki/rotki/pull/4464

**Pull request closed without merging**
