### PR TITLE
Do not use isisnstance to check an asset is a token #1741

### PR DESCRIPTION
**Pull request by djibix**
Add import AssetType from rotkehlchen.typing on all modified files
Replace isinstance(x, EthereumToken) by x.asset_type == AssetType.ETH_TOKEN

### CODE REVIEW

**Comment by LefterisJP** [comment]
@djibix Thanks for the pull requests. Question: Why are you closing them and openign new ones? You can just amend the commit if there are errors.

**Comment by djibix** [comment]
Hi Lefteris, well I'm new to Github, not really used to it. I'll check how to amend then.
Thing is that the first one did not pass the lint test, though it compiled on my machine. I had to add an import on all files. Is that expected ?

**Comment by LefterisJP** [comment]
To run the linter locally before pushing type `make lint`

**Comment by djibix** [comment]
Well this one does not pass either :-(

**Comment by djibix** [comment]
> To run the linter locally before pushing type `make lint`

Alright I'll do that

**Comment by vnavascues** [comment]
I'm closing this PR as its issue has been closed as well.

**Pull request closed without merging**
