### PR TITLE
feat: reset EVM transaction events

### LINKED ISSUE #6243: frontend: add a transaction (evm) reset button
## Abstract

Add a button in the overflow menu to reset a transaction. The button will delete any customized events the user might have and re-decode the specific transaction.

## Motivation

There is no way to reset a single event you can only ignore.
Deleting and re-decoding can work but it is not obvious.

## Specification

- [ ] Add a reset button that deletes any customized evm transaction and re-decodes events for this transaction.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #6243

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
@lukicenturi for this as I wrote in discord

- We need to make sure that editing is possible even when loading (unless it's saving)
- We need to only disable reset only when we re-decode.

**Comment by lukicenturi** [comment]
> @lukicenturi for this as I wrote in discord
> 
> * We need to make sure that editing is possible even when loading (unless it's saving)
> * We need to only disable reset only when we re-decode.

This comment has been addressed now on the last commit

**Comment by kelsos** [comment]
> > @lukicenturi for this as I wrote in discord
> > 
> > * We need to make sure that editing is possible even when loading (unless it's saving)
> > * We need to only disable reset only when we re-decode.
> 
> This comment has been addressed now on the last commit

Thanks, I am gonna check then.

**Comment by kelsos** [comment]
We need a changelog entry for this btw

**Pull request merged**
