### PR TITLE
Users can now select ETH or BTC for their profit currency 

### LINKED ISSUE #1270: User should be able to set a crypto asset as their main currency
## Abstract

Users should be able to set a crypto asset (e.g. BTC / ETH) as their "main currency". Instances in the application where "USD Value" / "EUR Value" etc would then be replaced by something like "BTC Value".

The ideal way to do this would be to actually calculate prices from the original asset to the crypto "main currency" using corresponding trading pairs, but the reality is that this is possible only for some assets (and then the actual price of the pair may fluctuate a lot depending on the source). As a result the most feasible way of implementing this would be to just convert the total "usd value" of all assets except the main one from "usd" to that crypto currency.

Historical prices will need to be obtained for the tax report and graphs to work properly.

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix #1270

### CODE REVIEW

**Comment by LefterisJP** [comment]
@kelsos if this passes all tests I think the frontend part can be done and should be trivial

**Comment by kelsos** [comment]
Good! are we going for the returning the exchange rates approach?

**Comment by LefterisJP** [comment]
@kelsos yes. Its also noted in the docs.

**Comment by kelsos** [comment]
e2e failed, I will check after the artifact upload

**Pull request merged**
