### PR TITLE
Introduces MakerDAO Vaults frontend part

### PR DESCRIPTION
**Pull request by kelsos**
Frontend part of #707

### CODE REVIEW

**Comment by kelsos** [comment]
> Some more comments after testing with the dev proxy locally:
> 
>     1. The liquidation price should respect the rest of the floating point value settings. In my machine it showed a price of `115.4761904761904761904761905` USD per ETH which takes a lot of space and looks bad.
> 
>     2. The first time I tried to load the vaults I got a NAN for creation time and also no events are shown. After a while and reloading events are still not shown but creation date is.
> 
> 
> I suspect this may be due to the requirement in `develop` to query vaults and then query vault details. Because the vault details call relies on the vault calls being fixed. In another PR I am working on this is addressed. Could that be it?
> 
> The frontend errors are:
> 
> ```
> vue.runtime.esm.js:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'toFormat' of undefined"
> 
> found in
> 
> ---> <AmountDisplay> at src/components/display/AmountDisplay.vue
>        <VCard>
>          <StatCard> at src/components/display/StatCard.vue
>            <Vault> at src/components/defi/Vault.vue
>              <Borrowing> at src/components/defi/Borrowing.vue
>                <DecentralizedBorrowing> at src/views/defi/DecentralizedBorrowing.vue
>                  <VContent>
>                    <VApp>
>                      <App> at src/App.vue
>                        <Root>
> ```
> 
> and
> 
> ```
> Uncaught (in promise) TypeError: Cannot read property '__esModule' of undefined
>     at ensureCtor (vue.runtime.esm.js:3592)
>     at eval (vue.runtime.esm.js:3665)
>     at eval (vue.runtime.esm.js:336)
> ```

Is there any issue with the details api? the only reason for NaN and empty is that for some reason it failed to find details, and the merged object had undefined fields. How much of a possibility is this? It seems that I missed the liquidation price.

**Comment by LefterisJP** [comment]
> I suspect this may be due to the requirement in develop to query vaults and then query vault details. Because the vault details call relies on the vault calls being fixed. In another PR I am working on this is addressed. Could that be it?

This ^

**Comment by LefterisJP** [comment]
Also there needs to be some kind of loading indicator when you press the "Borrowing" tab for DeFi. It shows 0 for everything and no vaults, until at some point that changes. You should use the same loading indicators as on the dashboard.

**Comment by kelsos** [comment]
It should have the same progress thing as the Lending.

**Comment by LefterisJP** [comment]
@kelsos As explained in discord, the transaction hash is not going to be unique per event. So you can have the same hash in multiple events.

Also would be nice if you change them from just being a hash to being a link to the equivalent etherscant transaction.

**Pull request merged**
