### PR TITLE
Introduces frontend for Compound 

### PR DESCRIPTION
**Pull request by kelsos**
- [x] Fix failing ui tests

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Thanks!

So some first feedback after checking it out locally.

1. The from/to asset component needa alignment in the arrow.



2. Misaligned icons under protocol



3. In the lending page, how is the interest earned calculated? The $ value.

4. Borrowing page


    - Says Aave loan. Should be compound.
    - What is the locked up collateral? Is it all locked up collateral in compound? Have you made sure it's from that one account and not all account? Is there any way to actually show the tokens? For example, with this account I have BAT + ZRX locked.
    - What is the APR? And why is it empty?
    - Why are events + rewards + debt loss empty?


6. Not sure if this is also on develop. But every time I add a new account all DeFi stuff in the frontend are not working. It's as if all data has dissapeared. Overview empty, lending empty, borrowing empty. If I press refresh it works again.

**Comment by kelsos** [comment]
Locked collateral ->
image

**Comment by kelsos** [comment]
> Why are events + rewards + debt loss empty?

I have no idea, with the test accounts I was using they where not, can you see/send me the response from the backend or PM the address used?

>Not sure if this is also on develop. But every time I add a new account all DeFi stuff in the frontend are not working. It's as if all data has dissapeared. Overview empty, lending empty, borrowing empty. If I press refresh it works again.

Not on develop, I have an idea on what the problem is, it should be simple to fix

> Is there any way to actually show the tokens? For example, with this account I have BAT + ZRX locked.

We didn't have this for aave so I missed it, thanks for pointing

> What is the APR? And why is it empty?

image
I am guessing a typo in the documentation of the api?

**Comment by kelsos** [comment]
@LefterisJP 

>  Is there any way to actually show the tokens? For example, with this account I have BAT + ZRX locked. 

I am reading this again and basically the way it works we create a new "loan entry" for each asset. So the one selected is the `BAT` one and you should also have the `ZRX` in the same dropdown. Could you describe more how do you imagine showing the tokens would work?

**Comment by LefterisJP** [comment]
> @LefterisJP
> 
> > Is there any way to actually show the tokens? For example, with this account I have BAT + ZRX locked.
> 
> I am reading this again and basically the way it works we create a new "loan entry" for each asset. So the one selected is the `BAT` one and you should also have the `ZRX` in the same dropdown. Could you describe more how do you imagine showing the tokens would work?

I am referring to the tokens locked in as collateral for Compound. They would be the same for all compound loans, since all loans share the same collateral.

**Review by LefterisJP — COMMENTED** [review]
More review time!

When I went to the borrowing tab and looked at a compound loan I got an exception in the console.
[localhost-1599896207249.log](https://github.com/rotki/rotki/files/5212357/localhost-1599896207249.log)

Comp details are not needed. PNL is always the same as the gained asset, the comp.




For borrowing for **a single loan** in Rewards and debt loss the address is not need. The loan already has it stated.


For liquidations we definitely need a much stronger red tone for the loss.



Also perhaps some kind of icon or something to indicate the left part, the green is what we get to keep, and the right part, the red is what we lost due to liquidation.



As seen above there is a bit too big of a gap between the icon and the amounts. Probably nitpicky on my side, but why is that?



Finally, in the lending part for the overview would it not make sense to add same assets together? Above you see that there are 2 different USDC entries for the 2 accounts that are lending it.

> Not sure if this is also on develop. But every time I add a new account all DeFi stuff in the frontend are not working. It's as if all data has dissapeared. Overview empty, lending empty, borrowing empty. If I press refresh it works again.

So now it seems that it will force refresh after adding a new account, right?  Would be nice to (in the future) have more narrow queries (per address)

**Comment by LefterisJP** [comment]
Ah another thing. Also as discussed would be great to have the borrowing Compound awards in the borrowing tab, and the lending on the lending. And not all in both. But that's more like a "good to have". We can make an issue about it later.

**Comment by kelsos** [comment]
About the space part, making it properly adjust for the whole column would be tricky because it is not a td. And to keep the icons vertically aligned I would have to check how many characters are displayed in all the amounts in the column and the adjust to the bigger value in the column. This hard-coded space seems to work with big numbers too. It is not perfect but maybe we can open and issue to make this dynamic.

**Comment by kelsos** [comment]
Develop is also force refreshing. We had that as a solution to the problem of outdated data when adding or removing accounts. The reason that it did not work was because I moved the status state and it didn't properly reset.

Sure can you open an issue to make the calls per account.

The assets are currently displayed per account and filtered by the account this is how we initially implemented this. Do we want to have the aggregation only per protocol? Or per asset? It would make sense if we are aggregating to get done with the address and protocol columns and aggregate per asset. The filtering can happen by the regular filters.

**Comment by LefterisJP** [comment]
>The assets are currently displayed per account and filtered by the account this is how we initially implemented this. Do we want to have the aggregation only per protocol? Or per asset? It would make sense if we are aggregating to get done with the address and protocol columns and aggregate per asset. The filtering can happen by the regular filters. 

On second thought I think we should allow both. Perhaps I want to see all different loans I am doing across all my accounts. This is good then. But then I may want to aggregate common assets In which case what I said would make sense. Can we offer the option to have both?

Also for example with the yearn vaults it's no longer assets, but locking up something in a vault. So a more generic way of phrasing it should be found

**Comment by kelsos** [comment]
> > The assets are currently displayed per account and filtered by the account this is how we initially implemented this. Do we want to have the aggregation only per protocol? Or per asset? It would make sense if we are aggregating to get done with the address and protocol columns and aggregate per asset. The filtering can happen by the regular filters.
> 
> On second thought I think we should allow both. Perhaps I want to see all the different loans I am doing across all my accounts. This is good then. But then I may want to aggregate common assets In which case what I said would make sense. Can we offer the option to have both?
> 
> Also for example with the yearn vaults it's no longer assets, but locking up something in a vault. So a more generic way of phrasing it should be found

@LefterisJP 
The idea I had in mind is to use the filtering to see specific assets per account, per protocol. So, if you have nothing selected you will see the aggregated amount across all protocols/addresses. Then if you go and select a specific address you will see the aggregated asset across all the protocols for the specific address. Finally, if you want to see details for a specific protocol/address you can do that by selecting the address and protocol from the filtering dropdowns.

Does this work for you? I think is reasonable as an approach and the filters are already there and do the same for some the totals.

**Comment by LefterisJP** [comment]
Yeah I guess this will be okay for now

**Review by LefterisJP — COMMENTED** [review]
Hey @kelsos so it's almost okay.

Some things missing.

1. Changelog entry for #597 and #804. Perhaps a combined entry would make sense for support of current compound lending/borrowing tracking and historical accounting.

2. 


This should be Details

3. 


There is a mistake here. And I am not really sure what would be the best way to show it. The API returns to you:

```json
                "debt_loss": {
                    "0xC440f3C87DC4B6843CABc413916220D4f4FeD117": {
                        "ETH": {
                            "amount": "0.011888402916288040",
                            "usd_value": "1.896370626849345935435"
                        },
                        "cUSDC": {
                            "amount": "84.96926318",
                            "usd_value": "1.784441127757439110"
                        }
                    },
```

But the ETH here is not really lost. It's actually gained due to the liquidation. As discussed you already show it below with the green numbers.

It's the backend's bad for showing it there like that. A small amount should indeed be there, but the bigger amount is gained due to liquidation. Where should the backend return it? Should I just add it in interest_profit? Would it be shown properly if I do?

So the ETH would be split. Some part as loss inside `debt_loss` and another one as gained. And the question is where should I put it?

**Review by LefterisJP — COMMENTED** [review]
Nice but there are still some problems.



In the liquidation example you are missing the actual liquidation loss of the cUSDC.

And finally one last thing I discovered which I don't likeand will see how to handle in the backend is



IT adds the outstanding debt as a loss, which is not really. Unless you get liquidated.

I will probably handle the last one with a commit

**Comment by LefterisJP** [comment]
For the last thing I just pushed a commit. It now makes sure to not take the outstanding debt into account.

**Review by LefterisJP — APPROVED** [review]
LGTM. Test failures are due to etherscan problems.

**Pull request merged**
