### PR TITLE
Various minor UI fixes (partial fix for #939)

### PR DESCRIPTION
**Pull request by isidorosp**
Partially addresses #939

* Fixes Currency Dropdown to not be affected by premium component rendering
* Fixes an overlay z-index issue with the navigation bar on wide resolutions
* Adds autofocus to the Login and Create User dialogs (username is automatically selected at load)

[ui tests]

### CODE REVIEW

**Comment by isidorosp** [comment]
@kelsos the above is ready for a check by you. In order to fix the "white" background on the navbar will you do a separate PR or just commit on top of this one?

**Comment by kelsos** [comment]
> @kelsos the above is ready for a check by you. In order to fix the "white" background on the navbar will you do a separate PR or just commit on top of this one?

I will do a new PR and might be needed to do so in the premium components

**Comment by isidorosp** [comment]
> I will do a new PR and might be needed to do so in the premium components

In that case should I just ready this for review and you can do the changelog entry in your PR?

**Comment by kelsos** [comment]
> > I will do a new PR and might be needed to do so in the premium components
> 
> In that case should I just ready this for review and you can do the changelog entry in your PR?

Please also add the changelog entry here. If this is fixed in the premium components then the PR will be in the component repo.

**Pull request merged**
