### PR TITLE
feat: UI download db snapshot for particular timestamp

### LINKED ISSUE #3894: Balance export for a specific date (Italian fiscal system)
## Abstract

In Italy every resident owning cryptocurrencies should declare his owning at the 1 of January and the 31 of December. Also, if the value of total asset is above 51.645,69€ for more than one week during the fiscal year, a 26% tax on every EUR conversion (wire transfer or card expenses) is due.

Competitor Cointracking.io is offering the snapshot.

## Motivation

Italian users of Rotki would appreciate the possibility of exporting the balance with all tokens at specific dates and easily comply with fiscal system.

The 51.645,69€ EUR / 1 week threshold would be another plus but IMHO not so important.

## Specification

Every time Rotki is opened a balance snapshot is taken and saved in the DB. Export that balance with all tokens (basicly the Dashboard view) for a specific date in a PDF printout.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #3894

- [ ] UI download db snapshot for particular timestamp
Apr-18-2022 11-34-42

### CODE REVIEW

**Review by kelsos — APPROVED** [review]
code looks good thank you

**Review by LefterisJP — COMMENTED** [review]
Hey @lukicenturi thanks, it seems to work but there is something that is missing. I was not sure it worked when I pressed "export". We need some kind of success popup. As the menu for export even stays open after successful export so we have no way to know it worked other than trying to look for the zip file.

**Comment by lukicenturi** [comment]
> Hey @lukicenturi thanks, it seems to work but there is something that is missing. I was not sure it worked when I pressed "export". We need some kind of success popup. As the menu for export even stays open after successful export so we have no way to know it worked other than trying to look for the zip file.

Updated, please check again @LefterisJP

**Review by LefterisJP — COMMENTED** [review]
Hey @lukicenturi thanks a lot.

I now see the confirmation window but what makes no sense is the amount in the original popup. Take a look at the following video.


https://user-images.githubusercontent.com/1658405/163875151-f2477387-7728-4989-bdf8-d4975431408e.mp4



I click on the highest value 271,668.02 EUR but when exporting a different value appears in the popup 251,508.63€

**Comment by lukicenturi** [comment]
> Hey @lukicenturi thanks a lot.
> 
> I now see the confirmation window but what makes no sense is the amount in the original popup. Take a look at the following video.
> 
>  Peek.2022-04-18.22-43.mp4 
> I click on the highest value 271,668.02 EUR but when exporting a different value appears in the popup 251,508.63€

My bad, I use the wrong currency when converting. It should be correct now @LefterisJP

**Review by LefterisJP — APPROVED** [review]
LGTM @lukicenturi. Thanks!

**Pull request merged**
