### PR TITLE
bitfinex: use fee_asset from api instead of guessing

### PR DESCRIPTION
**Pull request by philhug**
Fixes: #2013

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Make sure it works for you since you got the test data and also please add a changelog entry: https://github.com/rotki/rotki/blob/develop/docs/changelog.rst

Just add it above the last release and denote it as bug.

**Review by LefterisJP — COMMENTED** [review]
Hey @philhug it seems that the change also affected a test that will need fixing: `test_deserialize_trade_sell`: https://github.com/rotki/rotki/blob/de9bb50f3a0deb8c1e1aed2d0c8c70b6bc431957/rotkehlchen/tests/exchanges/test_bitfinex.py#L344

You can run the bitfinex tests by being in  virtualenv of rotki and do: `python pytestgeventwrapper.py -xs rotkehlchen/tests/exchanges/test_bitfinex.py`

And that particular test only:

`python pytestgeventwrapper.py -xs rotkehlchen/tests/exchanges/test_bitfinex.py::test_deserialize_trade_sell`

**Review by LefterisJP — APPROVED** [review]
Thanks a lot @philhug. Looks good to me. We will also add a clause in the next DB upgrade to reset the bitfinex trades of the user so they are resaved with the correct fee.

**Comment by vnavascues** [comment]
@philhug @LefterisJP Thanks a lot for addressing this. I'll do the migration.

**Pull request merged**
