### PR TITLE
feat(electron): make window initial size proportional

### LINKED ISSUE #5920: frontend(electron): make the window initial size proportional to screen
## Abstract

Make sure that the initial window size when the application is opened for the first time is relative to the screen site.

We can keep the current default value as the minimum (base) and then calculate the percentage this default has on a basic 15" laptop screen `1366 x 768` screen resolution.

Then based on the screen size make the window that percentage of the active resolution assuming that it is bigger than `1366 x 768`.

## Motivation

The initial window might appear too small when opened on a retina or 4k screen.

## Specification

- Make sure that the initial screen size is proportional to the screen
- Make sure that when re-opening the app the window restores to the last known size (`electron-window-state` should take care of it just make sure it does)

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #5920

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by lukicenturi** [comment]
to reset the saved size, go to `/Users/{username}/Library/Application Support/rotki` and delete `rm -rf window-state.json`

**Comment by kelsos** [comment]
@lukicenturi could you read the linked issue again? 

What I describe in the issue is not making the window full-screen for every screen size.

**Comment by lukicenturi** [comment]
> @lukicenturi could you read the linked issue again?
> 
> What I describe in the issue is not making the window full-screen for every screen size.

This should be updated now

**Review by kelsos — APPROVED** [review]
lgtm @lukicenturi thanks

**Pull request merged**
