### PR TITLE
Introduces frontend NFT support

### LINKED ISSUE #1097: Support ethereum NFTs
## Abstract

There is a big market for NFTs in ethereum and an untapped need to track and account for them.

There is crypto collectibles marketplaces like https://opensea.io/

We should be able to account for them

## Task

Figure out a way to autodetect NFTs owned by an ethereum address. A good start would be ERC721 tokens. 

For ERC721 tokens etherscan offers an events endpoint to get a list of ERC721 token transactions per account: https://etherscan.io/apis#accounts

We could use that to see what ERC721 a user has and show their balance after processing them all.

There is also the ERC1155 standard for NFTs

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1097

## Checklist

- [x] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### TODO
- [x] Fix response in documentation (valid json and missing properties)
- [x] Add pagination (different number of items per page depending on the screen size)
- [x] Add address filtering
- [x] Add empty screen when the account has no nfts
- [x] Add missing icon placeholder image
- [x] Add loading when entering the component

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
Thanks a lot! Looks okay.

So some comments on things that can be improved on the UI.

## Separate space between name and price



It would be nice if there was some way to separate the name and the price area. The name seems too big.

## Make tiles smaller. Fit more in same space.

Opensea fullscreen



rotki fullscreen



I think you can make our tiles smaller and as such fit more in the same space as opensea does

## Overflow of name



This probably ties with the name + price separation comment I made above. But as you can see the name somehow does not shorten for some NFT and pushes itself even out of the tile.

Check lefteris.eth NFTs to replicate.

## Funny look at address filtering


https://user-images.githubusercontent.com/1658405/132415905-746f9621-85f9-436c-8981-d5428ab973d3.mp4

The address filtering menu looks funny once I use it to filter by address

## Image missing NFTs



Can we find a bit better generic NFT image than this? Not really a biggy. I think you also mentioned this as an open question at standup.




Also what is the difference between those two? One has no image and the other the "no image" image.


## Handling of the free version limit is missing

The free version limit is missing. We discussed in the standup you would implement it. Just leaving a reminder here.

----- 

Non ui-related comments for backend:

1. I created a new account, added premium keys, added my lefteris.eth account and then only saw 5 NFTs. Same as free limit. Something is off there with the addition of the api keys not being properly forwarded. I should check this out. After re-login worked fine.
2. Need to implement the pricing data properly. There are many suggestions in the issue, but I believe the best thing to start with would be (1) open offers , (2) last traded price (3) if in collection, take floor price. Probably algo should be max of all 3.

And I feel like I am forgetting something for the backend but well we will remember it I guess.

**Comment by kelsos** [comment]
> Thanks a lot! Looks okay.
> 
> So some comments on things that can be improved on the UI.
> ## Separate space between name and price

Let me check to see why the padding around doesn't work.

> 
> 
> It would be nice if there was some way to separate the name and the price area. The name seems too big.
> ## Make tiles smaller. Fit more in same space.

> Opensea fullscreen
> 
> 
> 
> rotki fullscreen
> 
> 

Let me see if that doesn't mess with the smaller sizes in the same width bucket.

> I think you can make our tiles smaller and as such fit more in the same space as opensea does
> ## Overflow of name
> 
> 
> 
> This probably ties with the name + price separation comment I made above. But as you can see the name somehow does not shorten for some NFT and pushes itself even out of the tile.

Ok, that is really weird. This is the same exact component that gets repeated. One would guess that there would be a uniform appearance in all the instances.

> Check lefteris.eth NFTs to replicate.
> ## Funny look at address filtering
> Peek.2021-09-07.23-55.mp4

Hmm, I haven't tried with only an address there. The accounts I tried had labels and that appeared properly let me have a look.
> The address filtering menu looks funny once I use it to filter by address
> ## Image missing NFTs
> 
> 
> 
> Can we find a bit better generic NFT image than this? Not really a biggy. I think you also mentioned this as an open question at standup.

If you can find something better feel free to replace it. I made that quickly in Inkscape using the same icons from the icon set we use.

> 
> 
> Also what is the difference between those two? One has no image and the other the "no image" image.
In the one with the placeholder, the imageUrl is falsy (null/empty string) whatever in the other case it is not.

> ## Handling of the free version limit is missing
> The free version limit is missing. We discussed in the standup you would implement it. Just leaving a reminder here.
> 

It should not, I tried that and it worked. It should appear on top. I can check again but did you check before adding the premium keys or after?

> Non ui-related comments for backend:
> 
>     1. I created a new account, added premium keys, added my lefteris.eth account and then only saw 5 NFTs. Same as free limit. Something is off there with the addition of the api keys not being properly forwarded. I should check this out. After re-login worked fine.
> 
>     2. Need to implement the pricing data properly. There are many suggestions in the issue, but I believe the best thing to start with would be (1) open offers , (2) last traded price (3) if in collection, take floor price. Probably algo should be max of all 3.
> 
> 
> And I feel like I am forgetting something for the backend but well we will remember it I guess.

**Comment by kelsos** [comment]
The image you asked about, if I open it directly using brave it will render properly. If I open the frontend using brave or electron then it will render as blank when used as a v-img source.

If I open it OpenSea I can also see the same issue we are facing so my guess is that there is a problem with the specific SVG and chrome. If I open the same link with Firefox it will render properly. There is not much I can do here.

image

**Comment by LefterisJP** [comment]
> The image you asked about, if I open it directly using brave it will render properly. If I open the frontend using brave or electron then it will render as blank when used as a v-img source.
> 
> If I open it OpenSea I can also see the same issue we are facing so my guess is that there is a problem with the specific SVG and chrome. If I open the same link with Firefox it will render properly. There is not much I can do here.
> 
> image

understood. So that is a specific problem of that image. No worries.

**Comment by LefterisJP** [comment]
> It certainly works. I created a new account without premium.
> image

It does. I checked myself too right now.

**Review by LefterisJP — COMMENTED** [review]
All right so from the comments in the previous review all are fixed except the one about:

> I think you can make our tiles smaller and as such fit more in the same space as opensea does

Do you think this can be done? Could it actually maybe also be configurable? How many tiles per row?

**Comment by kelsos** [comment]
> All right so from the comments in the previous review all are fixed except the one about:
> 
> > I think you can make our tiles smaller and as such fit more in the same space as opensea does
> 
> Do you think this can be done? Could it actually maybe also be configurable? How many tiles per row?

The tiles should also adjust on 720p it should show 8 and in 1080p + it should show 10.

**Comment by kelsos** [comment]
I could make it adjust somewhere in between but they might be too crowded or too small in some cases when the menu is open 

localhost_8080_(FHD)

**Review by LefterisJP — APPROVED** [review]
LGTM @kelsos 

> The PR modified the frontend, and updated the user guide to reflect the changes.

Do you think the usage guide should be updated as part of this PR or later? To include the NFT gallery.

**Pull request merged**
