### PR TITLE
Adds more returns types and introduces eslint cache

### PR DESCRIPTION
**Pull request by kelsos**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
@LefterisJP if this change works, code analysis and eslint will run when `develop` has changes.

If it works, this will create a baseline for code analysis and a baseline cache for frontend PRs. I am trying the `--cache` option locally, which saves a lot of waiting time. 

I had no idea it existed, I was looking for ways to optimize performance today and I came across an article :)

If it doesn't I just have to revert the `rotki_ci.yml` modifications

**Comment by LefterisJP** [comment]
I see thanks. Anyway we can apply this to backend PRs? Or just talking about the eslint thing?

**Comment by kelsos** [comment]
I need to check how it will work on develop, I might have to do a follow up if things don't work but the idea is that we will run only code-analysis for the baseline to compare (both backend/frontend) and also create a lint cache that PRs can use.

**Review by LefterisJP — COMMENTED** [review]
everything seems green here

**Pull request merged**
