### PR TITLE
Fix different issues

### PR DESCRIPTION
**Pull request by yabirgb**
- Fixes wrong key on balancer query
- Fixes icon used by the app for aura
- Updates polars version since the prev one is yanked

Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Review by prettyirrelevant — APPROVED** [review]
lgtm

**Review by LefterisJP — CHANGES_REQUESTED** [review]
Does not look good to me! Such a non-epic PR for the 9,000th PR.

Boooo

1ypyrl


I request changes by creating a time machine and re-doing it!

**Comment by yabirgb** [comment]
I got one approve from isaac ma fren. So I'll merge

**Comment by LefterisJP** [comment]
> I got one approve from isaac ma fren. So I'll merge

Shit you can do that? @kelsos we must un-admin him. He is too powerful

**Comment by yabirgb** [comment]
imagen

**Pull request merged**
