### PR TITLE
Add blockchain account tags and labels

### LINKED ISSUE #461: Add the ability to tag blockchain accounts
## Abstract

Currently, you add an account solely by this address.

## Motivation

Unless you know all your address (which is likely not the case) you may have a hard time remembering where an account comes from. Is that a hardware wallet? An app on your phone? Some metamask somewhere, ...

## Specification

When Adding a blockchain account, I suggest adding an option field for the name of that account. Improving further, the ability to tag accounts would likely be very handy.

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix #461

### CODE REVIEW

**Comment by kelsos** [comment]
- I don't remember blocking adding before. Do you think it would make sense to block it? Is there any technical reason blocking us from adding accounts when loading?
- Editing has to be part of the account table which (along with the display of the label and tags). These are not ready yet (I am still planning to get them done today). The feedback was to be about the tag manager :smiley: 
- Sure I will do so :+1: 
- "Too big" is way too abstract, could you clarify what is too big? width, height? the height of [canvas](https://vuetifyjs.com/en/components/color-pickers#canvas). To be honest though, compared to most of the color pickers I have seen in applications so far, for me, it looks pretty standard sized. Maybe we could make it display on demand somehow and not always be visible. 
- What do you mean by "red-ish" does the hex change without you changing it when you save?
- Like I mentioned above not done yet :stuck_out_tongue:

**Comment by LefterisJP** [comment]
> I don't remember blocking adding before. Do you think it would make sense to block it? Is there any technical reason blocking us from adding accounts when loading?

It's blocked I think since adding an account also queries the chain and the chain is already being queried at that moment.

> Too big" is way too abstract, could you clarify what is too big? width, height? the height of canvas. To be honest though, compared to most of the color pickers I have seen in applications so far, for me, it looks pretty standard sized. Maybe we could make it display on demand somehow and not always be visible.

The whole thing is just too big imo. Mostly height, as I would have liked to see the tables of existing tags easier without too much scrolling.

> What do you mean by "red-ish" does the hex change without you changing it when you save?

It changes every time I save, but not at the color I set at the picker. And every change it is set to a reddish color and not the one I chose.

**Comment by kelsos** [comment]
> It's blocked I think since adding an account also queries the chain and the chain is already being queried at that moment.

Ok, fair point. I will do the changes to block it.

> The whole thing is just too big IMO. Mostly height, as I would have liked to see the tables of existing tags easier without too much scrolling.

I see, I would still prefer not to reduce the height of the widget since it would become too small. 
What is your opinion about not showing it by default? I need to see how it would be done since it would not be nice to have a modal in another modal but maybe have a regular text field where you can add the hex that displays this as a *menu* when you focus.

> It changes every time I save, but not at the color I set at the picker. And every change it is set to a reddish color and not the one I chose.

That is definetely weird. I don't remember it happening. I will have to check it.

**Comment by LefterisJP** [comment]
> I see, I would still prefer not to reduce the height of the widget since it would become too small.
What is your opinion about not showing it by default? I need to see how it would be done since it would not be nice to have a modal in another modal but maybe have a regular text field where you can add the hex that displays this as a menu when you focus.

Maybe let's leave this for after the release. It's cosmetic and not that important. Focus on the rest for now.

**Comment by LefterisJP** [comment]
Okay (3) with tag deletion is backend's fault. Funny .. I thought I was handling that correctly. Deleting a tag that is already utilized by others should first remove the tag from those accounts. (hence the foreign key error)

**Comment by LefterisJP** [comment]
Comment (3) should be handled by now

**Comment by LefterisJP** [comment]
Rebased on develop

**Pull request merged**
