### PR TITLE
fix: exchange input for cex mapping

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
@lukicenturi what are we fixing here exactly?

**Comment by lukicenturi** [comment]
> @lukicenturi what are we fixing here exactly?

so the `exchange` data from `locations` endpoint.
In the exchange form I want to only show the ones with api key
while in the manage cex mapping, I want to show all exchange data.

**Comment by kelsos** [comment]
OK so on my side it looks fine if it's ok with @yabirgb too we can proceed and merge.

**Review by yabirgb — APPROVED** [review]
L
G
T
M

**Pull request merged**
