### PR TITLE
Base L2 frontend support

### PR DESCRIPTION
**Pull request by 0xGusMcCrae**
Frontend support for Base

### CODE REVIEW

**Review by lukicenturi — COMMENTED** [review]
Looks good at a glance, since you just copy from arbitrum

**Comment by lukicenturi** [comment]
Looks like it missing the icon

**Comment by tewshi** [comment]
> Looks like it missing the icon

yeah, here @0xGusMcCrae :
image

**Review by tewshi — APPROVED** [review]
lgtm!

**Comment by lukicenturi** [comment]
I will adding the icon

**Pull request merged**
