### PR TITLE
Fix kraken for missing result response in balances

### LINKED ISSUE #2243: Change the trade database and datastructure format to accept assets instead of a pair
## Abstract

Related to #2240 (it does that only in the frontend part)

Change the backend DB schema for trades to accept individual assets and not a trade pair. This is going to be a big improvement as the legacy format of having a trade pair is much harder to work with as you need to always serialize to/from a pair each time you want to analyze a trade.

## Task

- [ ] Change the DB schema to accept assets instead of a pair string
- [ ] Change the data structure to use assets instead of a pair string
- [ ] Add a DB upgrade to upgrade all places where trades with a pair were used to the new schema. This needs A LOT of testing.
- [ ] Change all places in the code where the new schema needs to be used.

### LINKED ISSUE #2443: Cannot set up Kraken API if Kraken has no balances
## Problem Definition

It fails every time I try to add my Kraken API keys:

kraken 

The keys are definitely correct ;-)  I have tried this several times.

## Logs

```
[25/02/2021 18:07:46 GMT] DEBUG rotkehlchen.exchanges.manager: Initializing exchanges
[25/02/2021 18:07:46 GMT] INFO rotkehlchen.exchanges.exchange: Initialized kraken exchange
[25/02/2021 18:07:46 GMT] DEBUG rotkehlchen.exchanges.kraken: Kraken API query method=Balance, data=None, call_counter=0
[25/02/2021 18:07:47 GMT] DEBUG rotkehlchen.exchanges.coinbasepro: Got report for id: 90d122b0-a7ca-4b3a-ad3a-c2127f14003e with length 95. Skipping it
[25/02/2021 18:07:47 GMT] DEBUG rotkehlchen.exchanges.coinbasepro: Coinbase Pro API query request_method=GET, request_url=/reports/6c8980e1-fd65-47b9-8318-b7023118171b, options={}
[25/02/2021 18:07:47 GMT] ERROR rotkehlchen.exchanges.kraken: Kraken API key validation error: Unexpected format of Kraken response. Missing key: 'result'
[25/02/2021 18:07:47 GMT] ERROR rotkehlchen.exchanges.manager: Failed to validate API key for exchange name=kraken, error=Unknown error at Kraken API key validation. Perhaps API Key/Secret combination invalid?
[25/02/2021 18:07:47 GMT] DEBUG rotkehlchen.api.rest: Request successful response={"result": null, "message": "Unknown error at Kraken API key validation. Perhaps API Key/Secret combination invalid?"}, status_code=409
```

### System Description

Operating system: openSUSE Tumbleweed
Rotki version: git `develop` branch, previously seen with older AppImage releases too

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix #2443

Also add a regression test for it

### CODE REVIEW

**Comment by LefterisJP** [comment]
hey @aspiers if you try this patch it will probably work with your kraken api key

**Comment by aspiers** [comment]
AFAICS this fixed it for me:

```
[26/02/2021 00:29:51 GMT] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "OPTIONS /api/1/exchanges HTTP/1.1" 200 327 0.000865
[26/02/2021 00:29:51 GMT] DEBUG rotkehlchen.exchanges.manager: Initializing exchanges
[26/02/2021 00:29:51 GMT] INFO rotkehlchen.exchanges.exchange: Initialized kraken exchange
[26/02/2021 00:29:51 GMT] DEBUG rotkehlchen.exchanges.kraken: Kraken API query method=Balance, data=None, call_counter=0
[26/02/2021 00:29:51 GMT] DEBUG rotkehlchen.exchanges.kraken: Kraken API query method=TradesHistory, data={'start': 0, 'end': 0}, call_counter=1
[26/02/2021 00:29:52 GMT] DEBUG rotkehlchen.exchanges.kraken: Kraken API query method=Ledgers, data={'start': 0, 'end': 0, 'type': 'deposit'}, call_counter=3
[26/02/2021 00:29:53 GMT] DEBUG rotkehlchen.api.rest: Request successful response={"result": true, "message": ""}, status_code=200
[26/02/2021 00:29:53 GMT] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "PUT /api/1/exchanges HTTP/1.1" 200 219 2.039102
[26/02/2021 00:29:53 GMT] DEBUG rotkehlchen.api.rest: Request successful response={"result": {"task_id": 11}, "message": ""}, status_code=200
[26/02/2021 00:29:53 GMT] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/exchanges/balances/kraken?async_query=true HTTP/1.1" 200 230 0.001948
[26/02/2021 00:29:53 GMT] DEBUG rotkehlchen.exchanges.kraken: Kraken API query method=Balance, data={}, call_counter=5
[26/02/2021 00:29:55 GMT] DEBUG rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
```

**Comment by LefterisJP** [comment]
Thank you @aspiers !

**Comment by LefterisJP** [comment]
Merged since the failing test was from blockchain.info 503ing

**Pull request merged**
