### PR TITLE
Introduces ui for manual price management

### LINKED ISSUE #1520: Allow adding price for a token/asset if no price can be found
## Abstract

If a price for a token or asset cannot be automatically found, give the user the ability to enter the price manually. This issue combines well with [this other issue](https://github.com/rotki/rotki/issues/1519) to allow for custom Ethereum tokens.

## Motivation

Custom tokens are sometimes small enough to not be listed on traditional exchanges, or, they will eventually get listed, but are not yet. I want to be able to record my transactions after they happen on exchanges like Uniswap who allow for custom token listings, but may not have great interfaces for the traditional price of the token until it becomes more popular.

## Specification

Here is an example of an interface I have used to accomplish this in a different program.

Example

### PR DESCRIPTION
**Pull request by kelsos**
Closes  #1520

### CODE REVIEW

**Comment by yabirgb** [comment]
1. I (as a stupid human) failed to read the filter prices and expected for some reason after adding a from and to asset that if I click on the `+` it will ask me for a prices. Would it be possible to add this option? Like if I have information in the filter if I click on `+` i get the form partially completed?
2. If an user adds decimals with `,` instead of `.` it shows an error from the backend. Could this be validated by the frontend before sending it to the backend?

**Comment by kelsos** [comment]
> ## Separation of addition and filtering
> 
> I found that quite strange.
> 
> 
> 
> Judging from the hugeass "+" button on the top right, I thought I could add the price of from/to assets when I pressed the button but that was not the case. This is just a filter.
> 
> I think it would make sense to separate the addition menu somehow from the filter as it's confusing liek this.

I will proceed with the change although I am not sure why would someone expect that the button would add directly when pressed instead of opening the bottom dialog, or why a section that has a "Filter" header would be anything else than a filter :). 

This behavior is quite consistent across the app (with a small exception for the exchange balances when there is no exchange added where it navigates you to the exchange API screen). There is no place where the plus button directly adds something.

**Comment by kelsos** [comment]
>     1. I (as a stupid human) failed to read the filter prices and expected for some reason after adding a from and to asset that if I click on the `+` it will ask me for a price. Would it be possible to add this option? Like if I have information in the filter and I click on `+` i get the form partially completed?
> 

Good suggestion @yabirgb it is trivial to add it :)

>     2. If an user adds decimals with `,` instead of `.` it shows an error from the backend. Could this be validated by the frontend before sending it to the backend?

It shouldn't be hard to do that let me check

**Comment by LefterisJP** [comment]
> Good suggestion @yabirgb it is trivial to add it :)

This may actually address my concern too @kelsos. Since the end result would be the same. I had the exact same expectation when I pressed it.

> It shouldn't be hard to do that let me check

Would that apply to all numbers? Since we don't have `,` separate decimals anywhere in the input, right?

**Comment by isidorosp** [comment]
> > 2. If an user adds decimals with `,` instead of `.` it shows an error from the backend. Could this be validated by the frontend before sending it to the backend?
> > ```
> 
> It shouldn't be hard to do that let me check

We have a user setting for what the decimal separator should be, right? Whenever we have values input from users we should probably be using that setting to determine (a) what decimal separator is acceptable for value inputs and (b) whether we need to transform the input before sending it to the backend or not.

**Comment by LefterisJP** [comment]
> > > 1. If an user adds decimals with `,` instead of `.` it shows an error from the backend. Could this be validated by the frontend before sending it to the backend?
> > 
> > 
> > It shouldn't be hard to do that let me check
> 
> We have a user setting for what the decimal separator should be, right? Whenever we have values input from users we should probably be using that setting to determine (a) what decimal separator is acceptable for value inputs and (b) whether we need to transform the input before sending it to the backend or not.

yeah that is true but I don't know if this is applied at the input. I guess not (I have not tried). This would be a different issue/feature unrelated to this PR that we can make!

**Comment by kelsos** [comment]
The settings we have are only affecting display and not input, if we would like to start applying something like this it needs to go to a new issue.

**Comment by LefterisJP** [comment]
@isidorosp can you make an issue for this? It's one of those nice to haves. I guess some kind of input transformer can exist which will transform the input to the normal decimal input the backend expects "3.15" etc.

**Comment by kelsos** [comment]
> If it won't look good we can also do without the "on" column.

No need to overdo it

**Comment by LefterisJP** [comment]
> > If it won't look good we can also do without the "on" column.
> 
> No need to overdo it

Well if it fits, does not break the table and does not take much time it may actually look good. Curious to see how it would look.

Can be done/expermented with later also if it's hard.

**Review by LefterisJP — APPROVED** [review]
I am going to approve the PR as the changes are there.

But there is a few more stuff that need to be done and can be done in another PR.

1. For historical oracles the manual oracle should also be selectable and its order should be decided from the frontend. (default should be first).





2. When editing a price entry I see only the price is editable. Is this a limitation from the api @yabirgb ?


3. @yabirgb for completeness sake please test what I wrote here so we are sure the whole thing is working: https://github.com/rotki/rotki/pull/3177#pullrequestreview-705470176

**Comment by yabirgb** [comment]
@LefterisJP About the manual price I was tempted to add it in the manual price oracle but don't know if it makes sense. Prices from coingecko/cryptocompare I believe will be accurate always and manual prices should be used when prices from this oracles are not available

**Comment by LefterisJP** [comment]
> @LefterisJP About the manual price I was tempted to add it in the manual price oracle but don't know if it makes sense. Prices from coingecko/cryptocompare I believe will be accurate always and manual prices should be used when prices from this oracles are not available

**absolutely not**

Coingecko cryptocompare is very very often wrong. This new feature is the only way to correct a broken price by those oracle.

By default manual price entry should come before anything else. Not to mention you save at least 2 api queries if you first query the DB for a cached price.

**Comment by yabirgb** [comment]
1. Created a ledger action of income for `yvsteCRV` (yearn asset without oracles' prices) with value of 100 units
2. Set manually a price at the given timestamp of 5 USD for each `yvsteCRV`
3. Run profit and loss report

image

**Pull request merged**
