### PR TITLE
Support Compound SAI

### PR DESCRIPTION
**Pull request by LefterisJP**
https://www.coingecko.com/en/coins/compound-sai

For @coinyon

### CODE REVIEW

**Comment by coinyon** [comment]
Thanks, but this is not working correctly. Probably cryptocompare does not have DAI data for that point in time.

> during history processing due to inability to reach an external service at that time: Failed to query cryptocompare for: "https://min-api.cryptocompare.com/data/v2/histohour?fsym=CSAI&tsym=DAI&limit=2000&toTs=1427270300". Error: There is no data for the toSymbol DAI 

The query works when `tsym=SAI` is used.

**Comment by isidorosp** [comment]
I don't think it's the date, it's that the query is trying to convert from cSAI to DAI. If you do fsym=SAI and tsym=DAI it works. What's the context of that error/call?

**Comment by LefterisJP** [comment]
@coinyon Why was it checking cSAI to DAI? It should be CSAI to SAI

**Comment by coinyon** [comment]
Yes, the trade pair is `cSAI_SAI`, don't know why it is choosing `DAI`. I'll investigate...

**Comment by coinyon** [comment]
Found it. Will make PR

**Comment by coinyon** [comment]
#1128

**Pull request merged**
