### PR TITLE
Moves dmg-license to dev dependencies, fixes win ps-list path

### PR DESCRIPTION
**Pull request by kelsos**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
@LefterisJP this seems to fix builds on mac and windows so we can merge it after CI passes

**Review by LefterisJP — COMMENTED** [review]
Frontend failed again. This really needs to be fixed somehow as we don't know how to evaluate easily and end up ignoring. I am restarting it.

**Review by LefterisJP — APPROVED** [review]
Okay 2nd time passed so I will go ahead and merge to hopefully fix the build in the CI.

**Comment by kelsos** [comment]
Great, I saw it failed but I didn't have more time to investigate.

Glad the restart fixed it.

**Pull request merged**
