### PR TITLE
feat: remove composables and utils import

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

**Comment by kelsos** [comment]
Are the failed tests due to flakiness?
We need to figure out a way to make the tests less flaky it has become really annoying.

**Comment by lukicenturi** [comment]
the auto-import not working for e2e spec files, so I will rollback those files

**Comment by lukicenturi** [comment]
This should be ready @kelsos

**Comment by kelsos** [comment]
> the auto-import not working for e2e spec files, so I will rollback those files

We probably need to add it to the ts-config there but Let's merge things as they are now.

**Review by kelsos — APPROVED** [review]
lgtm

**Pull request merged**
