### PR TITLE
Update README.md - fix grammatrical errors in README.

### PR DESCRIPTION
**Pull request by sonijogesh**
I have noticed some grammatical mistakes in **README** inside section "**Features at a glance**"

"**Shows overview of your..**"  should be "**Shows an overview of your..**"

" **blockchain, exchanges and protocols...**"  should be " **blockchain, exchanges, and protocols...**"

Screenshot-

Screenshot (106)

### CODE REVIEW

**Comment by sonijogesh** [comment]
Please review my PR.

**Comment by LefterisJP** [comment]
> Please review my PR.

Make only **A SINGLE** pr for all things you want. Do not spam our repo with multiple PRs.

**Comment by LefterisJP** [comment]
I am closing the PR. You are spamming our repo and not following what I asked of you.

**Comment by sonijogesh** [comment]
ya, sorry because there was an internet problem.
I have closed another one.

**Comment by sonijogesh** [comment]
Please open this issue, there was actually internet problem from my side , i thought that the PR was opened but it didn't , that's why I made it once more.

**Pull request closed without merging**
