### PR TITLE
Add $CAPS asset

### PR DESCRIPTION
**Pull request by CPatchane**
Add Ternoa token, $CAPS

[Coingecko](https://www.coingecko.com/en/coins/ternoa)
[Project website](https://www.ternoa.com/en)

### CODE REVIEW

**Comment by yabirgb** [comment]
@CPatchane Thanks for taking the time to add a new asset! Unfortunately now we have a different way of adding assets. I'll take this information and add to the database the asset. Since a few versions ago we use a different system with versions at the rotki/assets repository


 I'm on the phone rn but I'll check if the information is outdated in the docs.

**Comment by CPatchane** [comment]
Oh ok, I didn't know about that new way, I saw the old one in the contribution documentation 🙈
What is the new process btw?

Feel free to do it on your side if it's better/faster and close this PR :)

**Comment by yabirgb** [comment]
@CPatchane Here you have some instructions https://github.com/rotki/assets

We release an assets versions in every major release of rotki. You will need to create a folder for the next version (`7`) with an `updates.sql` file inside the `updates` folder and also update the `info.json` file.

If you want to do it go ahead :) You already have the information. The only thing is that for the name in ethereum tokens we use the name method of the contract. In this case is `Capsule Coin`

**Comment by yabirgb** [comment]
@CPatchane I had to add a couple more of assets and went ahead with this one. In case you want to see how this is done here is the PR https://github.com/rotki/assets/pull/45 . About the coingecko id you provided it was incorrect. This is something that coingecko does poorly and is that the web interface has different ids than the used in the prices API. Usually what I do is check the id [here](https://api.coingecko.com/api/v3/coins/list) before adding it.

Thank you for the pull request! Thes asset will be included in 1.20. In the meantime you can add it manually to your local rotki database in case you didn't https://rotki.readthedocs.io/en/latest/usage_guide.html#customization-of-the-list-of-supported-assets

**Pull request closed without merging**
