### PR TITLE
Introduces overview of defi protocols

### PR DESCRIPTION
**Pull request by kelsos**

### CODE REVIEW

**Comment by LefterisJP** [comment]
> In the front-end console we get this warning:

That problem **is** also on develop

> The exchange balances don't work. If I click on any exchange they no longer work. Not sure if it's from this PR or from something added at the end of the last PR.

That **is not** on develop. On develop it works fine.

> I get a funny "False" string along with a separating line after ETH per account balances and also one after BTC per account balances as seen in the picture:

That problem **is** also on develop

**Comment by isidorosp** [comment]
> > I get a funny "False" string along with a separating line after ETH per account balances and also one after BTC per account balances as seen in the picture:
> 
> That problem **is** also on develop

Debug print was left in #1160 by accident.
Delete Ln 154 in AccountBalances.vue to fix this
```
...
Ln 153       ></confirm-dialog>
Ln 154       {{ privacyMode }}
Ln 155     </div>
...
```

**Comment by LefterisJP** [comment]
> Debug print was left in #1160 by accident.

Hah! Surprised detective @kelsos missed this :)

giphy

**Comment by isidorosp** [comment]
> > Debug print was left in #1160 by accident.
> 
> Hah! Surprised detective @kelsos missed this :)
> 
> giphy

Pika pika needs a holiday methinks.

**Comment by kelsos** [comment]
Well, some times some things might be missed :) it happens :P

**Pull request merged**
