### PR TITLE
Introduces unified packaging for Linux, OSX and windows

### PR DESCRIPTION
**Pull request by kelsos**
- Introduces new unified PowerShell script for building the Windows binary
- Creates a new packaging workflow on github actions
- Removes deploy tasks from travis
- Removes AppVeyor configuration
- Ensures that SQLCipher 4.4.0 is used on all OSes
- Updates Author

I Tested it on the fork with consecutive new tags
image

Artifacts were uploaded properly to the draft release
image

I did smoke tests of launching the generated AppImage, dmg, exe on the respective OSes and everything seems to work fine.

### CODE REVIEW

**Comment by kelsos** [comment]
@LefterisJP we should remove AppVeyor completely and probably also close #146
I am not sure about #855 (maybe we can change that to introducing E2E test runs on windows/OSX on nightlies)

**Review by LefterisJP — APPROVED** [review]
From a quick look, looks good to me. Interesting way of using diffs for sqlcipher.

Also nice to see part of an editable release template

**Comment by LefterisJP** [comment]
Edited #855 and will close #146

**Comment by LefterisJP** [comment]
Also removed the appveyor webhooks. But why is test-e2e fail in the ci?

**Pull request merged**
