### PR TITLE
Introduces a common frontend library

### PR DESCRIPTION
**Pull request by kelsos**
- [x] Add linting for new library
- [x] Ensure that components can build 
- [x] Make sure that CI build pass
- [x] Update documentation about installing dependencies/working with frontend

### CODE REVIEW

**Comment by kelsos** [comment]
Both PRs should be ready for review if anything is unclear please let me know.
The first step after checking this change is to go to the `frontend` folder (not `frontend/app`) and do an
`npm ci` and then do an `npm run build -w @rotki/common` to build the common library.

Then you can start the app like normal for the components the instructions are in the PRs readme.
You need to update the directory in your `.env` in the `dev-proxy` since the structure changed a bit

**Comment by kelsos** [comment]
Remember to and a nvmrc file in the frontend directory

**Comment by kelsos** [comment]
- [ ] Bump the requirement for minimum npm 7 version. Older versions run into an infinite loop when working with workspaces.

**Review by LefterisJP — APPROVED** [review]
Seems to work.

As we discussed the guide needs to be improved a bit since I had a few hiccups while trying to make it work.

**Pull request merged**
