### PR TITLE
Add ETH-C Makerdao vault. Closes #2713

### LINKED ISSUE #2713: Detected vault with collateral_type ETH-C. That is not yet supported by rotki. Skipping...
## Problem Definition

Please add ETH-C MakerDAO vault to Rotki.

## Logs

Backend messages:
```
Detected vault with collateral_type ETH-C. That is not yet supported by rotki. Skipping...
```

### PR DESCRIPTION
**Pull request by yabirgb**
Got the ETH-C join address from https://github.com/makerdao/pymaker/blob/master/config/mainnet-addresses.json#L45 , a makerdao repo

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
hey @yabirgb can you make sure that all other missing collateral types are added? More could be missing.

You can get all address details from their changelog: 
https://changelog.makerdao.com/
e.g. latest: https://changelog.makerdao.com/releases/mainnet/1.2.10/contracts.json

And you can see all possible types in oasis:

https://oasis.app/borrow/

Ignore the UNIV2 lp pair types.

**Comment by yabirgb** [comment]
@LefterisJP I've checked with the oasis lists and all are in there except for the uni lp.

**Comment by LefterisJP** [comment]
The failing test is a 500 error on a kusama open node: 

```
ERROR rotkehlchen.chain.substrate.manager: Kusama failed to request KSM account balance at endpoint https://kusama-rpc.polkadot.io/ due to: RPC request failed with HTTP status code 500 account=GLVeryFRbg5hEKvQZcAnLvXZEXhiYaBjzSDwrXBXrfPF7wj
```

unrelated.

**Review by LefterisJP — APPROVED** [review]
Thanks. Should work. LGTM.

**Pull request merged**
