### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by kelsos**
- Updates frontend dependencies
- Updates dev-proxy dependencies
- Adds npm/node version checking
- Updates CI to node 14 and npm 7

### CODE REVIEW

**Review by LefterisJP — COMMENTED** [review]
check-frontend is failing here.


And omg the number of line changes.

**Review by LefterisJP — COMMENTED** [review]
It even shows you where the problems is btw

**Comment by kelsos** [comment]
> check-frontend is failing here.
> 
> And omg the number of line changes.

It is updating the dependencies and moving to v2 of the lockfile format since we upgrade to npm 7

**Comment by LefterisJP** [comment]
> It is updating the dependencies and moving to v2 of the lockfile format since we upgrade to npm 7

hah yeah I know. But every time I see it my eyes pop out :smile:

**Comment by kelsos** [comment]
the nightly build seems fine: https://github.com/rotki/rotki/actions/runs/642645524

**Review by LefterisJP — APPROVED** [review]
> the nightly build seems fine: https://github.com/rotki/rotki/actions/runs/642645524
> 
> I will check the other binaries later, linux seems good.

did you check them? I mean already you seem to have done a good sanity check. I will approve on my side and you do what you  need

**Comment by kelsos** [comment]
Did a quick smoke test on every platform, all seems good.

**Pull request merged**
